### ISSUE TITLE
Poor performance paging through large result sets

### ISSUE THREAD

**Issue by ajdavis** [SoftInstigate/restheart#1]
MongoDB queries with a large "skip" slow down linearly. As [the manual says](http://docs.mongodb.org/manual/reference/method/cursor.skip/):

> The cursor.skip() method is often expensive because it requires the server to walk from the beginning of the collection or index to get the offset or skip position before beginning to return result. As offset (e.g. pageNumber above) increases, cursor.skip() will become slower and more CPU intensive. With larger collections, cursor.skip() may become IO bound.

I'm concerned that RESTHeart's API encourages users to page through large result sets using large "skip" values, see [CollectionDAO line 185](
https://github.com/SoftInstigate/restheart/blob/develop/src/main/java/com/softinstigate/restheart/db/CollectionDAO.java#L185). Paging through an entire result set this way is quadratic.

Instead of creating a new DBCursor object with a "skip" for each HTTP request, I suggest keeping the DBCursor object in memory and iterating it to return the next page of data. You can evict a partially-iterated cursor from memory after 10 minutes of inactivity since it will be deleted on the MongoDB server after 10 minutes. This will give optimal (linear) performance to iterate an entire result set.

**Comment by ujibang** [comment]
done! 

the eager cursor preallocation engine is now part of the development branch and addresses this issue.
some tests show a 10x performance improvement factor! (we are going to post details about this in our blog soon).

this enhancement will be part of upcoming 0.9.8 release.

thanks for guiding us in the right direction.

**Comment by ajdavis** [comment]
Cool, glad to help!

**Comment by ujibang** [comment]
FYI: we just published some performance [test results](http://restheart.org/docs/performances.html).

in most of the test scenarios, RESTHeart achieves better performances than a direct access with the MongoDb java driver!

Notably, on finds that involve skipping many documents, as you pointed out, MongoDB has poor performances while RESTHeart, with its eager preallocation dbcursors engine, does very well.

**Comment by AjitDeswal** [comment]
Instead of skip : we should go with range based example:-
a) If we want to see records without any sorting than 
    we should use (_id: {$gt : <lastId>}) in where clause.

b)if we want to see sorted results:-
example:-
_id value
1 a
2 b
3 c
4 a
5 b
6 c
than approach will fails.
so to handle this we have to modify our where clause just as below:-

db.<collection>.find(
{$or:
    [
        {$and : 
            [
                {<sort key>:{$gte: <last sort key value of previous page>}},
                {"_id" : {$gt : <last  result id of previous page>}}
            ]
        },
        {<sort key> :{$gt: <last sort key value>}}
    ]
}.
sort({<sort key>:1}).limit(10)

This will work for you 👍 ....
I have written a demo code where i have implemented this with application level cache to maintain
last page info.

**Comment by ujibang** [comment]
Hi @AjitDeswal 

when dealing with large collections, range based paging is indeed the best approach; this is also suggested in the [mongodb documentation](https://docs.mongodb.com/manual/reference/method/cursor.skip/):

> Consider using range-based pagination for these kinds of tasks. That is, query for a range of objects, using logic within the application to determine the pagination rather than the database itself. This approach features better index utilization, if you do not need to easily jump to a specific page.

Now, RESTHeart returns paged results when GETting a collection; when a client requests `GET /db/collection?page=X` the cursor pool feature discussed here, pre-allocates cursors to speed up requests for pages near X following the "Principle of locality".

This is happening despite the fact that the client is specifying or not a range based query. 

So for instance:

`GET /db/collection?filter={"$and":[{"a": {"$gt": 100}}, "{"a": {"$lt: 200} }]}&sort={"a": 1}`

leads to preallocating cursors with same _filter_ and _sort_ options.

These preallocated cursors will speeded up:

`GET /db/collection?filter={"$and":[{"a": {"$gt": 100}}, "{"a": {"$lt: 200} }]}&sort={"a": 1}`
`GET /db/collection?page=2&filter={"$and":[{"a": {"$gt": 100}}, "{"a": {"$lt: 200} }]}&sort={"a": 1}`

But the following request will **not** be speeded up:

`GET /db/collection?filter={"$and":[{"a": {"$gt": 200}}, "{"a": {"$lt: 300} }]}&sort={"a": 1}`

As long as I understand you are proposing _something_ like:

`GET /db/collection?page=X&rangePaging={"$and":[{"a": {"$gt": "$page*100"}}, "{"a": {"$lt: {"$page*100+100"}} }]}&sort={"a": 1}`

The _rangePaging_ parameter would tell RESTHeart how to page the collection, and the cursor pool would preallocate cursors accordingly.

In essence, we don't use skip anymore but pure range based paging...

Have I got your point?
