### ISSUE TITLE
Issues with restheart aggregate query using a REST client

### ISSUE THREAD

**Issue by afolaran** [SoftInstigate/restheart#101]
Hello.

I am having problems running an aggregate query with restheart using a REST client. The documentation does not seem to be clear enough for me on this. I have created a test database and collection just to see how it works. I select PUT/POST as my HTTP method and then insert 

aggrs:='[\ {"type":"pipeline",\ "uri":"total-by-item",\ "stages": [\ {"_$match": { "Item": { "_$var": "Item"}}},\ {"_$group": { "_id": "$Item", "total": {"_$sum": "$Amount"}}}]}]'

in the body section to create the aggrs metadata but it does not work at all. It returns the following error message;

"http status code": 406,
"http status description": "Not Acceptable",
"message": "Invalid JSON", 

I have tried to adjust the syntax in different ways but I keep getting error messages. I know the problem is in my declaration of the metadata. Please kindly make available to me the proper syntax for carrying out the aggregation operation as well syntax for even inserting documents into a collection using a REST client. 

I look forward to your response. Thanks

**Comment by ujibang** [comment]
first try to remove the \

second, from the documentation:
> Note that the dollar prefixed operators in stages must be underscore escaped, e.g. "_$exits"

so it should be (I haven't tested it)
```
aggrs:='[ {"type":"pipeline", "uri":"total-by-item", "stages": [  {"_$match": { "Item": { "_$var": "Item"}}}, {"_$group": { "_id": "$Item", "total": {"_$sum": "$Amount"}}}]}]'
```

**Comment by afolaran** [comment]
Hello Andrea. I tried it and it still returns the same error.

"http status code": 406,
"http status description": "Not Acceptable",
"message": "Invalid JSON"

I think you should try it also and see if it works cos now I am stuck and cannot make progress with my project work because of this. I need to successfully make an aggregation query using a REST client. I believe the problem is still with the syntax. I look forward to your response. Thanks.

**Comment by ujibang** [comment]
Hello @afolaran 

I just tried it and it works for me!

This is what I have done (I used [httpie](https://github.com/jkbrzt/httpie); actually the **aggrs:=** syntax is specific of this client)

create the collection with the definition of the aggregation
```
$ http PUT 127.0.0.1:8080/test/issue101 aggrs:='[ {"type":"pipeline", "uri":"total-by-item", "stages": [  {"_$match": { "Item": { "_$var": "Item"}}}, {"_$group": { "_id": "$Item", "total": {"_$sum": "$Amount"}}}]}]'
HTTP/1.1 200 OK
...
```

tested the aggregation (no data)
```
$ http GET 127.0.0.1:8080/test/issue101/_aggrs/total-by-item?avars='{"Item":"a"}'
HTTP/1.1 200 OK
...

{
    "_returned": 0, 
    "_size": 0, 
    "_total_pages": 0
}
```

**Comment by afolaran** [comment]
Hello Andrea. I am afraid I am still facing some problems. I have installed httpie and I have successfully queried some collections in the database on my local machine. However, I still cannot carry out aggregation request. Below I provide a screenshot of the error message I got.

![error page](https://cloud.githubusercontent.com/assets/16158966/12815707/af78832e-cb50-11e5-81fe-e265ee564293.png)

**Comment by ujibang** [comment]
hi @afolaran 

I suggest you to write the json in a file, check the syntax and run

```
http -a a:a PUT 127.0.0.1:8080/db/coll < file.son
```

hope this is supported in windows!
