### ISSUE TITLE
How to get records more than1000?

### ISSUE THREAD

**Issue by singhvikram704** [SoftInstigate/restheart#109]
**I am getting the response below:**

 {    "_links": 
{    "self": 
{ "href": "/database/users?page=1&pagesize=1500"
  } },
    "http status code": ​400,
    "http status description": "Bad Request",
    "message": "illegal page parameter, pagesize must be >= 0 and <= 1000"
}

**How can i get records more than1000?**

**Regard
Vikram singh**

**Comment by ujibang** [comment]
you cannot have more than 1000 documents in a single response.

so you need to split your data retrieval in several requests:

```
GET /database/users?page=1
GET /database/users?page=2
...
```

**Comment by singhvikram704** [comment]
very thank you sir.
