### ISSUE TITLE
406 response on valid HTTP put request

### ISSUE THREAD

**Issue by samfromlv** [SoftInstigate/restheart#111]
Trying to upload file (GridFS) with this request using Microsoft C# System.Net.Http.HttpClient 

> PUT /oko/userphoto.files/1987 HTTP/1.1
> Authorization: Basic YWRtaW46Y2hhbmdlaXQ=
> Accept: */*
> Content-Type: multipart/form-data; boundary="asdasdasdasdasdasd2234vv45y3b4vhg3rtchg245"
> Host: 192.168.28.128
> Content-Length: 229
> Expect: 100-continue
> 
> --asdasdasdasdasdasd2234vv45y3b4vhg3rtchg245
> Content-Type: application/octet-stream
> Content-Disposition: form-data; name=file; filename=1987; filename*=utf-8''1987

Result:

> HTTP/1.1 406 Not Acceptable
> Connection: keep-alive
> Access-Control-Allow-Origin: *
> X-Powered-By: restheart.org
> Access-Control-Allow-Credentials: true
> Access-Control-Expose-Headers: Location, ETag, Auth-Token, Auth-Token-Valid-Until, Auth-Token-Location, X-Powered-By
> Content-Type: application/hal+json
> Content-Length: 1575
> Date: Sun, 21 Feb 2016 12:41:17 GMT
> X-Charles-Received-Continue: HTTP/1.1 100 Continue
> 
> { "_links" : { "self" : { "href" : "/oko/userphoto.files/1987"}} , "http status code" : 406 , "http status description" : "Not Acceptable" , "message" : "Error parsing the multipart form: data could not be read" , "_embedded" : { "rh:exception" : [ { "exception" : "java.io.IOException" , "exception message" : "UT000036: Connection terminated parsing multipart data" , "stack trace" : [ "java.io.IOException: UT000036: Connection terminated parsing multipart data" , "  at io.undertow.server.handlers.form.MultiPartParserDefinition$MultiPartUploadHandler.parseBlocking(MultiPartParserDefinition.java:217)" , "  at org.restheart.handlers.injectors.BodyInjectorHandler.handleRequest(BodyInjectorHandler.java:129)" , "  at org.restheart.handlers.OptionsHandler.handleRequest(OptionsHandler.java:58)" , "  at org.restheart.handlers.injectors.RequestContextInjectorHandler.handleRequest(RequestContextInjectorHandler.java:355)" , "  at org.restheart.security.handlers.CORSHandler.handleRequest(CORSHandler.java:88)" , "  at org.restheart.handlers.PipedHttpHandler.handleRequest(PipedHttpHandler.java:86)" , "  at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)" , "  at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)" , "  at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:793)" , "  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)" , "  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)" , "  at java.lang.Thread.run(Thread.java:745)"]}]}}
> 

If request is changed to remove quotes from boundary:

> PUT /oko/userphoto.files/1987 HTTP/1.1
> Authorization: Basic YWRtaW46Y2hhbmdlaXQ=
> Accept: */*
> Content-Type: multipart/form-data; boundary=35dafad7-391b-4450-bf0f-9cd4167463d6
> Host: 192.168.28.128
> Content-Length: 217
> Expect: 100-continue
> 
> --35dafad7-391b-4450-bf0f-9cd4167463d6
> Content-Type: application/octet-stream
> Content-Disposition: form-data; name=file; filename=1987; filename*=utf-8''1987
> 
> 	
> 

Result:

> HTTP/1.1 201 Created
> X-Powered-By: restheart.org
> Auth-Token-Location: /_authtokens/admin
> Access-Control-Expose-Headers: Location, ETag, Auth-Token, Auth-Token-Valid-Until, Auth-Token-Location, X-Powered-By
> Date: Sun, 21 Feb 2016 12:43:09 GMT
> Auth-Token: 891cb6bf-72b2-4839-9100-bd6289c82fae
> Connection: keep-alive
> Access-Control-Allow-Origin: *
> Auth-Token-Valid-Until: 2016-02-21T12:58:09.664Z
> Access-Control-Allow-Credentials: true
> Content-Length: 0
> X-Charles-Received-Continue: HTTP/1.1 100 Continue

According to this docs boundary can be quoted:

1) http://www.ietf.org/rfc/rfc2616.txt
Search for "permits the boundary string to be"

2) https://www.ietf.org/rfc/rfc2046.txt
Search for "and must instead be represented as"

More info:
http://developers.de/blogs/damir_dobric/archive/2013/09/10/problems-with-webapi-multipart-content-upload-and-boundary-quot-quotes.aspx

**Comment by mkjsix** [comment]
Hi,
I think you are right but this looks like to be an issue with how Undertow parses the multipart. I've seen similar problems around, as the .NET client implementation looks correct but some server-side implementations aren't fully compliant with rfc2046.
I need to investigate this further, but at the moment what we'll presumably do is to open an issue with the Undertow project.
Meanwhile, could you please tell me exactly which version of Restheart are you using?

**Comment by mkjsix** [comment]
@samfromlv I opened a request for clarification to Undertow at https://issues.jboss.org/browse/UNDERTOW-644

**Comment by mkjsix** [comment]
Rif. https://softinstigate.atlassian.net/browse/RH-178

**Comment by mkjsix** [comment]
The issue has been fixed in Undertow, but we need to wait their release so that we can build RESTHeart with the new dependency.

**Comment by samfromlv** [comment]
We are using RestHeart via Docker, image tag is 'latest' and according to logs it runs 1.1.6 version.

Workaround for .NET clients until fix is released:

http://stackoverflow.com/questions/21569770/wrong-content-type-header-generated-using-multipartformdatacontent/21583769

**Comment by mkjsix** [comment]
Undertow 1.3.19.Final has been released. The fix is already in the latest RESTHeart snapshots (1.1.8-SNAPSHOT and 2.0.0-beta-3-SNAPSHOT). We don't have yet a ETA for the stable versions, it should take a couple of weeks.
Please re-open this issue in case of further questions.

**Comment by ljjlpf** [comment]
```
var fun = function(){

}
```
