### ISSUE TITLE
RESTHeart results not matching what's in the database

### ISSUE THREAD

**Issue by matthewpalmer** [SoftInstigate/restheart#116]
Hi,

I'm seeing RESTHeart return different results from what's actually in the database, not totally sure why.

For example, if I do a GET for

```
http://charter.ws:8080/charter/emails?filter={_id:'CA+Y5xYdHMtCvVhenNzUKDKkYjMc4Eb2g8CNwiNUhCF9e1s_eyg@mail.gmail.com'}
```

I get no result,

```
{
  "_links": {
    "self": {
      "href": "/charter/emails?filter={_id:'CA+Y5xYdHMtCvVhenNzUKDKkYjMc4Eb2g8CNwiNUhCF9e1s_eyg@mail.gmail.com'}"
    },
    "curies": []
  },
  "_id": "emails",
  "_created_on": "2016-02-12T02:49:33Z",
  "_etag": {
    "$oid": "56bd483da07fe857fb4ce84b"
  },
  "_collection-props-cached": false,
  "_returned": 0
}
```

But if I make the equivalent query in the database, i.e.

```
db.emails.find({_id:'CA+Y5xYdHMtCvVhenNzUKDKkYjMc4Eb2g8CNwiNUhCF9e1s_eyg@mail.gmail.com'})
```

the correct email is found and returned.

I've tried with and without caching. Also, this only occurs for some of the documents in the database, but some of them work perfectly.

Any ideas for how I can get started debugging/fixing this? Have been loving RESTHeart so far and really want to keep using it.

Thought I might add the things I've tried

* starting/stopping the RESTHeart server
* disabling the cache
* power cycling the machine
* adding more RAM to the machine (it's running on DigitalOcean)

I haven't tried deleting and re-creating the database yet—leaving that as a last resort since the data in the database itself seems to be fine

**Comment by ujibang** [comment]
the problem in your request is the + sign.

+ sign in the query string is URL-decoded to a space. %2B in the query string is URL-decoded to a + sign.

You can have a look at this for more information http://stackoverflow.com/questions/6855624/plus-sign-in-query-string

**Comment by matthewpalmer** [comment]
Ah, that makes sense. Thanks so much and for getting back to me so quickly :+1:
