### ISSUE TITLE
No Access-Control-Allow-Methods for bulk operations

### ISSUE THREAD

**Issue by AngryLoki** [SoftInstigate/restheart#117]
Bulk operations are not possible with CORS. When I'm doing a PATCH request to `/db/col/*?filter=...`, chrome returns 
```
XMLHttpRequest cannot load http://localhost:8080/db/col/*?filter={%22data%22:{%22$exists%22:1}}. 
Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response.
```

However PATCHing specific items (e. g. /db/col/123) works well.

Tested with 2.0.0-beta-1.

**Comment by ujibang** [comment]
Hi @AngryLoki 

thanks for reporting this bug!

I created task [RH-181](https://softinstigate.atlassian.net/browse/RH-181) in project jira to fix it.

I'll let you know when it is fixed...

**Comment by ujibang** [comment]
fixed in master! please **try** it and **confirm**. 

you can download the latest 2.0.0-beta-2-SNAPSHOT from [sonatype.org](https://oss.sonatype.org/content/repositories/snapshots/org/restheart/restheart/2.0.0-beta-2-SNAPSHOT/restheart-2.0.0-beta-2-20160303.180600-12.zip)

**Comment by AngryLoki** [comment]
It works now, thanks!
