### ISSUE TITLE
Custom target field on Relationship

### ISSUE THREAD

**Issue by hemartins** [SoftInstigate/restheart#122]
Hi guys

First of all, congratulations for this great project. I've found it some weeks ago and I'm loving it!

I want to have a relationship to a target document using a custom target field to link. For example, a customer document with a relationship to his accounts:

Customer
`{
   "_id":{
      "$oid":"56963a0db9c56f2c478203c3"
   },
   "customerId":"c10da1336b06cc",
   "customerName":"New Customer",
   "accounts":[
      "9999999999",
      "1234567833",
      "000100010001"
   ]
}`

Account
`{
   "_id":{
      "$oid":"56deb5fbb9c56f5771f45b18"
   },
   "accountId":"9999999999",
   "accountName":"New Account",
   "otherInfo":[]
}`

How to link the customer to the account using the field accountId as target field?

Is possible to do something like this?

`{
   "rels":[
      {
         "rel":"accounts",
         "type":"ONE_TO_MANY",
         "role":"OWNING",
         "target-coll":"Accounts",
         "ref-field":"accounts",
         "target-field":"accountId"
      }
   ]
}`

Thanks
Regards
Henrique

**Comment by ujibang** [comment]
Hi @hemartins, 

currently there is no `target-field`, you need to store the **_id**s of the referenced document in the ref-field.

```
{ "_id":{ "$oid":"56963a0db9c56f2c478203c3" }, "customerId":"c10da1336b06cc", "customerName":"New Customer",
 "accounts":[{"$oid": "56deb5fbb9c56f5771f45b18"}, ... ] }
```

this makes sure that the referenced field has an unique index.

I'm going to add your suggestion in our backlog. We are currently working hard to close version 2.0, writing documentation and extending the integration test coverage. So cannot do it very quickly..going to be in 2.1......

if you are interested on contributing to the project with a pull request, I can point you to the code that deals with relationship

you might have already seen it, however find the documentation about relationship at https://softinstigate.atlassian.net/wiki/x/iYCM

thank you for you enthusiasm in the project.

**Comment by ujibang** [comment]
FYI 
I created the task in the backlog https://softinstigate.atlassian.net/browse/RH-184

**Comment by hemartins** [comment]
Hi @ujibang 

I'will fork the project and try to implement this improvement. I'will let you know as soon I have some results.

Thanks

**Comment by ujibang** [comment]
Hi @hemartins 

any news? we are going to close the issue and look forward for your PR
