### ISSUE TITLE
Is there any way to reload security.yml at runtime?

### ISSUE THREAD

**Issue by allisthere2love** [SoftInstigate/restheart#127]
Hi,
We're running some tests with Restheart and facing the following scenario:
We have some roles in security.yml, each one corresponding to one path (mongodb database).
If we want to add a new collection to this scenario, we need to modify the yml and then restart restheart.

Is it possible to reload it in runtime via some url? Or maybe put this feature in the backlog?

thanks!

**Comment by ujibang** [comment]
Hi @allisthere2love 

the feature "configuration reload at runtime" is already in the backlog. see https://softinstigate.atlassian.net/browse/RH-139

however we just release 2.0 and now priority is stability and refactoring, specifically this task https://softinstigate.atlassian.net/browse/RH-100 (Refactor code to use the new Mongodb driver 3.0 API)

so release time for this feature is not defined. if you need to speedup things you can either do yourself and contribute a pull request or buy a [custom development](http://restheart.org/support-packages.html) package from SoftInstigate.

thanks
