### ISSUE TITLE
access restriction at document level

### ISSUE THREAD

**Issue by mohankv** [SoftInstigate/restheart#128]
How to ensure access restriction at document level? I mean, a document must be accessed (GET requests) and modified (PATCH/POST requests) only by a user who created it using POST request.

**Comment by ujibang** [comment]
The default _SimpleFileIdentityManager_ does not allow to define permissions based on document properties: it only allows to match conditions on URLs.

So you should define a [custom Identity Manager](https://softinstigate.atlassian.net/wiki/x/HADM)

However there is a possible trick using bulk updates. You could do:

```
PATCH /db/coll/doc?filter={"_id": <docid>}&filter={'userid':< userid >}
```

and defining the following permission in security.yml:

```
# Users with role 'users' can bulk PATCH documents having userid property equals to their username
    - role: users
      predicate: regex[pattern="/db/coll/*\?.*filter={'userid':'(.*?)'}.*", value="%R", full-match=true] and equals[%u, "${1}"] and method[value="PATCH"]
```

the two filter query parameters are logically composed with the AND operator by RESTHeart. The first makes sure you only update the document with <docid> _id, the second enforces the document to have the userid property equals to the specified <userid>

the security permission enforces the <userid> parameter to be only accepted if equals to the authenticated user id.

**Comment by mohankv** [comment]
Thank you! That helps.
