### ISSUE TITLE
restheart

### ISSUE THREAD

**Issue by passionguy** [SoftInstigate/restheart#13]
![qq 20150116234119](https://cloud.githubusercontent.com/assets/2037747/5778862/4c5c0bb2-9dd9-11e4-850d-012f5726326e.jpg)

wooow!!! awesome product.
1、restheart may have a problem with chinese word.
2、how can i authority with db,except config in restheart-security.yml.

thanks

**Comment by mkjsix** [comment]
Hi, thank you!
1. I guess it's the demo blog front-end having issues more than Restheat itself, however I will setup a couple of tests with Chinese content, that would be a good idea anyway
2. Not sure about your question: do you want to setup some finer authentication in MongoDB compared to what you can do in restheart-security.yml file? Are you thinking about some missing functionality on this regard?

**Comment by mkjsix** [comment]
Hello,

Sorry for delay. I tried posting a JSON with some Chinese content and I have no issues visualizing it with the HAL browser or when I use curl, so my first hypothesis should be correct: it's an issue with the client, not the server. See my screenshot:

![schermata 2015-02-02 alle 12 24 07](https://cloud.githubusercontent.com/assets/365382/5999837/81d31dd0-aad6-11e4-9c9a-813c3de10e2c.png)
