### ISSUE TITLE
Small bug when non projecting the _id field

### ISSUE THREAD

**Issue by cenguix** [SoftInstigate/restheart#130]
When in any query we want to indicate that the _id field we do not want to appear in the json results as in for instance: keys=="{'_id':0,'title':1}"
Json result for a text search:
{
    "_embedded": {
        "rh:doc": [
            {
                "score": 1.5,
                "title": "Rendezvous with RAMA"
            },
            {
                "score": 1.5,
                "title": "Rama II"
            },
            {
                "score": 1.5,
                "title": "Rama Revealed"
            },
            {
                "score": 1.5,
                "title": "The Garden of Rama"
            }
        ]
    },
    "_id": "books2",
    "_returned": 0
}

The returned field displays incorrectly that 0 documents have been retrieved. When it should say 4. For the rest of cases when it is not indicated the non-projection of the _id field, it is correct the returned field.

**Comment by ujibang** [comment]
thanks for reporting

created bug https://softinstigate.atlassian.net/browse/RH-191

will be fixed in 2.0.1

**Comment by ujibang** [comment]
fixed.
