### ISSUE TITLE
How to get distinct values ( question )

### ISSUE THREAD

**Issue by mohamed-ouakil** [SoftInstigate/restheart#131]
Hi All,

i read the doc and cannot find how to achieve this

i have this on the collection :  
{
"type" : "A"
"value" : 111
}
{
"type" : "B"
"value" : 111
}
{
"type" : "A"
"value" : 222
}

i can do that on mongo shell : 
db.collection_test.distinct("type")

it return me : [ "A", "B"]

how to do the same on restheart ? 
i tried many /get/collection_test?filter parameter but it doesn't works

thanks for your reply

regards

**Comment by ujibang** [comment]
Hi

You have to create an aggregation. See how to do it in [documentation](https://softinstigate.atlassian.net/wiki/x/AwDw).

**Comment by mohamed-ouakil** [comment]
Hi ,

thanks  a lot :)
