### ISSUE TITLE
(web) hooks documentation

### ISSUE THREAD

**Issue by johnwiesel** [SoftInstigate/restheart#132]
According to https://softinstigate.atlassian.net/browse/RH-73 this feature is implemented and documentation is in progress. But I have trouble finding a good place to start using this feature (both in code or documentation).

Any help would be appreciated. Thank you!

**Comment by ujibang** [comment]
I just finished writing the [hooks](https://softinstigate.atlassian.net/wiki/x/EgAtAQ) documentation section.

@johnwiesel please review it and let me know if it provides all information to develop an hook.

feel free to reopen this issue eventually.
