### ISSUE TITLE
How to deny access to a specific collection?

### ISSUE THREAD

**Issue by roberterdin** [SoftInstigate/restheart#133]
I want to deny access to a specific collection.

My approach was to have this regex in the security.yml file : 
```
    - role: $unauthenticated
      predicate: regex[pattern="(?!/mydb/conversations/)^.*$", full-match=true]
```
This does not prevent access though. Any ideas?

**Comment by ujibang** [comment]
A permission _allows_ requests matching the condition.

So basically to prevent access you don't have to specify any permission for that role.

**Comment by roberterdin** [comment]
But given a database where there are a large amount of collections and I want to allow access to all collections but one. It's not very efficient to write hundreds of allow statements, I'd rather write one where I specify that access is allowed to **all but** the specified collection.

**Comment by ujibang** [comment]
Ah! Then you need a predicate that allows any request but to that collection.

Try

not path-prefix["/mydb/conversations"]

**Comment by roberterdin** [comment]
Ah, thanks a lot! I did not know there is a not operator.
