### ISSUE TITLE
How to fliter based on the embeded collection field?

### ISSUE THREAD

**Issue by sivateja890** [SoftInstigate/restheart#134]
I have collection like below

`{
    "_id" : ObjectId("573eb77bf3465096ddb1e873"),
    "id" : 1,
    "name" : "siva",
    "email" : "sivateja@gmail.com",
    "address" : [ 
        {
            "street" : "balajinager",
            "district" : "nellore",
            "state" : "A.p"
        }, 
        [ 
            {
                "street" : "balajinager",
                "district" : "nellore",
                "state" : "A.p"
            }
        ]
    ]
}`

i want to filter the records based on the city, which is inside the address array, how can we do that ?

**Comment by ujibang** [comment]
Try (ai haven't tested it)

GET /db/coll?filter={"address.city": "Rome"}

Also refer to mongodb documentation section https://docs.mongodb.com/manual/tutorial/query-documents/#match-a-field-without-specifying-array-index

**Comment by sivateja890** [comment]
I have done some trail and errors , below link workd for me

/db/col?filter={'address':+{$elemMatch:+{'state':'A.p'}}}&hal=f
