### ISSUE TITLE
Support for authentication w/o username & password?

### ISSUE THREAD

**Issue by jocII** [SoftInstigate/restheart#135]
I have an application that uses a token based security scheme using jwt tokens. Is there a mechanism to provide an alternate credential implementation that passes a token instead of username and password?

**Comment by ujibang** [comment]
Hello @jocII 

RESTHeart allows plugging of custom IDentity Managers. In summary, a custom IDM has to be implemented in java and setup in the configuration file.

Have a look at [Custom Identity Manager](https://softinstigate.atlassian.net/wiki/x/HADM) in the documentation.

However the IDM assumes that the credentials are passed using the Basic Authentication scheme, i.e. via the _Authentication_ request header; if you are fine with passing the jws token via this header, it should be easy implementing it (in case you can also rely on [paid support](http://restheart.org/support-packages.html)).

You can find an implementation of an IDM in the code: [DbIdentityManager.java](https://github.com/SoftInstigate/restheart/blob/master/src/main/java/org/restheart/security/impl/DbIdentityManager.java).

**Comment by jocII** [comment]
I dug into the code a bit further and can see where the authentication mechanisms are created within the SecurityHandler. It doesn't look like it would be that difficult to refactor this to allow other undertow AuthenticationMechanisms to be used. Do you think this is something that your project would add support for? I would think that other users might find this as useful as being able to add their own identity and access managers.

**Comment by ujibang** [comment]
Hi @jocII 

RESTHeart used the undertow [BasicAuthenticationMechanism](http://undertow.io/javadoc/1.3.x/io/undertow/security/impl/BasicAuthenticationMechanism.html). This make the credentials being passed via the _Authorization_ request header.

The actual authentication happens in the IDM that is already pluggable. As long as you can pass your token via this header, it shouldn't be a problem implementing a custom IDM that validates it.

Does this make sense for your use case?

**Comment by ujibang** [comment]
FYI we got a [PR](https://github.com/SoftInstigate/restheart/pull/137) from @mohankv that addresses this need.
