### ISSUE TITLE
How to define javascript code in aggregation pipelines operation, such as new Date()

### ISSUE THREAD

**Issue by weikunlu** [SoftInstigate/restheart#148]
I convert my timestamp field to date object through below method.
`{ "_$project": {"value":"1", "time":{ "_$dateToString": { "format": "%Y-%m-%d %H%M%S", "date": {"_$add": [new Date(0), "$timestamp"]}}}}},`

but restheart send me "message": "Invalid JSON"

is there any way to define script code for this case? 
just like passing variables to aggregation operations { "_$var" : "n" }, we could also define a {"_$javascript":"new Date(0)"}

**Comment by weikunlu** [comment]
I have tried several Bson apis but fail... It looks like I can't use JS function in java.

also find similar discuss here.
https://groups.google.com/forum/#!searchin/mongodb-user/date$20java%7Csort:relevance/mongodb-user/1ldJdhPY3M8/Vg-qZ9F1h_4J

**Comment by ujibang** [comment]
Tip: Use $currentDate mongo operator

**Comment by mkjsix** [comment]
I'm closing this right now, feel free to re-open if you have additional questions.
