### ISSUE TITLE
Bulk deletion of binary files using the filter query parameter

### ISSUE THREAD

**Issue by gremplewski-espirit** [SoftInstigate/restheart#149]
Hi,

is it possible to bulk delete multiple binary files using a wildcard and the filter query parameter?

I tried the following delete request:

`DELETE http://localhost:8080/project_1/assets_DE.files/*?filter={"uploadDate":{"$lt":{'$date':'2016-08-11T09:40:50.822Z'}}}`

But I get the following response:
```
{
  "_links": {
    "self": {
      "href": "/project_1/assets_DE.files/*"
    }
  },
  "http status code": 403,
  "http status description": "Forbidden",
  "message": "reserved resource"
}
```

Thanks in advance!
Tim

**Comment by mkjsix** [comment]
We wrote this part a long time ago and you can't delete a collection which ends with ".files" as it's actually a reserved resource. I guess the only way would be to delete binary files one by one, and I agree this is not the best solution, but we need to make room for improvements. @ujibang do you have an alternative solution?

**Comment by ujibang** [comment]
this is not supperted yet.

I've added it to our roadmap, see https://softinstigate.atlassian.net/browse/RH-205
