### ISSUE TITLE
ETag header values should be quoted

### ISSUE THREAD

**Issue by mirzov** [SoftInstigate/restheart#152]
Hi!
According to [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.19), the values of the ETag headers are supposed to be quoted strings. Please see also [this answer](http://stackoverflow.com/a/11572348/653730) on StackOverflow. Do you think you could consider complying and changing the RESTHeart responses in future releases?

**Comment by mkjsix** [comment]
Hello @mirzov 
It seems to me you are right. Accordingly to [RFC 7232](https://tools.ietf.org/html/rfc7232#section-2.3) (which supersedes RFC 2621) the ETag must be in quoted strings.

I created a JIRA issue to track progress on this: https://softinstigate.atlassian.net/browse/RH-207

However, I can't give you the ETA right now, we need to prioritize work internally.

**Comment by mirzov** [comment]
Hello @mkjsix,
Thank you for the prompt reaction! The issue is not critical as far as I am concerned (results in warnings by an HTTP-level library). Hope the change will not create problems for your existing user base.

**Comment by mkjsix** [comment]
Not sure about the impact, but we'd like to stay HTTP compliant as much as possibile. We'll publish the changes on master and then decide when to move to a stable release.

**Comment by mkjsix** [comment]
Hi @mirzov 
Unfortunately we have an impact already with our default integration tests, so we do expect regressions. This means we need to schedule this modification for a major release (3.0) as it could probably break clients using 2.x.

**Comment by mirzov** [comment]
Hi @mkjsix 
Thanks a lot for letting me know, appreciate your fast feedback!

**Comment by mkjsix** [comment]
After a deeper analysis this would really require a major refactoring, so we have decided to freeze this activity because we have higher priorities for the product.
Technical details are in https://softinstigate.atlassian.net/browse/RH-207
