### ISSUE TITLE
Adding new aggregation removes existing defined aggregations

### ISSUE THREAD

**Issue by vsreekar** [SoftInstigate/restheart#153]
Hi,

Whenever we try to make a PUT request to create a new aggregation, we observed that all existing aggregation definitions of that collection are being removed and only the latest one is preserved.

We tried with `$addToSet: { aggrs: <aggregation definition>}` as well.

Is there any suggested way to add a new aggregation definition without erasing the old ones?

**Comment by ujibang** [comment]
You need to use PATCH (using $addToSet) as PUT always replace the properties with the request body

**Comment by vsreekar** [comment]
Thank you for your time and quick reply @ujibang.
Looked like a trivial one after checking your reply.
