### ISSUE TITLE
Return a long in the response after a POST

### ISSUE THREAD

**Issue by Skyark112** [SoftInstigate/restheart#163]
Hey there,

So due to some political reasons within my project, we need to be able to return a serialize_id and pass that as part of the response object after performing a successful POST request.

Is there a way to easily modify the response object that gets returned back after a POST request?

For example a POST response would generate something like 
HTTP/1.1 201 Created
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, ETag, Auth-Token, Auth-Token-Valid-Until, Auth-Token-Location, X-Powered-By
Connection: keep-alive
Content-Length: 0
Date: Tue, 08 Mar 2016 13:26:06 GMT
ETag: 56ded2ee2d174c2a08cdee85
Location: http://127.0.0.1:8080/db/coll/56ded2eead66b2a1e741c054
X-Powered-By: restheart.org
 
I was wondering if it i's possible to add something like "Serialize_ID: xxxxxxxxxxxxxxx" to this response. 

I do realize that you give us the "etag" and the location of the document in mongo, but we can't use the ObjectIDs in our current system, we have to use a long type.

**Comment by ujibang** [comment]
Hi @Skyark112 

if you just need to have the _id of type long, then you can generate it client side and include in the request:

```
POST { "_id": 137, .... }
or
POST { "_id": {"$numberLong": 23423324 }, .... }
```

see [$numberLong](https://docs.mongodb.com/v3.2/reference/mongodb-extended-json/#numberlong)

will create documents with _id=137 or _id=23423324

If you rather want to transform the response and add some data (such as Serialize_ID) via a [representation transformer](https://softinstigate.atlassian.net/wiki/x/i4CM), this is not yet available for write requests, but it is planned for 3.0. see task [extend response transformers to write request](https://softinstigate.atlassian.net/browse/RH-213) in our backlog

**Comment by Skyark112** [comment]
@ujibang 

Thanks you for the response! I wanted to do something like your second suggestion, but in the end we managed to convince the other party to pass in their own long type id - like your first suggestion haha. 
I don't think we want to move to 3.0.0 yet, but once you have a stable release of that I hope to upgrade!

Sorry I have another unrelated question (not sure if I should open up another issue or not), but I can't seem to create a schema for document validation. Right now, I'm trying to run this command from the example:

http -a <user>:<pass> PUT <ip>:<port>/testdb/_schemas/testSchema {
"$schema": "http://json-schema.org/draft-04/schema#",
"type": "object",
"properties": {"address": {"type":"string"},
                      "city": {"type":"string"},
                      "postal-code": {"type":"string"},
                      "country": {"type":"string"}},
"required": ["address", "city", "postal-code"]
}

I'm getting http: error: argument REQUEST_ITEM: "[address," is not a valid value

When I leave out the "required" field, it gives me:  
{
    "_links": {
        "self": {
            "href": "/testdb/_schemas/documents"
        }
    },
    "http status code": 400,
    "http status description": "Bad Request",
    "message": "schema check failed"
}

Any idea what could be wrong here?

**Comment by ujibang** [comment]
please close this one and open a new issue. it will help others to find a solution for similar problems....
