### ISSUE TITLE
Failing to connect to Azure mongo-uri

### ISSUE THREAD

**Issue by platomaniac** [SoftInstigate/restheart#167]
I am failing to connect to a remote mogoDB service from Azure. Though using standard java driver I can connect via the same **mongo-uri**.

The azure mongo-uri is like this: `mongodb://username:passwd@host:10250/?ssl=true`

It will be great if anyone can shade some light on how to configure the `restheart.yml` to properly to connect the Azure mongoDB service instance.

To specify some more detail, I was testing from my local Windows machine. I changed the `restheart.yml` by adding my specific **mongo-uri** and ran `java -server -jar .\restheart.jar`. However when I go to `http://127.0.0.1:8080/browser/#/?hal=f ` I get the following error.
```
{
  "http status code": 500,
  "http status description": "Internal Server Error",
  "message": "Timeout connecting to MongoDB, is it running?"
}
```
I tried `https://127.0.0.1:4443/browser/#/?hal=f` but the same error appears.

**Comment by ujibang** [comment]
the error message you get ("Timeout connecting to MongoDB, is it running?") means that restheart is not able to communicate with the mongod server. Check the address, also using telnet:

```
$ telnet host 10250
```

**Comment by ujibang** [comment]
closing for now, feel free to reopen if you have more info

**Comment by iwoork** [comment]
I get the same issue. It happens because Azure probably doesn't understand the startup parameters.

On my local, I can run it successfully using:
```
docker run -d -p 80:8080 --name restheart -v "$PWD"/etc:/opt/restheart/etc:ro softinstigate/restheart:3.2.0
```

It fails to connect to DB when I only use
```
docker run -d -p 80:8080 --name restheart softinstigate/restheart:3.2.0
```
I would expect that Azure is not aware of the `-v "$PWD"/etc:/opt/restheart/etc:ro` flag

Any ideas to get around this?

**Comment by mkjsix** [comment]
On which Azure service are you running RESTHeart? Is that a plain Linux VM with Docker installed? Which version of docker? What operating system?
