### ISSUE TITLE
count semantic for empty collections is broken in latest 3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by mkjsix** [SoftInstigate/restheart#168]
When counting an empty collection the previous behavior was to receive an object as the response:
```
HTTP/1.1 200 OK
...
{
    "_embedded": {
        "rh:doc": [
            { <DOC30> }, { <DOC31> }, ... { <DOC39> }
        ]
    }
    "_returned": 0,
    "_size": 0
    "_total_pages": 1
}
```

Now I'm just receiving an empty array:

```
HTTP/1.1 200 OK
...

[]
```

This breaks the count semantic, as an empty collection should return a _size of 0, not an empty array

**Comment by ujibang** [comment]
fixed in 529a9f79f928209218dd5f8c0156eab316663653. can you verify?
