### ISSUE TITLE
[Question] How to submit PATCH request that only affects specified fields in nested sub document?

### ISSUE THREAD

**Issue by tomkerswill** [SoftInstigate/restheart#169]
Hi

I have a document which has a structure like this:

{
   "company": {
          "profile": {
                 "organisation": "Test organisation",
                 "name": "Test name 1"
           }
     }
}

I want to update just its name, using a PATCH request. Here's what I am sending:

{
     "company":{
         "profile":  {
            "name": "Test Patch Request 2"
        }   
  }
}

... This has the effect of overwriting "profile", so that the value of "organisation" is lost (because I'm sending a new profile object). How do I do the PATCH request so it only replaces exactly what I have specified? Eg. how can I do this so it only replaces the "name" in this case?

Thanks,

Tom

**Comment by mkjsix** [comment]
I suggest to give a look at this section in the documentation:

https://softinstigate.atlassian.net/wiki/display/RH/Write+Requests#WriteRequests-Dotnotation

**Comment by ujibang** [comment]
use the dot notation

```
PATCH /db/coll/id {"company.profile.name": "new value" }
```

**Comment by tomkerswill** [comment]
Okay - thanks!
