### ISSUE TITLE
Remove field in collection filter

### ISSUE THREAD

**Issue by jettdigital** [SoftInstigate/restheart#17]
Forgive my ignorance i'm new to Mongodb

It seems in the Mongo docs it's possible to remove fields from query results per 
http://docs.mongodb.org/manual/tutorial/project-fields-from-query-results/

However, it's done with a second argument to the function find() but if you take a look at line 177 is DocumentDao there's nothing in there for the second argument to find(). Am I missing something or does that mean it's impossible to exclude fields from a filter result?

(what I'm trying to do is get a shallow query of a Document without including its subdocument, maybe there's a different way to accomplish this query)

**Comment by ujibang** [comment]
Projection is not currently supported; however this is on our roadmap and planned for next version.

No release date is available, might say in about 1 month but no commitment on this.

Check improvement RH-67 https://softinstigate.atlassian.net/browse/RH-67

You can check our roadmap at https://softinstigate.atlassian.net/issues/?filter=10403

If you are in trouble with this, you might want to check http://restheart.org/support.html

**Comment by mkjsix** [comment]
Feature implemented: https://softinstigate.atlassian.net/browse/RH-67
