### ISSUE TITLE
Query, last (1-10) documents.

### ISSUE THREAD

**Issue by compyy** [SoftInstigate/restheart#170]
Hello,

I need help in query document, we have huge number of documents in this format.

{
            "Gateway": "Entrance", 
            "_etag": {
                "$oid": "58355081eb828602bc76b939"
            }, 
            "_id": {
                "$oid": "583550819650e5de42d36989"
            }, 
            "major": 30703, 
            "minor": 24375, 
            "time": "Wed Nov 23 2016 13:17:05 GMT+0500 (PKT)", 
            "timems": {
                "$numberLong": "1479889025332"
            }, 
            "uuid": "b9407f30f5f8466eaff925556b57fe6d"
 }

These Entries are written per second, sometimes multiple entries are written in 1 second.

in our Frontend we dont want to query full collection, we only want to GET only last 100 or last 200 documents, but can't find a way how to do it.

Is there any method where we query last 100 documents, save the last _id, and then in next query we mention the last _id and get all documents after that _id only ?

I hope i could clear what i want to do :)

**Comment by compyy** [comment]
I found a way to do it, but still have some questions.

http --auth admin:changeit GET 127.0.0.1:8080/school/gateway?filter="{'_id': { '\$gt': { '\$oid': '5836cde460d0372bd97a8c36' } }}"


Why do i have to mention \ before $, in examples it doesnt mention.

also is there any difference if i use "" or '' ?

**Comment by ujibang** [comment]
use **paging**. 

see https://softinstigate.atlassian.net/wiki/x/XACk#QueryDocuments-pagingPaging

**Comment by ujibang** [comment]
regarding your question about \,?,& and marks, this is the shell you are using, some chars are interpreted by the shell.

for instance in unix shell **$** is used for environment variables, **&** runs the command in background

so in most cases you need to quote the string, like in ?filter='{"a":1}' or escape chars link in \&

with httpie you can see the URL actually used via the -v options. you'll see how the shell interpreted your url with those chars...

**Comment by compyy** [comment]
Thanks, i found two working ways, both are good.

in first way, i can get the last written id, and then query all data written after this id after few intervals.

http --auth admin:changeit GET 127.0.0.1:8080/school/gateway?filter='{"_id": { "$gt": { "$oid": "5836cde460d0372bd97a8c36" } }}'


http --auth admin:changeit GET 127.0.0.1:8080/school/gateway?page=1\&pagesize=10
