### ISSUE TITLE
restheart2.0.2 : restheartd.conf is using some default config file and not mentioned restheart.yml file

### ISSUE THREAD

**Issue by genxlogics** [SoftInstigate/restheart#173]
hi @mkjsix 
i am using restheart2.0.0 on linux and running it as forked process. i configured the restheartd.conf to point to my restheart.yml file which includes

https-listener: false
https-host: 0.0.0.0
https-port: 444

http-listener: true
http-host: 0.0.0.0
http-port: 8081

now first thing is it's not picking my defined log file. its only logging in /tmp/restheart.log

when i see that file it shows as. if you notice its only taking the default configuration and not using my config file specified in restheartd.conf

so my security/ports/ or anything are not working as expected.

16:37:37.216 [main] INFO org.restheart.Bootstrapper - Starting RESTHeart instance default
16:37:37.216 [main] INFO org.restheart.Bootstrapper - version 2.0.2
16:37:37.218 [main] INFO org.restheart.Bootstrapper - Logging to file /tmp/restheart.log with level INFO
16:37:37.405 [main] INFO org.restheart.Bootstrapper - MongoDB connection pool initialized
16:37:37.405 [main] INFO org.restheart.Bootstrapper - MongoDB version 3.4.0
16:37:37.405 [main] WARN org.restheart.Bootstrapper - ***** No Identity Manager specified. Authentication disabled.
16:37:37.405 [main] WARN org.restheart.Bootstrapper - ***** No access manager specified. users can do anything.
16:37:37.405 [main] INFO org.restheart.Bootstrapper - Token based authentication enabled with token TTL 15 minutes

**16:37:37.583 [main] INFO org.restheart.Bootstrapper - HTTPS listener bound at 0.0.0.0:4443

16:37:37.583 [main] INFO org.restheart.Bootstrapper - HTTP listener bound at 0.0.0.0:8080**
16:37:37.584 [main] INFO org.restheart.Bootstrapper - Local cache for db and collection properties enabled with TTL 1000 msecs
16:37:37.584 [main] INFO org.restheart.Bootstrapper - Local cache for schema stores not enabled
16:37:37.789 [main] INFO org.restheart.Bootstrapper - URL / bound to MongoDB resource *
16:37:37.877 [main] INFO org.restheart.Bootstrapper - Embedded static resources browser extracted in /tmp/restheart-7235751717071695347
16:37:37.896 [main] INFO org.restheart.Bootstrapper - URL /browser bound to static resources /tmp/restheart-7235751717071695347. Access Manager: false
16:37:38.042 [main] INFO org.restheart.Bootstrapper - Pid file /var/run/restheart-0.pid
16:37:38.042 [main] INFO org.restheart.Bootstrapper - RESTHeart started

if you notice its taking the default configuration from somewhere. please help !!!

**Comment by Skyark112** [comment]
Hey, I've worked a bit on RestHEART myself and I hope I can help you. 

When you start the server are you specifying your .yml file?  For example:

'java -server /path/to/restheart.jar org.restheart.bootstrapper /path/to/your/restheart.yml'?

**Comment by genxlogics** [comment]
Thanks @Skyark112 
i was missing the .ymk file from command. its working fine !!
