### ISSUE TITLE
Release 3.0.0 is available

### ISSUE THREAD

**Issue by mkjsix** [SoftInstigate/restheart#174]
We've released **RESTHeart 3.0.0**. You can download it [here](https://github.com/SoftInstigate/restheart/releases/latest) or you can run the [Docker image](https://hub.docker.com/r/softinstigate/restheart/).
The documentation is on [Confluence](https://softinstigate.atlassian.net/wiki/x/G4AH).

This is a major release supporting a more compact and easier to use JSON representation format. HAL is of course still totally supported, but we have gone a more pragmatic route when complete HATEOAS is not strictly necessary. However the compact and HAL representations can be switched dynamically, just via a simple query-string. There are many additional code refactorings to use the new MongoDB java driver 3.x, improved transformers and many minor improvements and bug fixes.

Please let us know any issue or post any question here.

**Comment by wblaircox** [comment]
Took so much time to get things working in very 2,  looks like it will take just as long to redo it the "simple" way. Can you point me to where I can make this version function like ver 2 in terms of the URL filters and formatting please?

**Comment by ujibang** [comment]
Hi @wblaircox 

I answered your question [here](https://github.com/SoftInstigate/restheart/issues/179)
