### ISSUE TITLE
Security between RestHEART and Mongodb

### ISSUE THREAD

**Issue by Skyark112** [SoftInstigate/restheart#176]
Hey guys,

I know that you have the custom identity managers and custom access managers and I've been playing around with that. I was just wondering if you guys implemented the ability to authenticate using 509 certs instead of user password. 

If not, would that be something that I would have to write in my own identity manager?

Thanks for all of your help!

**Comment by ujibang** [comment]
Hi @Skyark112 

do you mean using certs to connect to mongodb (as the issue title suggests) or to use certs to authenticate the clients of restheart?

the former is possible (see [here](https://softinstigate.atlassian.net/wiki/x/FICM#InstallationandSetup-7.1ConnectRESTHearttoMongoDBoverTLS/SSL)); the latter requires modifying restheart code.

A custom IDM assumes the basic authentication scheme anyway (credential passed via Authenticate request method). The good news is that [undertow](https://github.com/undertow-io/undertow) (RESTHeart is built on it) has a the [ClientCertAuthenticationMechanism](https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/security/impl/ClientCertAuthenticationMechanism.java)

Adding a different authentication mechanism other that basic authentication is not in our backlog (of course you can always request commercial support from [softinstigate](http://restheart.org/support-packages.html), the company behind restheart).

If you make the authentication mechanism configurable in some ways, please considering contributing via pull request.

**Comment by Skyark112** [comment]
Thanks so much! I can't believe I missed that lol.
