### ISSUE TITLE
Handling "/" in collection name

### ISSUE THREAD

**Issue by forsen** [SoftInstigate/restheart#177]
RESTHeart does not support "/" in collection names. 

From mongo shell: 
`> use test`
`> db.createCollection("my/test")`
`> db['my/test'].insert({some data:"test"})`

Now try [http://localhost:8080/test/my/test](http://localhost:8080/test/my/test)

Result is 404. 

According to [MongoDB Reference](https://docs.mongodb.com/manual/reference/limits/#Restriction-on-Collection-Names), using "/" in collection name is acceptable. 

Tested with RESTHeart 3.0.0 and MongoDB 3.2

**Comment by ujibang** [comment]
closing this since we found no way of distinguish / in a URL as part of a collection name
