### ISSUE TITLE
3.x Filters different?

### ISSUE THREAD

**Issue by wblaircox** [SoftInstigate/restheart#179]
What has changed in terms of the filters with this new 3.x version? As soon as I loaded it, my queries stopped working as expected. As in, they don't work, lol

**Comment by wblaircox** [comment]
Can someone point me in the direction to download version 2 again? Have to revert until I can get everything working with version 3.

**Comment by ujibang** [comment]
Hi @wblaircox 

`filter` format hasn't changed in restheart 3.0. I suspect you have an issue with the new default resource representation format called PLAIN_JSON

You can get HAL format back either setting the default format in the configuration file (see below) or via the `rep=[HAL|PJ]` query parameter.

```
#### default representation format (PLAIN_JSON or HAL)
default-representation-format: HAL
```

in any case you can download version 2 from the [release page](https://github.com/SoftInstigate/restheart/releases)

let us know if this fixes your issue; in case it doesn't please provide more info about the error you get

**Comment by wblaircox** [comment]
ah, much better!! Thanks @ujibang Fantastic tool by the way, do you take donations?

**Comment by mkjsix** [comment]
Thank you @wblaircox, actually we haven't thought about taking donations, I guess we could put some button on the website but we haven't selected any provider so far. If you have suggestions we'll have a look :)
