### ISSUE TITLE
How to get the count of documents in collection?

### ISSUE THREAD

**Issue by chunlunglin** [SoftInstigate/restheart#18]
I go through the API but still don't know how to get the count of all documents in the specific collection?
Is it possible just return the total count to caller? Thanks,

**Comment by ujibang** [comment]
indeed it is possible!

if **count** parameter is in the query string, response includes the **_size** and **_total_pages** properties (size is the total number of documents in the collection, if no filter has been specified).

so **GET /db/coll?count will do the trick**

the collection response include the URI template rh:countandpaging, that includes it:
```
"rh:countandpaging": {
            "href": "/api/materials/{?page}{&pagesize}&count", 
            "templated": true
        }
```
also you find it documented in the doc section API->collection->query parameters, have a look at
http://restheart.org/docs/api.html#api-coll

**Comment by smpadhy** [comment]
Hi, We have a large collection with approximately 2.5 billion documents.  I am using _size for the number of documents in a collection. It is giving "java.lang.ArithmeticException: integer overflow
	at java.base/java.lang.Math.toIntExact(Math.java:1071)".  We found out that Java Max Int is 2147483647 which is less than 2.5 billion. That might be the reason of integer overflow. For smaller collection, _size is returning fine.
Do you know of a workaround?
Thanks.

**Comment by mkjsix** [comment]
@smpadhy please open a new issue with all the requested information, without even knowing which version of RESTHeart you are running we can't help.

**Comment by smpadhy** [comment]
Thanks.
