### ISSUE TITLE
Arbitrary request filtering

### ISSUE THREAD

**Issue by hannespernpeintner** [SoftInstigate/restheart#180]
Hey guys :)

Using Identity- and AccessManager for security purposes works very well. Now we would like to have (simple) arbitrary filtering for our application. More precisely: We would like to intercept all requests and generate metrics for all usages. Is there a way to use request filters with restheart?

The only workaround we see currently, is to implement the filter logic in our AccessManager. But it wouldn't be the right place for the logic.

Thanks :)

**Comment by ujibang** [comment]
Hi @hannespernpeintner 

I'm not sure I get what you mean by "request filter"...

...however a way to intercept requests (and collect metrics) would be implementing an [hook](https://softinstigate.atlassian.net/wiki/x/EgAtAQ).

**Comment by hannespernpeintner** [comment]
Ah, seems to be exactly what I wanted. Mea culpa, I overlooked it :( Thanks!
