### ISSUE TITLE
One bad RequestHook disables them all

### ISSUE THREAD

**Issue by visualist** [SoftInstigate/restheart#182]
If you have one working RequestHook, like this in your config file:
<pre>
    - group: hooks
      interface: org.restheart.hal.metadata.singletons.Hook
      singletons:
        - name: snooper
          class: org.restheart.hal.metadata.singletons.SnooperHook
</pre>
and say it works fine. But when a second hook is added that is not a loadable class, then the previously working hook stops working. Example:
<pre>
        - name: dnx
          class: org.organization.DoesNotExist
</pre>

I should think only 'snooper' should continue to work in this case, just 'dnx' should fail.
(This issue is more of an edge case & low priority for me, but wanted to report it just the same.)

**Comment by mkjsix** [comment]
I think it could be fixed with a different exception handling strategy when loading hooks, we should have a look at the code within RESTHeart. BTW, did you see the problem at startup time or at runtime?

**Comment by visualist** [comment]
It was at runtime when the working hook stopped working. Adjusting the exception handling makes sense.

**Comment by visualist** [comment]
11:18:30.649 [XNIO-1 task-1] DEBUG o.r.h.m.s.NamedSingletonsFactory - added singleton snooper of class org.restheart.hal.metadata.singletons.SnooperHook to group hooks

**Comment by visualist** [comment]
oops, didn't mean to close the issue

**Comment by ujibang** [comment]
Hi, news about this. Last commit should fix this issue. 

Feel free to reopen. Thanks
