### ISSUE TITLE
SSL Connection with Mongo in v2.0.3.1

### ISSUE THREAD

**Issue by Skyark112** [SoftInstigate/restheart#187]
Hey guys,

Just wanted to ask if I could still do the ssl=True in the mongoURI and add in the java options during startup in version 2.0.3.1. For time related reasons we are not updating to 3.0.0 until later in our cycle. 

Instinct says that this should work fine because I don't think any of it has to do with restheart itself, but just wanted to make sure.

Thanks as always!

**Comment by ujibang** [comment]
yep it works. you can specify the mongoURI with all the options supported by the java driver

**Comment by Skyark112** [comment]
Thanks!

**Comment by ujibang** [comment]
to know how to configure restheart to use SSL have a look in the [documentation](https://softinstigate.atlassian.net/wiki/x/FICM#InstallationandSetup-7.1ConnectRESTHearttoMongoDBoverTLS/SSL)
