### ISSUE TITLE
Issue with checking Schema with Application Logic Handler

### ISSUE THREAD

**Issue by Skyark112** [SoftInstigate/restheart#188]
Hey guys,

The custom logic handler I have going to one of our collections is not recognizing the schema that's associated with that collection. 
I'm not too sure of the reason - maybe because RequestDispacherHandler isn't being added into the chain?

I had some custom code checking the JSON passed in for our custom logic handler so this isn't a huge issue, but I wanted to confirm if this is intended or not.

Thanks for the great application as always!

**Comment by ujibang** [comment]
to check schema you should use a [Checker](https://softinstigate.atlassian.net/wiki/x/jYCM). You can also use the ready to use JsonSchemaChecker!

[Application Logic](https://softinstigate.atlassian.net/wiki/x/IoCw) Hanlders are not part of the collection request chain, intended just to provide some custom logic...

**Comment by Skyark112** [comment]
Thanks, I got it working
