### ISSUE TITLE
Does RESTHeart support Patch calls?

### ISSUE THREAD

**Issue by rbarcelos** [SoftInstigate/restheart#19]
Not sure if here is the right place to ask this..
I am calling $http passing the following payload and I am seeing the data added as it is isntead of the result of the execution,

{                    "op": "add",                    "path": "/",                   "value": "wt_metadata"           }

**Comment by mkjsix** [comment]
Hi,
Could you please provide us with some context and explain in more details what are you trying to do?

**Comment by ujibang** [comment]
yes RH supports PATCH. 

you don't need to specify "op":"add" property,  just PATCH with properties you want to add or modify.

PATCH verb already has already the "add if missing" semantic.

Maybe you want something like the mongodb array operators? In this case, it is in our roadmap for next major release.

More info at https://softinstigate.atlassian.net/browse/RH-19

**Comment by rbarcelos** [comment]
Thanks for the reply..

Using PATH with the properties, I am able to add new properties, but it
fails with CONFLICT when I try to modify them.. See attached images:.

What should be request payload when updating the property?



--
Rafael Ferreira Barcelos
M.Sc. in Software Engineering at COPPE/UFRJ
Software Development Engineer at Microsoft
-- 

On Thu, Mar 19, 2015 at 10:48 AM, Andrea Di Cesare <notifications@github.com

**Comment by ujibang** [comment]
Conflict is due to the etag.

When modifying an existing resource, you need to pass the etag value in the If-Match request header.

Just for reference http://en.m.wikipedia.org/wiki/HTTP_ETag

**Comment by mkjsix** [comment]
Some additional information: we are handling the [Optimistic concurrency control](http://en.wikipedia.org/wiki/Optimistic_concurrency_control) problem, you can have a look at the following external blog post for a nice description of the mechanics, the reasoning is more or less the same: http://fideloper.com/etags-and-optimistic-concurrency-control

**Comment by rbarcelos** [comment]
Thanks a lot. After I call pacth, do I need to do and extra get only to get
the new etag? I am getting error 412 - precondition failed when trying to
call several patchs in a arrow..

--
Rafael Ferreira Barcelos
M.Sc. in Software Engineering at COPPE/UFRJ
Software Development Engineer at Microsoft
--

**Comment by ujibang** [comment]
Etag changes on every update.

Conflict = no Etag was specified
Precondition failed = specified Etag does not match

**Comment by mkjsix** [comment]
At present, if you want to perform a sequence of PATCHes over a document you'll have to issue a GET after each PATCH. I'm going to open an enhancement in our JIRA, it is nicer if we could put the new Etag in the response header after a PATCH, so you can just read the HTTP headers without any additional GET. We can't commit to an ETA at the moment.

**Comment by mkjsix** [comment]
Added an enhancement in JIRA: https://softinstigate.atlassian.net/browse/RH-80

**Comment by mkjsix** [comment]
Hi Rafael,
The enhancement described in https://softinstigate.atlassian.net/browse/RH-80 is now in the latest development snapshot (0.10.1-SNAPSHOT on branch 'develop'). You'll have to build RESTHeart by yourself or wait for the stable 0.10.1 release, which is tentatively planned for this weekend.
