### ISSUE TITLE
update document throw 406 error

### ISSUE THREAD

**Issue by kevin8023** [SoftInstigate/restheart#194]
when i use below url to update document, it will throw 406 error

[root@localhost schema]# http patch http://a:a@*.*.*.*:8080/mdm/Organization/58c641ce962086519e2a82ad?id_type=STRING_OID < Organization_update.json

Organization_update.json
{
            "_id":"58c641ce962086519e2a82ad",
           "OrganizationName": "test for update"
}

Result :

HTTP/1.1 406 Not Acceptable
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, ETag, Auth-Token, Auth-Token-Valid-Until, Auth-Token-Location, X-Powered-By
Auth-Token: 30f5797d-c056-4529-95fa-5ccbdccf5138
Auth-Token-Location: /_authtokens/a
Auth-Token-Valid-Until: 2017-03-13T07:39:00.430Z
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 126
Content-Type: application/json
Date: Mon, 13 Mar 2017 07:24:00 GMT
X-Powered-By: restheart.org

{
    "http status code": 406,
    "http status description": "Not Acceptable",
    "message": "_id in json data cannot be different than id in URL"
}

could you help to fix this ? 
Thank you a lot!

**Comment by ujibang** [comment]
Try with ?id_type=STRING

STRING_OID will take the id in the url as an Objectid (since its valid ObjectId value), thus it will conflict with the sting _id in the document.

You can also omit the _id in the body.

**Comment by kevin8023** [comment]
Hi ujibang:
  Thanks for you suggestion! but i also cannot update this document.
  Now i tried to update below url and omit the _id in json body, and it will throw 400 bad request.i'm so confused. could you help to advise best way to update?

http patch http://a:a@15.19.249.25:8080/mdm/Organization/58c641ce962086519e2a82ad < Organization_update.json

Organization_update.json

{
"OrganizationName": "test for update"
}

Result:

HTTP/1.1 400 Bad Request
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, ETag, Auth-Token, Auth-Token-Valid-Until, Auth-Token-Location, X-Powered-By
Auth-Token: 4df7fb6d-07cb-452f-b003-e4e7d66dae5d
Auth-Token-Location: /_authtokens/a
Auth-Token-Valid-Until: 2017-03-13T08:23:01.550Z
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 167
Content-Type: application/json
Date: Mon, 13 Mar 2017 08:08:01 GMT
X-Powered-By: restheart.org

{
    "_warnings": [
        "#: 2 schema violations found",
        "#: extraneous key [_id] is not permitted",
        "#: extraneous key [_etag] is not permitted"
    ],
    "http status code": 400,
    "http status description": "Bad Request",
    "message": "request check failed"
}



Thank you a lot.

**Comment by ujibang** [comment]
Now the PATCH request failed because of json schema validation.

In your schema you need to define the properties _id and _etag (this is injected by restheart, see [etag](https://softinstigate.atlassian.net/wiki/x/hICM))

Update your schema to include them, try something like this:

```
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"_id": {
			"type": "string"
		},
		"OrganizationName": {
			"type": "string"
		},
		"_etag": {
			"type": "object",
			"properties": {
				"_$oid": {
					"type": "string"
				}
			},
			"additionalProperties": false,
			"required": [
				"_$oid"
			]
		}
	},
	"additionalProperties": false,
	"required": [
		"_id",
		"OrganizationName"
	]
}
```

**Comment by kevin8023** [comment]
Hi ujibnag:
 Thank you a lot. I already fixed this issues.
