### ISSUE TITLE
Unicode & file upload in restheart 3.0.1

### ISSUE THREAD

**Issue by khanhdhv** [SoftInstigate/restheart#198]
Hi!

I've found some troubles when using restheart 3.0.0 and 3.0.1.
1. Unicode characters are not displayed correctly in restheart 3.0.1.

![unicode](https://cloud.githubusercontent.com/assets/26496583/24072823/97dc5720-0c1f-11e7-86ff-8322183568c0.PNG)

2. File upload problem in both 3.0.0 and 3.0.1:
   - 'filename' field always be 'file'.
   - 'contentType' field always be null.
I've tried to use curl with properties but have no change.

![fileupload](https://cloud.githubusercontent.com/assets/26496583/24072824/97dc827c-0c1f-11e7-95a6-683c119a1a96.PNG)

Are these bugs or i have to change something in configuration file?

Thanks!

**Comment by ujibang** [comment]
Hi @khanhdhv 

as you can see, the contentType is actually in metedata.contentType. at the time we wrote that feature the mongodb java driver did not allow to give the file contentType a value so we put it there. I'll check if the new version allows it.

the filename `file` is just the default value given when no filename property is specified. to pass it do as follows (I'm using httpie here):

```
http -f PUT 127.0.0.1:8080/testdb/mybucket.files/mypicture.png file@"~/Desktop/mypicture.png" properties='{"filename":"mypicture.png"}'
```

as you can see the _properties_ part is a json object with _filename_ property

**Comment by ujibang** [comment]
added bug to our backlog, see https://softinstigate.atlassian.net/browse/RH-241

**Comment by khanhdhv** [comment]
Thank you!

I have found the way to post file to the bucket.
But there is a small problem when the file name have unicode characters. :D

![filename](https://cloud.githubusercontent.com/assets/26496583/24244348/02aca2b0-0ff1-11e7-9a32-f55042b73753.PNG)

**Comment by ujibang** [comment]
thanks

took note in the jira bug. we will fix it...

**Comment by ujibang** [comment]
Please check this issue https://github.com/SoftInstigate/restheart/issues/206 

It shows you how  to fix the encoding problem you experienced

**Comment by ujibang** [comment]
closing for now, feel free to reopen if #206 doesn't work for you
