### ISSUE TITLE
_etag not being returned for all docs in a collection

### ISSUE THREAD

**Issue by rbarcelos** [SoftInstigate/restheart#20]
Hi,

I am using RestHeart to load all docs in a given collection from MongoDb.
_etag is being returned randomly only for few docs ..

![capture](https://cloud.githubusercontent.com/assets/1468598/6793832/9290582c-d187-11e4-8b06-c4bda83bfcf2.PNG)

You can try it out using the following url also:

http://104.236.128.68:8080/WallTrade/fb_group

**Comment by ujibang** [comment]
Just to confirm: has the document 11 in your screenshot been created by RESTHeart or by a different client?

In fact, the _etag property is injected by RESTHeart at write time.

If a document has been created by a different client (e.g. mongo shell) the _etag won't be there. In this case RESTHeart won't enforce the etag match. At first update by RETHeart, the _etag will be automatically added.

**Comment by rbarcelos** [comment]
Gotcha..
You are right.. the ones missing got created by a different client..
could you make this clear on the documentation ?..

Thanks

--
Rafael Ferreira Barcelos
M.Sc. in Software Engineering at COPPE/UFRJ
Software Development Engineer at Microsoft
--

**Comment by ujibang** [comment]
yes indeed. the docs will have a section full dedicated to the ETag

work in progress!  http://restheart.org/docs/etag.html
