### ISSUE TITLE
Tailable Cursor Support and Client Side Wrapper

### ISSUE THREAD

**Issue by nxidplease** [SoftInstigate/restheart#201]
Any existing support for tailing the oplog and getting live changes through websockets or something along these lines? 

Is there any clientside library that wraps the api like pouchDb does for couchDb?

**Comment by mkjsix** [comment]
The closest thing I can think of are Request Hooks:

https://softinstigate.atlassian.net/wiki/x/EgAtAQ

> Request Hooks allow to execute custom code after a request completes.

I can't help with your second question as I've never heard of pouchDb, sorry.
