### ISSUE TITLE
New group transformers added in 3.0.x

### ISSUE THREAD

**Issue by grossmueller-espirit** [SoftInstigate/restheart#204]
Hi, 

I have noticed that two additional group transformers have been added to the RH3 default restheart.yml.
What is the purpose of "writeResult" and "hashProperties"?
Should I add them to my restheart.yml when migrating from 2.0.2 to 3.0.x?

Thanks,
Tanja

**Comment by ujibang** [comment]
hi @grossmueller-espirit 

from HashTransformer javadoc

> This transformer hashes the properties from the resource representation on write requests using the bcrypt hash function the properties to hash out are passed in the args argument as an array of strings. the bcrypt

example that hashes the property 'password' from the response:
```
{ rts: [{ "name": "hashProperties", 
             "phase":"REQUEST", 
             "scope":"CHILDREN",
             "args": { "props": ["password"], "complexity": 12 }}
         ]
}
```

**writeResult** is just an example that shows how to send a response body in a write request. it sends back a body as follows:

```
{  
   "oldData":  { ... }
   "newData" : { ... }
}
```

**Comment by grossmueller-espirit** [comment]
Hi @ujibang 

thanks a lot for the information!
