### ISSUE TITLE
ResponseHelper.endExchangeWithMessage changed behaviour in 3.0.x

### ISSUE THREAD

**Issue by grossmueller-espirit** [SoftInstigate/restheart#205]
Hi,

we created a very simple custom application logic handler that is supposed to return a little piece of information. All is working well in rh 2.0.2.
This is the code we used:
```java
@Override
public void handleRequest(HttpServerExchange httpServerExchange, RequestContext requestContext) throws Exception {
    if (requestContext.getMethod() == RequestContext.METHOD.GET) {
       ResponseHelper.endExchangeWithMessage(httpServerExchange, HttpStatus.SC_OK, "myinformation");
    } else {
        ...
    }
}
``` 
In the response, our information was present  in the "message" property:
```javascript
{
  "_links": {
    "self": {
      "href": "/_logic/littlesecret"
    }
  },
  "http status code": 200,
  "http status description": "OK",
  "message": "myinformation"
}
```

For 3.0.x we needed to adapt the code slightly because the signature of "endExchangeWithMessage" changed:
```java
ResponseHelper.endExchangeWithMessage(httpServerExchange, requestContext, HttpStatus.SC_OK, "myinformation");

``` 
**Problem**: now the response body is empty! 

I managed to solve the problem by using some code of ResponseHelper version 2.0.2 in my handler. (In short: httpServerExchange.getResponseSender().send(myRep.toString());).

Even though the solutation seems to work I was wondering if you could give us some background on what is happening here, i.e. why "endExchangeWithMessage" no longer does what it used to do in 2.0.2.

Thanks a million,
Tanja

**Comment by ujibang** [comment]
Hi @grossmueller-espirit 

in 3.0 `ResponseHelper.endExchangeWithMessage()` does not actually send the response, instead it just sets the response in the context via `context.setResponseContent()`

ResponseSenderHandler it then send the response set in the context.

So you can just instantiate ResponseSenderHandler in your handler constructor and call its `handleRequest()` method at the end.

```
public YourHandler(PipedHttpHandler next, Map<String, Object> args) {
        super(new ResponseSenderHandler(null), args);
    }

public void handleRequest(
            HttpServerExchange exchange,
            RequestContext context)
            throws Exception {
            ......
            // set the response content
            ResponseHelper.endExchangeWithMessage(...);
            ......
            // call ResponseSenderHandler
            getNext().handleRequest(exchange, context);
}
```

**Comment by grossmueller-espirit** [comment]
Hi @ujibang 

thanks a lot for explaining how to use it. Great!
