### ISSUE TITLE
How to get original request  document data

### ISSUE THREAD

**Issue by kevin8023** [SoftInstigate/restheart#208]
Hi,
  currently we use below method to get document data in custom hook,but we find it is not original document data, 
  please check below concerns.
   METHOD:           BsonValue _content = rc.getContent();
		             BsonDocument content = _content.asDocument();
 
RESULT:             {"OrganizationName":{"dateTime":false,"symbol":false,"javaScriptWithScope":false,"string":true,"regularExpression":false,"javaScript":false,"double":false,"document":false,"DBPointer":false,"number":false,"boolean":false,"null":false,"bsonType":{"container":false,"value":2},"int32":false,"array":false,"int64":false,"binary":false,"value":"test","decimal128":false,"objectId":false,"timestamp":false},"_etag":{"dateTime":false,"symbol":false,"javaScriptWithScope":false,"string":false,"regularExpression":false,"javaScript":false,"double":false,"document":false,"DBPointer":false,"number":false,"boolean":false,"null":false,"bsonType":{"container":false,"value":7},"int32":false,"array":false,"int64":false,"binary":false,"value":{"date":"Sat Apr 08 03:37:27 EDT 2017","currentCounter":-770095373,"generatedMachineIdentifier":14654826,"machineIdentifier":14654826,"generatedProcessIdentifier":22561,"time":1491637047000,"processIdentifier":22561,"counter":1656561,"timestamp":1491637047,"timeSecond":1491637047},"decimal128":false,"objectId":true,"timestamp":false}}

   could you help to get original request document data as below in custom hook? 
  {
    "OrganizationName": "test"
  }

**Comment by ujibang** [comment]
Hi @kevin8023 

I checked the hooks and found an issue introduced by a recent refactoring. opened this bug https://softinstigate.atlassian.net/browse/RH-243 

I fixed it, can you please try with the 3.0.3-SNAPSHOT build that you can find in [sonatype](https://oss.sonatype.org/content/repositories/snapshots/org/restheart/restheart/3.0.3-SNAPSHOT/restheart-3.0.3-20170410.125305-3.tar.gz) repo?

**Comment by ujibang** [comment]
It should be fixed, I'm closing this one. Feel free to reopen if you need further help.
