### ISSUE TITLE
RESTHeart does not run on IBM SDK

### ISSUE THREAD

**Issue by slankas** [SoftInstigate/restheart#21]
Using IBM's SDK 8 on a power-pc 64 bit server, I receive the following error trying to start RESTHeart:
>14:54:48.006 [main] ERROR org.restheart.Bootstrapper - couldn't start RESTHeart, error with specified keystore. exiting..
>java.security.NoSuchAlgorithmException: SunX509 KeyManagerFactory not available
>        at sun.security.jca.GetInstance.getInstance(GetInstance.java:171) ~[na:1.8.0]
>        at javax.net.ssl.KeyManagerFactory.getInstance(KeyManagerFactory.java:20) ~[na:8.0 build_20140901]
>        at org.restheart.Bootstrapper.startCoreSystem(Bootstrapper.java:482) [restheart.jar:0.10.0]
>        at org.restheart.Bootstrapper.startServer(Bootstrapper.java:332) [restheart.jar:0.10.0]
>        at org.restheart.Bootstrapper.main(Bootstrapper.java:214) [restheart.jar:0.10.0]
> 14:54:48.007 [main] INFO  org.restheart.Bootstrapper - stopping RESTHeart

I was able to fix this by extracting out the jar file, grabbing the Master version of org.restheart.BootStrapper.java and replacing the two instances (lines 482 and 491) of 
> kmf = KeyManagerFactory.getInstance("SunX509");
with
> kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());

My fix was adopted from http://stackoverflow.com/questions/18609106/paypal-nvp-how-use-sunx509-on-ibm-jre

**Comment by ujibang** [comment]
fixed as you suggested in development branch

many thanks
