### ISSUE TITLE
com.mongodb.MongoTimeoutException

### ISSUE THREAD

**Issue by huangyanxiong01** [SoftInstigate/restheart#214]
#  reproduce
```
docker run -itd --name mongo -v /home/ubuntu/mongodb/:/data/db  -p 27017:27017 mongo
docker run --rm -i -t -d -p 8080:8080 --name restheart -v /home/ubuntu/restheart/restheart.yml:/opt/restheart/etc/restheart.yml  --link mongo softinstigate/restheart
```

Now open http:/.locahost:8080/ in browser

# Result
```json
{
    "_exceptions": [
        {
            "exception": "com.mongodb.MongoTimeoutException",
            "exception message": "Timed out after 30000 ms while waiting for a server that matches ReadPreferenceServerSelector{readPreference=primary}. Client view of cluster state is {type=UNKNOWN, servers=[{address=mongodb:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketException: mongodb}, caused by {java.net.UnknownHostException: mongodb}}]"
        }
    ],
    "http status code": 500,
    "http status description": "Internal Server Error",
    "message": "Timeout connecting to MongoDB, is it running?"
}
```

**Comment by ujibang** [comment]
you named your mongo container `mongo` and `--link mongodb`

shouldn't it be `--link mongo`?

**Comment by huangyanxiong01** [comment]
@ujibang I think I copied the wrong command line. if  mongo container not found, the docker will show warning 
```
docker: Error response from daemon: Could not get container for mongo.
```
Now,the command line has been fixed, you can according to command line reproduce

**Comment by ujibang** [comment]
Try with name and --link mongodb 

I think the address specifie in conf file is mongodb

**Comment by mkjsix** [comment]
@huangyanxiong01 did you follow the documentation at https://hub.docker.com/r/softinstigate/restheart/ ?

**Comment by huangyanxiong01** [comment]
@mkjsix I konw you recommend to pull  mongo:3.2 restheart 3.0.3. but I would like to use the new features of mongodb 3.4.4

**Comment by mkjsix** [comment]
@huangyanxiong01 with RESTHeart 3.x you can safely pull Mongodb 3.4, we use it extensively in our tests.

**Comment by huangyanxiong01** [comment]
@ujibang thank you, the mongodb container only name "mongodb", if container name "mongo" , the restheart will connect mongodb timeout.I don't think the address specifie in conf file is mongodb, it possible
 "mongodb" name in code

**Comment by mkjsix** [comment]
@huangyanxiong01 if you are pulling the official softinstigate/restheart docker image then the default configuration is taken from https://github.com/SoftInstigate/restheart/tree/master/Docker/etc
so `mongo-uri: mongodb://mongodb`

**Comment by huangyanxiong01** [comment]
@ujibang Yes,thank you,I already understand
