### ISSUE TITLE
message body content in POST method.

### ISSUE THREAD

**Issue by bharath-c** [SoftInstigate/restheart#216]
HI,
I was trying to extend restheart with ApplicationLogicHandler clas.
in handleRequest i wanted to parse POST method. But i couldnt find any function to fetch message body data. 
Im not sure if that a bug or intended functionality. 
Sorry if Im posting in wrong forum.

**Comment by ujibang** [comment]
Hi @bharath-c 

to implement an Application Logic you need to implement the mehtod

`public void handleRequest(HttpServerExchange exchange, RequestContext context) throws Exception {`

The RequestContext object allows you to get the input body wit the method `public BsonValue getContent()`

**Comment by bharath-c** [comment]
Thanks for ur reply.
I had done same but Im getting null pointer exception.
Message body is {"data":"restheart"}
Pls guide

**Comment by bharath-c** [comment]
this helped me.
	StringWriter writer = new StringWriter();
		IOUtils.copy(exchange.getInputStream(), writer);
		String payLoad = writer.toString();

Anyways thanks a lot.
