### ISSUE TITLE
Poor performance with pagesize larger than 101

### ISSUE THREAD

**Issue by marx-espirit** [SoftInstigate/restheart#218]
Hi,

we are facing some performance issues when using a filter query with a page Size greater than 101.

Out database has a single collection with ~800.000 documents. The collection contains two types of documents with different type attributes ('fs_entity_type':'News' and 'fs_entity_type':'Product') There are ~500.000 News documents and ~300.000 Product documents. We have created an index for the field fs_entity_type.

These are the queries:
<restheart>/bigproject/content?filter={'fs_entity_type':'News'}&pagesize=101
<restheart>/bigproject/content?filter={'fs_entity_type':'Products'}&pagesize=101

The performance of these queries is very well. But if we increase the page size to 102, queries become 3-5 times slower.

Both restheart and mongodb are running on the same host, so networking should not be the problem. Using the mongo shell is also performing well.

Any ideas?

I could provide a mongoexport if this helps.

**Comment by ujibang** [comment]
yes please provide the mongoexport

**Comment by marx-espirit** [comment]
You can download the export from here https://github.com/marx-espirit/files/raw/master/mongodumb/content.tar.gz

**Comment by ujibang** [comment]
we reproduced the issue.

we increased the batch size of the find method invocation to 1000 (that is the highest valid value for pagesize)

this way we passed from about 5 tps to 121 tps with pagesize=102

can you try the latest snapshot build https://oss.sonatype.org/content/repositories/snapshots/org/restheart/restheart/3.1.0-SNAPSHOT/restheart-3.1.0-20170613.142712-67.tar.gz

**Comment by marx-espirit** [comment]
With the latest snapshot it works very well for all pagesizes.

Thanks.

**Comment by mkjsix** [comment]
@marx-espirit FYI, we've just released [RESTHeart 3.1](https://github.com/SoftInstigate/restheart/releases/tag/3.1.1)
