### ISSUE TITLE
Set the ReadPreference via configuration

### ISSUE THREAD

**Issue by marx-espirit** [SoftInstigate/restheart#219]
We are using restheart with a mongo cluster of three nodes. We use a correct mongo cluster uri.
All writes and reads are forwarded to the primary instance, that's the default java driver behaviour. What we need is the posibility to configure the ReadPreference of the MongoClient (http://api.mongodb.com/java/current/com/mongodb/ReadPreference.html) via the restheart configuration.

I haven't found any documentation about that.
Is that possible somehow?

**Comment by ujibang** [comment]
you can set the read preference in the connection uri 

see https://docs.mongodb.com/manual/reference/connection-string/#urioption.readPreference

**Comment by marx-espirit** [comment]
Ah, I didn't see that. Thanks.

**Comment by mkjsix** [comment]
Closing. Feel free to re-open in case of further questions. Thank you.
