### ISSUE TITLE
UnsupportedDocumentIdException - "the type of _id in request data is not supported: DOCUMENT"

### ISSUE THREAD

**Issue by four43** [SoftInstigate/restheart#225]
Hey all,

I'm porting an application over to use RESTHeart, these objects use complex documents as _id/primary keys (not auto assigned ObjectIds). Is that not supported in RESTHeart? I was looking for documentation on it but couldn't find any.

Thanks,
-Seth

**Comment by ujibang** [comment]
documentation about the document id can be found at https://softinstigate.atlassian.net/wiki/x/ToCM#ResourceURI-Documentid

the problem with _id of type document is that we cannot generate an URI for that resource.

for instance see the URIs of the following documents:

```
{ "_id": { "$oid": "5951238c2e461ec87775ef3a" } } => /db/coll/5951238c2e461ec87775ef3a
{ "_id": "1" } => /db/coll/1
{ "_id": 1 } => /db/coll/1?id_type=number
```

we haven't found a way to genere a URI for documents with _id of type document:

```
{ _id:  { "a": 1, "b": "test" } } => /db/col/????
```

nevertheless you should be able to access your document via a filtered collection GET:

```
GET /db/coll?filter={"_id:" { "a": 1, "b": "test" } }
```

however trying to create such a document leads to an error:

```
POST /db/coll  {"_id":{"a":1,"b":"test"}}

{
    "_exceptions": [
        {
            "exception": "org.restheart.hal.UnsupportedDocumentIdException",
            "exception message": "unknown _id type: BsonDocument"
        }
    ],
    "http status code": 406,
    "http status description": "Not Acceptable",
    "message": "the type of _id in request data is not supported: DOCUMENT"
}
```

this is a bug, we will fix it.

**Comment by ujibang** [comment]
created task https://softinstigate.atlassian.net/browse/RH-249

**Comment by four43** [comment]
Ah I see, I was trying to create a set of documents via POST of a JSON array, if that helps. Thanks for the feedback and work on the project. I appreciate it!

**Comment by four43** [comment]
Hey guys, I was hacking on a side project a little bit for a work around. I thought of a non-breaking interface change that would be nice. 

One use case I have is a bulk update of data where I don't know the _id. I only know some other unique keyed fields. I can't use bulk update because that only seems to work if I include an _id, so it's just inserting the data. What if I post something like this:

```json
[
    [
        {
           "a": 123
        },
        {
            "b": "hello"
        }
    ],
    [
        {
           "a": 456
        },
        {
            "b": "world"
        }
    ]
]
```

Posting an array of arrays. This allows me to send filter criteria and the data to update in one query. Thoughts on that? It's not super ... REST like since the POSTed documents don't really look like the output, but it provides added functionality. Thanks!

**Comment by ujibang** [comment]
fixed in master. now documents with _id of type object can be created.

note that due to mongodb limitation, _id cannot be an array
