### ISSUE TITLE
M2M Link HREF Has Double Square Brackets in Filter

### ISSUE THREAD

**Issue by keitwb** [SoftInstigate/restheart#226]
Hello,

I have a many-to-many relationship that seems to be generating the wrong link URL.  

I have a collection that has links to a lease collection:

        {
            "ref-field": "$.leases", 
            "rel": "leases", 
            "role": "OWNING", 
            "target-coll": "leases", 
            "type": "MANY_TO_MANY"
      }

But when I get documents from that collection they have links like the following:

    "_links": {
        "leases": {
            "href": "/leases?filter={'_id':{'$in':[['1','2']]}}"
        }, 
        ...
    }

Notice that there are **two** square brackets around the value of the `$in` filter, which causes a GET request on that href to return nothing.  If I remove one pair of the brackets, it works as expected. The `leases` field on the doc is just a simple array: `["1", "2"]`, which I assume is the proper format.  Am I doing something wrong with setting up the rels or is this a bug?  

I am using RESTHeart version 3.1.1.

**Comment by ujibang** [comment]
I double checked this issue and also created a [test case](https://github.com/SoftInstigate/restheart/blob/master/src/test/java/org/restheart/test/integration/RelationshipsIT.java) for it.

@keitwb your relationship definition is wrong. the json path expression `$.leases` points to the array; however the leases ids are the _elements_ of the array. so it should be `$.leases.[*]` (or just `leases`)

that was why the array in the _links was an array of array.

**Comment by keitwb** [comment]
Thanks @ujibang, adding the `.[*]` fixed it!
