### ISSUE TITLE
How to execute PATCH request for modifying document using HttpURLConnection in JAVA

### ISSUE THREAD

**Issue by sai10** [SoftInstigate/restheart#228]
/**
here I have used HttpURLConnection class to provide http service
 * SAMPLE CODE - its giving 405 as response 
 */

        public class TestRestHeartUpdate{
        public static void main(String[] args) throws Exception{

        URL url;
        url = new URL("http://127.0.0.1:8080/testDB1/col1/5967c13e61f73b88018db783");

        HttpURLConnection hc;
        hc = (HttpURLConnection) url.openConnection();
        hc.setDoInput(true);
        hc.setDoOutput(true);
        hc.setRequestMethod("POST");
        hc.setRequestProperty("X-HTTP-Method-Override", "PATCH");

        hc.setRequestProperty("Content-Type","application/hal+json");
        hc.setRequestProperty("Accept","application/hal+json");
        hc.setInstanceFollowRedirects(false);
        hc.setRequestProperty("If-Match","5967c28f42483b1c3dbedc54");
        hc.setUseCaches(false);
        hc.connect();

        byte[] opB = " {'rating':'VeryGood'}".getBytes("UTF-8");
        OutputStream os = hc.getOutputStream();
        os.write(opB);
        System.out.println(hc.getResponseCode());
    }
}

**Comment by ujibang** [comment]
Looking at your code, you are using POST method on a document resource. This is not allowed. Use PUT or PATCH

**Comment by sai10** [comment]
But in HttpURLConnection java class, there is no request method denoting PATCH defined.

**Comment by ujibang** [comment]
Your problem should be the following line

`hc.setRequestMethod("POST");`

**Comment by sai10** [comment]
Yes exactly, but that is what I got in response from stackoverflow. However they mentioned , it depends on the respective server whether it will accept it or not. So can please provide a solution to it.

**Comment by ujibang** [comment]
use unirest library. http://unirest.io/java.html
