### ISSUE TITLE
While updating an int field it is getting updated as string in the document.

### ISSUE THREAD

**Issue by sai10** [SoftInstigate/restheart#229]
command:
---------------
http PATCH 127.0.0.01:8080/testDB1/col1/59737cbeed1d17e8bed6d79f  If-Match:5973a6e442483b0c988c5b12  "age"=007

updated document:
---------------------------
{
	"_id" : ObjectId("59737cbeed1d17e8bed6d79f"),
	"_etag" : ObjectId("5973a70942483b0c988c5b13"),
	"name" : "Sam",
	"rating" : "good",
	"age" : "007",
}

**Comment by ujibang** [comment]
That's httpie. If you want an interview field you have to specify the value with `age:=7`
