### ISSUE TITLE
delete element from an array

### ISSUE THREAD

**Issue by ganeshkaki** [SoftInstigate/restheart#233]
How to delete an element from an array using some parameter in the element. Can any one help?

Thanks

**Comment by mkjsix** [comment]
Have a look at the `$pull` operator in MongoDB: https://docs.mongodb.com/manual/reference/operator/update/pull/

Please refer to the official documentation on how to use **update operators** with RESTHeart: https://softinstigate.atlassian.net/wiki/display/RH/Write+Requests#WriteRequests-Updateoperators

Rif #90

**Comment by ujibang** [comment]
an example using httpie

`$ http -a a:a PUT 127.0.0.1:8080/db/coll/array a:='[{"b":1},{"b":2}]'`

this creates a document with the array `a` with 2 elements:

```
{
    "_etag": {
        "$oid": "598038a2a86d8544e3fa9895"
    },
    "_id": "array",
    "a": [
        {
            "b": 1
        },
        {
            "b": 2
        }
    ]
}
```

this removes the element in the array `a` with `b=2` 

`$ http -v -a a:a PATCH 127.0.0.1:8080/db/coll/array "\$pull":='{"a":{"b":2}}'`

**Comment by ujibang** [comment]
closing this issue. @ganeshkaki feel free to reopen if you need more help.
