### ISSUE TITLE
how to find all unique field property names in a collection with restheart aggregation?

### ISSUE THREAD

**Issue by thm1118** [SoftInstigate/restheart#234]
[do this with MapReduce](https://stackoverflow.com/questions/2298870/mongodb-get-names-of-all-keys-in-collection)
`mr = db.runCommand({
  "mapreduce" : "my_collection",
  "map" : function() {
    for (var key in this) { emit(key, null); }
  },
  "reduce" : function(key, stuff) { return null; }, 
  "out": "my_collection" + "_keys"
})`
Then run distinct on the resulting collection so as to find all the keys:
`db[mr.result].distinct("_id")
["foo", "bar", "baz", "_id", ...]`

**Comment by ujibang** [comment]
@thm1118 you can define aggregations (both aggregation pipelines and mapreduce) on restheart.

please refer to [Aggregations](https://softinstigate.atlassian.net/wiki/x/AwDw) documentation page.
