### ISSUE TITLE
Filtering results based on authenticated user

### ISSUE THREAD

**Issue by volnei** [SoftInstigate/restheart#235]
How to filter elements on a collection based on a Authenticated User, using custom user collection? I saw examples using filter on url, but it's not secure cause users can change the parameter.

Eg, Supose I have my users collections to authenticated users and want to filter only notes for the logged in user.

**Comment by ujibang** [comment]
@volnei my suggestion is to use a transformer to add a filter query parameter to the request based on authenticated user's role.

note that a request with multiple filter query parameters, eg `/db/coll?filter={"a":1}&filter={"b":2}`, executes a query with the filters combined with the `$and` operator.

I personally used often this approach and I find it elegant and effective.

**Comment by volnei** [comment]
@ujibang, thanks for your reply. 

But in this way, all data is exposed using /db/coll without filters, right?

**Comment by ujibang** [comment]
Not really. In the transformer you enforce the filter that you want, limiting the results according to user role

**Comment by ujibang** [comment]
@volnei in the following example, the transformer method **tranform()** injects a filter enforcing the _owner_ property of the document to be equal to the username in case the authenticated user has no ADMIN role

`@Override
    public void transform((HttpServerExchange exchange, RequestContext context, BsonValue contentToTransform, BsonValue args) {
        if (context.isGet()
                && (context.isCollection()
                || context.isDocument())) {

            Deque<String> filters = context.getFilter();

            if (filters == null) {
                filters = new ArrayDeque<String>();
                // needed in case the deque has been instantiated here
                context.setFilter(filters);
            }
            
            // get user role
            
            Set<String> roles = context.getAuthenticatedAccount().getRoles();

            if (!roles.contains("ADMIN")) {
                BsonDocument filter = new BsonDocument("owner", new BsonString(context
                        .getAuthenticatedAccount().getPrincipal().getName()));
                
                filters.add(filter.toJson());
            }
        }
    }`

**Comment by ujibang** [comment]
@volnei I'm closing this issue, feel free to reopen if you need more support
