### ISSUE TITLE
Unable to save ISODate in MongoDB Collection

### ISSUE THREAD

**Issue by nitinware** [SoftInstigate/restheart#237]
I am calling RestHeart Post API to insert  a document in collection from my Java application.
I am passing Java request pojo with a java.util.Date feild "lastModifiedDate" but it is not getting is saved as ISODate, instead it is getting saved as NumberLong.

```
Saved as "lastModifiedDate" : NumberLong("1503540612123")
Instead of "lastModifiedDate" : ISODate("2015-02-28T00:00:00Z")
```

Can you please help me to identify a way to pass the date object from Java pojo, so that it is save in ISODate format in mongodb. 
Any help is highly appreciated.
Thanks.

**Comment by ujibang** [comment]
Use { "$date": <epoch> }

**Comment by nitinware** [comment]
@ujibang - Thanks for quick response, appreciate it. 
Sorry but can you please elaborate more on the above solution.

My Request pojo is a mentioned below, 

```
public class Sensor {

    private String sensorID;

    private String sensorName;

    private Integer sensorState;

    private Float tempreature;

    private String lastModifiedDate;

}

```

what should i change in lastModifiedDate feild so that it value is saved as ISODate(''") in mongodb.
I am making restemplate call by passing the instance of above mentioned Sensor class.

**Comment by ujibang** [comment]
Please refer to [Strict mode representations of BSON](https://softinstigate.atlassian.net/wiki/x/UICM#RepresentationFormat-StrictmoderepresentationsofBSON) section of RESTHeart documentation.

> RESTHeart represents the state of MongoDb resources using the strict mode representations of BSON that conforms to the JSON RFC. 


```
{
   "_id": { "$oid": "546b2dcdef863f5121fc91f3" },    
    "date": { "$date": 1503906057000  },    
    "pi": 3.1415
}
```

the date object is represented as { "$date": 1503906057000  }, where the number value is the epoch time in milliseconds. In this way, mongodb stores the date attribute as a Date object

**Comment by nitinware** [comment]
@ujibang - Thanks for detailed response, I highly appreciate it.
Since I wanted to store the current timestamp in UTC, I used the below approach to save the current timestamp in UTC and it worked for me.

`{ "sensorID":"ID001", "sensorName" : "Sensor_NYC", "sensorState" : 1, "tempreature" : 75, "$currentDate": {"timestamp": true }`
