### ISSUE TITLE
Bulk update with PATCH request is failing with 400 response

### ISSUE THREAD

**Issue by kmurali676** [SoftInstigate/restheart#238]
Bulk update with PATCH request is failing with 400 response. 

PATCH {{host}}/mydb/releases/*?filter={"code":"9780000000774"}
Content-Type: application/json

#body
{"$inc":{"count":1}}

Response:
HTTP/1.1 400 request check failed

{
  "_warnings": [
    "the checker JsonSchemaChecker does not support this request and is configured to fail in this case. Note that the request uses update operators and it is a bulk operation"
  ],
  "http status code": 400,
  "http status description": "Bad Request",
  "message": "request check failed"
}

**Comment by ujibang** [comment]
From [Request Checker](https://softinstigate.atlassian.net/wiki/x/jYCM) documentation page:

> The collection _metadata_ property checkers allows to declare a checker to be applied to the requests involving the documents of the collection.
> [checkers](url) is an array of [checker](url) objects. A checker object has the following format:

```
{ "name": <checker_name>,"args": <arguments>, "skipNotSupported": <boolean> }
```

JsonSchemaChecker does not support bulk requests. Thus you need to set `skipNotSupported: true` if you want to execute that request.

Note that you can also set a second custom checker, that would only support this request if you need to enforce a check anyway.

**Comment by ujibang** [comment]
closing for now, feel free to reopen if you need further help
