### ISSUE TITLE
Disable color logging?

### ISSUE THREAD

**Issue by replicant0wnz** [SoftInstigate/restheart#240]
Is there a config option for this? I dump all my logs to elasticsearch and they just end up w/the ansi color codes ..

**Comment by mkjsix** [comment]
@replicant0wnz not yet, but it should be fairly easy to add it, I'm having a look.

**Comment by mkjsix** [comment]
https://softinstigate.atlassian.net/browse/RH-250

**Comment by mkjsix** [comment]
Hi @replicant0wnz Release [3.1.2](https://github.com/SoftInstigate/restheart/releases/tag/3.1.2) adds a configuration parameter to enable or disable the ANSI console. By default is set to true, so you have to edit your `restheart.yml` configuration file and set it to false:

`ansi-console: false`

The related commits are also on master (so 3.2.0-SNAPSHOT).

Please let us know if it works for you.

**Comment by replicant0wnz** [comment]
Well that was quick, thanks! Upgraded and verified logging, works perfect. Again, thanks!
