### ISSUE TITLE
config file path has space , restheart then  can not resolve config file

### ISSUE THREAD

**Issue by thm1118** [SoftInstigate/restheart#248]
in class `AbstractSimpleSecurityManager`,  method `init` , it should use like `is = new FileInputStream(new File(java.net.URLDecoder.decode(confFilePath,"utf-8")));`  to compatibility with  path which has sapce

**Comment by mkjsix** [comment]
https://softinstigate.atlassian.net/browse/RH-253

**Comment by mkjsix** [comment]
Fixed in master.
https://github.com/SoftInstigate/restheart/commit/27c4475b5be4d3bfd9e5728a22afa5e12583849e
