### ISSUE TITLE
Geospatial Queries are not working for mongodb with restheart.

### ISSUE THREAD

**Issue by shivadarshan91** [SoftInstigate/restheart#255]
Hi Team,

i have stored geo location data in mongodb. when i query with some coordinates, mongodb gives me nearest location from **places_data** collection. 

**Query:**
db.getCollection('places_data').find({location:{ $nearSphere:{ $geometry: { type: "Point",  coordinates: [ 76.651086, 14.318631]}}}}).limit(1)

But same is not working when i query through restheart:

http://localhost:8080/location_db/places_data?pagesize=1&filter={%22location%22:{%22$nearSphere%22:{%22$geometry%22:{%22type%22:%22Point%22,%22coordinates%22:[76.652822,14.313394]}}}}

please can you help me in this.

Regards,
Shivadarshan

**Comment by ujibang** [comment]
RESTHeart sorts by _id by default. 

from MongoDB [documentation](https://docs.mongodb.com/manual/reference/operator/query/near/#sort-operation) 

> $near sorts documents by distance. If you also include a sort() for the query, sort() re-orders the matching documents, effectively overriding the sort operation already performed by $near. When using sort() with geospatial queries, consider using $geoWithin operator, which does not sort documents, instead of $near.

Solution is just specifying no sorting with `sort={}` query parameter

```GET http://localhost:8080/location_db/places_data?sort={}&pagesize=1&filter={%22location%22:{%22$nearSphere%22:{%22$geometry%22:{%22type%22:%22Point%22,%22coordinates%22:[76.652822,14.313394]}}}}```

**Comment by shivadarshan91** [comment]
Great.. it works like charm. Thank you

Thanks and regards,
Shivadarshan
