### ISSUE TITLE
Default sort makes query extremely slow

### ISSUE THREAD

**Issue by scathers** [SoftInstigate/restheart#256]
I am using RESTHeart to query a large collection (60 million documents). When running a query that filters based on an indexed field, the query takes over 8 minutes to return. If I run the same query directly against MongoDB, it returns in 0.15 seconds. After digging into the code, I found that even when no sort parameters are provided, RESTHeart inserts a [default sort by descending _id](https://github.com/SoftInstigate/restheart/blob/328c384b831494b22d0a736c12a52b8b500feb80/src/main/java/org/restheart/handlers/RequestContext.java#L649). If I comment out this line, results return in a fraction of a second.

I'm wondering, is there a particular reason that RESTHeart forces a sort to take place on every query? And is there some way to disable this behavior so that queries like this return in a reasonable amount of time?

**Comment by ujibang** [comment]
To disable default sorting just add `sort={}` query parameter

**Comment by scathers** [comment]
Can you shed any light on the rationale for always putting in a default sort? It would be helpful to at least note in the documentation that RESTHeart is doing this and that it can severely affect query performance, along with putting in the tip about passing in an empty sort object to disable it.

**Comment by ujibang** [comment]
Hi, from mongodb doc

      Unless you specify the sort() method or use the $near operator, MongoDB does not guarantee the order of query results.

Now restheart returns data in pages (default being 100) and it is stateless. This means that two requests use different db cursors.

A default sorting makes sure that requests on different pages returns documents in a well defined order.

If you query a 60 millions documents collections you sure need to filter it somehow and make sure your request make use of indexes unless you just need to get few documents in an undefined order. 

With a filter applying, sorting shouldn't be a problem.

**Comment by ujibang** [comment]
Closing this, feel free to reopen if you have more to discuss

**Comment by mkjsix** [comment]
Meanwhile I've added some more emphasis on the "Default sorting" section in the docs:

https://softinstigate.atlassian.net/wiki/spaces/RH/pages/10747996/Query+Documents#QueryDocuments-Defaultsorting
