### ISSUE TITLE
New release 3.2.0

### ISSUE THREAD

**Issue by mkjsix** [SoftInstigate/restheart#257]
# Release notes - RESTHeart [3.2.0](https://github.com/SoftInstigate/restheart/releases/tag/3.2.0) #
                
## What's new in this release ##

- Fully tested with [MongoDB 3.6](https://www.mongodb.com/mongodb-3.6);
- [Dropwizard metrics](https://softinstigate.atlassian.net/wiki/x/HAALBw) on requests;
- Editing metadata for [GridFS](https://softinstigate.atlassian.net/wiki/x/RoCw) binary files;
- Several bug fixes and performances improvements.

## Binaries ##

As usual, RESTHeart server can be downloaded and [executed as is](https://softinstigate.atlassian.net/wiki/x/FICM) or available is other formats:

- As a [Docker image](https://hub.docker.com/r/softinstigate/restheart/);
- As a [Maven artifact](https://mvnrepository.com/artifact/org.restheart/restheart);

The Maven dependencies are meant to create custom extensions, such as [Application Logic Handlers](https://softinstigate.atlassian.net/wiki/x/IoCw) and [Request Hooks](https://softinstigate.atlassian.net/wiki/x/EgAtAQ).

Please help us improving the product by opening issues or PRs.

**Comment by boesebeck-espirit** [comment]
Awesome!
