### ISSUE TITLE
Undertow produces "Already in use" exception

### ISSUE THREAD

**Issue by wdonne** [SoftInstigate/restheart#259]
Hello,

I'm trying to run two RESTheart instances on the same machine. Both only use the HTTP listener. One is on port 8080 and the other on port 8081. Despite this I get the following exception:

14:29:01.041 [main] [1;31mERROR[0;39m org.restheart.Bootstrapper - Error starting RESTHeart. Exiting...
java.lang.RuntimeException: java.net.BindException: Address in use
	at io.undertow.Undertow.start(Undertow.java:245)
	at org.restheart.Bootstrapper.startCoreSystem(Bootstrapper.java:616)
	at org.restheart.Bootstrapper.startServer(Bootstrapper.java:390)
	at org.restheart.Bootstrapper.main(Bootstrapper.java:152)
Caused by: java.net.BindException: Address in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:191)
	... 3 common frames omitted

Best regards,

Werner.

**Comment by ujibang** [comment]
Check that both http and https restheart's listeners are configured with different ports and that there isn't other process holding them.

**Comment by wdonne** [comment]
This is the config of the first instance:

https-listener: false
https-host: 0.0.0.0
https-port: 4443

http-listener: true
http-host: localhost
http-port: 8080

ajp-listener: false
ajp-host: 0.0.0.0
ajp-port: 8009

This is the one of the second:

https-listener: false
https-host: 0.0.0.0
https-port: 4443

http-listener: true
http-host: localhost
http-port: 8081

ajp-listener: false
ajp-host: 0.0.0.0
ajp-port: 8009

The second one binds correctly to port 8081:

16:45:55.220 [main] [34mINFO [0;39m org.restheart.Bootstrapper - HTTP listener bound at localhost:8081

The second instance fails even when the first isn't running, so there is a conflict with another process, but the exception doesn't say for which port the bind fails.

**Comment by mkjsix** [comment]
The `java.net.BindException` just tells that the address is already in use, you need to find out which process is actually binding to port 8080 on your machine. The command to do that varies, depending on the operating system you are running. See [this thread](https://unix.stackexchange.com/questions/9252/determining-what-process-is-bound-to-a-port) for some examples.
As soon as you have this information, you can kill the binding process.

**Comment by wdonne** [comment]
There is no problem with port 8080. It is used by the first instance without any problems. The second instance I try to launch binds only to port 8081 and that works fine too. Only a bit later there is an “Already in use” exception WITHOUT any mention of a port. So how am I going to find the conflicting port?

**Comment by ujibang** [comment]
closing this for now. feel free to reopen it
