### ISSUE TITLE
Can RestHeart be started as a service???

### ISSUE THREAD

**Issue by chaithrachithu1** [SoftInstigate/restheart#265]
Hi All,

When ever I start RestHeart, it is starting as a process. But, I would like to start RestHeart as a service rather. Is there a way that can be achieved????

**Comment by mkjsix** [comment]
Yes, but it depends on which operating system...

**Comment by chaithrachithu1** [comment]
I'm having Windows 8 as Operating system

**Comment by mkjsix** [comment]
We don't use Windows here, so no direct experience with it.

However, RESTHeart is a self-contained Java application, you can have a look at #212 which suggests to use **[Procrun](https://commons.apache.org/proper/commons-daemon/procrun.html)**:

_Procrun is a set of applications that allow Windows users to wrap (mostly) Java applications (e.g. Tomcat) as a Windows service._ 
_The service can be set to automatically start when the machine boots and will continue to run with no user logged onto the machine._
