### ISSUE TITLE
Suggestion : continuous calls of StringBuilder.append 

### ISSUE THREAD

**Issue by o0lwj0o** [SoftInstigate/restheart#266]
Hi,
&nbsp;&nbsp;&nbsp;&nbsp;I have found some continuous calls about `StringBuilder.append(..)` in some files. For example, there are ten continuous calls in the function generateTimer from the file restheart/src/main/java/org/restheart/utils/MetricsJsonGenerator.java. 
```Java
 private BsonDocument generateTimer(Timer timer) {
        BsonDocument document = new BsonDocument();
        final Snapshot snapshot = timer.getSnapshot();
        document.append("count", new BsonInt64(timer.getCount()));
        document.append("max", new BsonDouble(snapshot.getMax() * durationFactor));
        document.append("mean", new BsonDouble(snapshot.getMean() * durationFactor));
        document.append("min", new BsonDouble(snapshot.getMin() * durationFactor));

        document.append("p50", new BsonDouble(snapshot.getMedian() * durationFactor));
        document.append("p75", new BsonDouble(snapshot.get75thPercentile() * durationFactor));
        document.append("p95", new BsonDouble(snapshot.get95thPercentile() * durationFactor));
        document.append("p98", new BsonDouble(snapshot.get98thPercentile() * durationFactor));
        document.append("p99", new BsonDouble(snapshot.get99thPercentile() * durationFactor));
        document.append("p999", new BsonDouble(snapshot.get999thPercentile() * durationFactor));
        ......
}
```
&nbsp;&nbsp;&nbsp;&nbsp;If it was achieved like `StringBuilder.append(..).append(..)append(..)`, it will promote its performance.

**Comment by mkjsix** [comment]
Thanks @o0lwj0o 

Despite I might agree that not repeating the document variable would be nicer for readability (but very subjective), why do you think it could make any difference in term of performances? Besides, it's a BsonDocument and not a StringBuilder, and the "append" method returns a reference to the document variable anyway, so I guess the compiler should output exactly the same bytecode.
