### ISSUE TITLE
Restheart not responsive

### ISSUE THREAD

**Issue by iwoork** [SoftInstigate/restheart#269]
I'm running docker version on Azure VM and when I run docker-compose up, it says that the RESTheart started. When I try to access the page, the normal HTTP authentication works but after successfully being authenticated, the browser just gets stucked with "Waiting for..." for a very very long time. Sometimes I get a response but most of the time not. I tried looking at logs but doesnt give me much details about the issue if it's my server or restheart itself. I was able to connect to the MongoDB successfully through a client and based on the startup log of restheart. I did check the firewall settings and all.

Any ideas?

**Comment by mkjsix** [comment]
Hi @iwoork 
We've never experienced similar issues, but we haven't run it on Azure. The weird thing is that you say that sometime you get a response, so it doesn't sound like a firewall issue. It seems that the HTTP request gets redirected "somewhere" and after bouncing here and there it eventually hit the server. So it looks like a weird networking problem between Restheart and mongodb.

Questions: which OS is the Azure VM? Are Restheart and Mongo running on that same VM?

**Comment by iwoork** [comment]
Yes it's really weird. It is running on a Ubuntu 16 VM on Azure. And yes Restheart and Mongo are running on the same VM as it's using docker-compose. it works sometimes, 1 out of 10 I would say. Occasionally I am able to access the endpoint if I leave it running for a long time. And then after a couple of use, it will get stucked again. No logs or errors to identify what happened.

To test, I also tried running a nodeJS app in port 80 (concurrently with restheart's port 8080) and the nodeJS app works just fine.

**Comment by mkjsix** [comment]
I suggest to post your question also to https://stackoverflow.com/questions/tagged/restheart where you can find a wider audience.

**Comment by iwoork** [comment]
I'm closing this as I have found the issue. Our azure has loadbalancer so need to just turn the `auth-token-enabled` to false!

**Comment by mkjsix** [comment]
Thanks @iwoork for letting us know.
