### ISSUE TITLE
How to upsert a array element in mongo

### ISSUE THREAD

**Issue by prakashsubramaniam** [SoftInstigate/restheart#272]
Hi,

I am having a requirement to upsert an array in mongo db and I would request your help to achieve it.

Scenario:
When we create a document in mongo we will be creating a employment array and we will be inserting what ever we get in the input. But when we update we may need to insert an additional element to an array. But I am not sure whether the element is existing or not. So my Patch should do update if the element if it is already present or it should insert a new element to an array if it is not present already.

I am using $set with PATCH methodd and using filterstring (employmentType) to get the exact element of the array to update.

Could you please If I need to use any other mongo update operator other than $set and is it because of the filter string in the url?

But filter string the mandatory thing to update the specific object. So I need to use the filterstring anyway but it should do upsert for an array.

Please let me know if you need any more information.

**Comment by prakashsubramaniam** [comment]
Hi Ujibang,

Could you please help me for the issue?

**Comment by ujibang** [comment]
Hi,

To us pert an element to an array you can use the $addToSet operator.

**Comment by prakashsubramaniam** [comment]
Hi Ujibang,

Thanks for your reply!

Unfortunately, $addToSet is not suiting for our requirement. As we need to check and update some fields only if the array element is already present, We need to add the element only if it not already present.

But here if we use $addToSet it is always adding the new element and it is not updating the existing element. $addToSet is just checking the field values if there is any change in field value it is considering it as a new element for that array. 

Hope I gave the clear requirement details. Could you please assist us?

**Comment by ujibang** [comment]
Well I don't understand the requirement.

However you can always add a filter qparam.

     PATCH /db/coll/id?filter={"array":"foo"} {"$addToSet":{"array" : "bar"}}

This adds foo to the array only if bar is present. If it is not present it returns 404.

**Comment by prakashsubramaniam** [comment]
Hi Ujibang,

Thank you!

Here is the more elaborated details of my requirement.

There is mongo document which has the employment array object and it can hold multiple element in it (governmentEmployment or privateEmployment or selfEmployed or Business). When we add a person (MongoDocument) we are not sure how many element got added already. 

Ex: Mongodocument has 2 element 
		1. governmentEmployment
		2. PrivateEmployment
		
	But when we do update of a person, user is sending some updates for governmentEmployment and also they want to add business details also.

So in code I should handle to check if governmentEmployment is already present or not, it is already present as per our example. So those information to be updated and Business is not already exist. but still I will be using the below query with filter string as it should be common for all the update.

		PATCH /db/coll/Person1234?filter={"employment.employmentType":"G"}  -- This is to check if governmentEmployment is exist or not.
		PATCH /db/coll/Person1234?filter={"employment.employmentType":"B"}	-- This is to check if Business is exist or not.
		
Since it is update call, I will be getting the request body also from the client. Hence I am sending the dbPatchRequest with $set operator.

**Comment by ujibang** [comment]
closing since it is an old question. feel free to reopen it if still valid.
