### ISSUE TITLE
PATCH db/coll/docid when no document found

### ISSUE THREAD

**Issue by kpetros** [SoftInstigate/restheart#276]
According to documentation, it seems to me that  PATCH db/coll/docid shouldn't perform upserts. When there is no document matching the id, i expect a 404 NOT FOUND response. Instead, a new document is created and the response code is 201 CREATED. 
[PATCH db/coll/docid return codes](https://softinstigate.atlassian.net/wiki/spaces/RH01X/pages/23461939/API+reference#APIreference-PATCH/%3Cdbname%3E/%3Ccollname%3E/%3Cdocid%3E)

I use version 3.2.2

**Comment by ujibang** [comment]
All write requests, including patch have upsert semantic.

To avoid creating a document you can pass the query parameter checkEtag

See http://restheart.org/learn/etag/
