### ISSUE TITLE
Gridfs examples

### ISSUE THREAD

**Issue by jessec** [SoftInstigate/restheart#28]
Hi could you provide some examples of how to work with files (gridfs).

**Comment by ujibang** [comment]
we'll definitely add a dedicated section about buckets and file resources to the [documentation](http://restheart.org/docs/overview.html)

while you wait for it, you can refer to this question https://github.com/SoftInstigate/restheart/issues/24

**Comment by jessec** [comment]
Ok nice that is very useful!
