### ISSUE TITLE
GET on db only succeeds with trailing slash

### ISSUE THREAD

**Issue by christiangroth** [SoftInstigate/restheart#286]
Hi,

we have some issues fetching data from an existing collection when no trailing slash is provided:

## Expected Behavior
curl http://HOST/DB --> HTTP 200 OK
curl http://HOST/DB/ --> HTTP 200 OK

## Current Behavior
curl http://HOST/DB --> HTTP 403 Forbidden
curl http://HOST/DB/ --> HTTP 200 OK

## Environment
* RESTHeart: 3.3.1
* MongoDB: 3.4.10

## Steps to Reproduce
* As this happens with all db there are no special steps needed. Any db with data is sufficient.

For collections it behaves as expected. Maybe we miss something or is this a bug?

Best regards
 Christian

**Comment by christiangroth** [comment]
We've found the root of all evil in our own code extending AccessManager, so we can close this issue. Sorry!

**Comment by mkjsix** [comment]
Glad to hear you solved your issue, you are welcome.
