### ISSUE TITLE
Not able to login to the Notes Web application. Please help resolve the issue.

### ISSUE THREAD

**Issue by askadian** [SoftInstigate/restheart#294]
Restheart – Manual Installation
Example Web Application Issue

1.	MongoDB is installed and is running at 127.0.0.1:27017
`PS   C:\WINDOWS\system32> mongo --version   
MongoDB shell version   v3.4.5   
git version:   520b8f3092c48d934f0cd78ab5f40fe594f96863   
OpenSSL version: OpenSSL   1.0.1u-fips  22 Sep 2016   
allocator: tcmalloc   modules: none   
build environment:       
distmod: 2008plus-ssl       
distarch: x86_64       
target_arch: x86_64
--`

2.	Java 8 is also present
`PS   C:\WINDOWS\system32> java -version   java version   "1.8.0_161"   Java(TM) SE Runtime   Environment (build 1.8.0_161-b12)   Java HotSpot(TM) Client   VM (build 25.161-b12, mixed mode, sharing)
--`

3.	MongoDB has been added with admin roles
`PS   C:\WINDOWS\system32> mongo   MongoDB shell version   v3.4.5   connecting to:   mongodb://127.0.0.1:27017   MongoDB server version:   3.4.5   Server has startup   warnings:   2018-06-28T21:52:11.921-0400   I CONTROL  [initandlisten]   2018-06-28T21:52:11.921-0400   I CONTROL  [initandlisten] ** WARNING:   Access control is not enabled for the database.   2018-06-28T21:52:11.921-0400   I CONTROL  [initandlisten] **          Read and write access to data and   configuration is u   nrestricted.   2018-06-28T21:52:11.921-0400   I CONTROL  [initandlisten]   > use admin   switched to db admin   > db.createUser({   ... user:   "admin",   ... pwd:   "changeit",   ... roles:   ["root"]   ... })   Successfully added user:   { "user" : "admin", "roles" : [   "root" ] }
--`

4.	Restheart is started as follows
`PS C:\code\projs\restheart-3.3.5>   java -jar restheart.jar   22:07:51.168 [main]   INFO  org.restheart.Bootstrapper - ANSI   colored console: true   22:07:51.217 [main]   INFO  org.restheart.Bootstrapper -   Starting RESTHeart instance default   22:07:51.219 [main]   INFO  org.restheart.Bootstrapper -   version 3.3.5   22:07:51.223 [main]   INFO  org.restheart.Bootstrapper -   Logging to file C:\Users\amkadian\AppData\Local\Temp\\restheart.l   og with level INFO   22:07:51.223 [main]   INFO  org.restheart.Bootstrapper -   Logging to console with level INFO   22:07:52.845 [main]   INFO  org.restheart.Bootstrapper -   MongoDB connection pool initialized   22:07:52.845 [main]   INFO  org.restheart.Bootstrapper -   MongoDB version 3.4.5   22:07:52.847 [main] WARN    org.restheart.Bootstrapper - ***** No Identity Manager specified.   Authentication disabled.   22:07:52.848 [main] WARN    org.restheart.Bootstrapper - ***** No access manager specified. users   can do anything.   22:07:52.849 [main]   INFO  org.restheart.Bootstrapper -   Authentication Mechanism io.undertow.security.impl.BasicAuthentic   ationMechanism enabled   22:07:52.850 [main]   INFO  org.restheart.Bootstrapper -   Token based authentication enabled with token TTL 15 minutes   22:07:52.865 [main]   INFO  org.restheart.Bootstrapper -   HTTPS listener bound at 0.0.0.0:4443   22:07:52.865 [main]   INFO  org.restheart.Bootstrapper - HTTP   listener bound at 0.0.0.0:8080   22:07:52.869 [main]   INFO  org.restheart.Bootstrapper -   Local cache for db and collection properties enabled with TTL 100   0 msecs   22:07:52.874 [main]   INFO  org.restheart.Bootstrapper -   Local cache for schema stores not enabled   22:07:53.101 [main]   INFO  org.restheart.Bootstrapper - URL   / bound to MongoDB resource *   22:07:53.276 [main]   INFO  org.restheart.Bootstrapper -   Embedded static resources browser extracted in C:\Users\amkadian\   AppData\Local\Temp\restheart-1284190277989468574   22:07:53.297 [main]   INFO  org.restheart.Bootstrapper - URL   /browser bound to static resources C:\Users\amkadian\AppData\   Local\Temp\restheart-1284190277989468574.   Access Manager: false   22:07:53.575 [main]   INFO  org.restheart.Bootstrapper - RESTHeart started
--`

5.	Web Server for Sample Application gets started
`PS   C:\code\projs\example-angularjs-app\restheart-notes-example> grunt serve   -force   Running   "serve" task       Running   "clean:server" (clean) task   >> 0 paths   cleaned.       Running   "wiredep:app" (wiredep) task       Running   "wiredep:test" (wiredep) task       Running   "wiredep:sass" (wiredep) task       Running   "concurrent:server" (concurrent) task       Running   "compass:server" (compass) task   Warning: not found:   compass Used --force, continuing.       Done, but with warnings.           Execution Time   (2018-06-28 22:14:56 UTC-4)   loading tasks                  22ms  ████ 12%   loading   grunt-contrib-compass  89ms  ████████████████ 50%   compass:server                 67ms  ████████████ 38%   Total 178ms       Running   "autoprefixer:server" (autoprefixer) task       Running   "connect:livereload" (connect) task   Started connect web   server on http://localhost:9000       Running   "watch" task   Waiting...
--`

6.	On launching the application in browser at localhost:9090/#!/signin, the default signin page gets displayed. On using the admin/changeit as user/password, following message gets displayed:
`
Error   contacting RESTHeart. Is it running at http://localhost:8080 ?
--
`

7.	This is what the browser console displays as error message:
`GET   http://localhost:8080/_logi   : 8080/_logic/roles/admin?nocache=1530239437416:1   GET http://localhost:8080/_logic/roles/admin?nocache=1530239437416 403 (Forbidden)
--
`

Please help and guide to resolve the issue.
[Restheart.pdf](https://github.com/SoftInstigate/restheart/files/2147578/Restheart.pdf)

**Comment by askadian** [comment]
Restheart API is reachable through the Windows Power Shell using http, as mentioned below:
`Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> http -a 'admin:changeit' PUT localhost:8080/db desc='this is my first db created with restheart'

HTTP/1.1 201 Created
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, ETag, Auth-Token, Auth-Token-Valid-Until, Auth-Token-Location, X-Powered-By
Connection: keep-alive
Content-Length: 0
Content-Type: application/json
Date: Fri, 29 Jun 2018 03:05:23 GMT
ETag: 5b35a1f3e8128818b4fa0990
X-Powered-By: restheart.org



PS C:\WINDOWS\system32> http -a 'admin:changeit' GET localhost:8080/db
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, ETag, Auth-Token, Auth-Token-Valid-Until, Auth-Token-Location, X-Powered-By
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 152
Content-Type: application/json
Date: Fri, 29 Jun 2018 03:05:39 GMT
ETag: 5b35a1f3e8128818b4fa0990
X-Powered-By: restheart.org

{
    "_embedded": [],
    "_etag": {
        "$oid": "5b35a1f3e8128818b4fa0990"
    },
    "_id": "db",
    "_returned": 0,
    "_size": 0,
    "_total_pages": 0,
    "desc": "this is my first db created with restheart"
}

PS C:\WINDOWS\system32>
`
[Restheart_V1.2.pdf](https://github.com/SoftInstigate/restheart/files/2147633/Restheart.pdf)

**Comment by ujibang** [comment]
I noticed in restheart logs

```
WARN  org.restheart.Bootstrapper - ***** No Identity Manager specified. Authentication disabled. 22:07:52.848 [main] 
WARN  org.restheart.Bootstrapper - ***** No access manager specified. users can do anything.
```

you started restheart without specifying a configuration file

```
java -jar restheart.jar
```

have a look at https://restheart.org/learn/configure-security/#configuration to understand how to enable security.

**Comment by askadian** [comment]
Thanks @ujibang 
I changed the Config File:
`idm:
    implementation-class: org.restheart.security.impl.SimpleFileIdentityManager
    #implementation-class: org.restheart.security.impl.DbIdentityManager
    conf-file: ./etc/security-old.yml
access-manager:
    implementation-class: org.restheart.security.impl.SimpleAccessManager
    conf-file: ./etc/security-old.yml
auth-mechanism:
    #implementation-class: org.restheart.security.impl.SimpleFileIdentityManager
    implementation-class: org.restheart.security.impl.IdentityAuthenticationManagerFactory
    username: admin
    pwd: changeit`

And restarted the RESTHEART SERVER with this file:
`PS C:\code\projs\restheart-3.3.5> java -jar original-restheart.jar ./etc/restheart.yml
23:05:32.495 [main] INFO  org.restheart.Bootstrapper - ANSI colored console: true
23:05:32.500 [main] INFO  org.restheart.Bootstrapper - Starting RESTHeart instance default
23:05:32.502 [main] INFO  org.restheart.Bootstrapper - version 3.3.5
23:05:32.505 [main] INFO  org.restheart.Bootstrapper - Logging to console with level INFO
23:05:33.715 [main] INFO  org.restheart.Bootstrapper - MongoDB connection pool initialized
23:05:33.715 [main] INFO  org.restheart.Bootstrapper - MongoDB version 3.4.5
23:05:33.731 [main] INFO  org.restheart.Bootstrapper - Identity Manager org.restheart.security.impl.SimpleFileIdentityMa
nager enabled
23:05:33.791 [main] INFO  org.restheart.Bootstrapper - Access Manager org.restheart.security.impl.SimpleAccessManager en
abled
23:05:33.793 [main] INFO  org.restheart.Bootstrapper - Authentication Mechanism org.restheart.security.impl.IdentityAuth
enticationManagerFactory enabled
23:05:33.794 [main] INFO  org.restheart.Bootstrapper - Token based authentication enabled with token TTL 15 minutes
23:05:33.801 [main] INFO  org.restheart.Bootstrapper - HTTPS listener bound at 0.0.0.0:4443
23:05:33.804 [main] INFO  org.restheart.Bootstrapper - HTTP listener bound at localhost:8080
23:05:33.809 [main] INFO  org.restheart.Bootstrapper - Local cache for db and collection properties enabled with TTL 100
0 msecs
23:05:33.810 [main] INFO  org.restheart.Bootstrapper - Local cache for schema stores enabled  with TTL 1000 msecs
23:05:33.941 [main] INFO  org.restheart.Bootstrapper - URL / bound to MongoDB resource *
23:05:33.943 [main] ERROR org.restheart.Bootstrapper - Failed to bind URL /browser to static resources browser. Director
y does not exist.
23:05:33.946 [main] INFO  org.restheart.Bootstrapper - URL /_logic/ping bound to application logic handler org.restheart
.handlers.applicationlogic.PingHandler. Access manager: false
23:05:33.948 [main] INFO  org.restheart.Bootstrapper - URL /_logic/roles bound to application logic handler org.resthear
t.handlers.applicationlogic.GetRoleHandler. Access manager: true
23:05:33.950 [main] INFO  org.restheart.Bootstrapper - URL /_logic/ic bound to application logic handler org.restheart.h
andlers.applicationlogic.CacheInvalidator. Access manager: true
23:05:33.959 [main] INFO  org.restheart.Bootstrapper - URL /_logic/csv bound to application logic handler org.restheart.
handlers.applicationlogic.CsvLoaderHandler. Access manager: true
23:05:34.112 [main] INFO  org.restheart.Bootstrapper - RESTHeart started`

Now the login is allowed. Thanks!
