### ISSUE TITLE
filter doesn't work

### ISSUE THREAD

**Issue by jmbeuken** [SoftInstigate/restheart#301]
Hi,

check if communication works with DB : 

> curl -k -u a:a  https://restheart_server:4443/buildbot/slaves?pagesize=1
> 
> {"_embedded":[{"_id":{"$oid":"5b0e91378c89b49c6baf1731"},"name":"buda2","brand":"Supermicro + GPU","os":"CentOS 7.4","vendor":"intel","cpu":"2 x Silver 4110 CPU @ 2.10GHz","core":32,"ram":16,"speed":"fast","max_builds":2,"builders":["buda2_gnu_6.4_cuda","buda2_gnu_8.1_mpich3"],"passwd":"xxxxx","reference":false,"active":true}],"_id":"slaves","_returned":1}
> 

ok !

but with filter ( or keys,...), Bad Request : 

> curl -k -u a:a  https://restheart_server:4443/buildbot/slaves?filter={'name':'abiref'}
> 
> {"_exceptions":[{"exception":"org.bson.json.JsonParseException","exception message":"JSON reader was expecting a value but found 'name'."}],"http status code":400,"http status description":"Bad Request","message":"illegal filter paramenter: name:abiref"}
> 

I tried also this : 

```
curl -g -v -k -u a:a  https://restheart_server:4443/buildbot/slaves?filter={\"name\":\"abiref\"}
*   Trying restheart_server...
<snip>
...
</snip>
* ALPN, server did not agree to a protocol
* Server auth using Basic with user 'a'
> GET /buildbot/slaves?filter={"name":"abiref"} HTTP/1.1
> Host: restheart_server:4443
> Authorization: Basic YTph
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Content-Length: 0
< Connection: close
<
* Closing connection 0
```

## Environment
OS ubuntu 16.04 under the two servers
mongodb 2.6.10
restheart 3.4.0

Any idea ?

Thanks

**Comment by ujibang** [comment]
that is your terminal dealing with the '

try

```
curl -k -u a:a https://restheart_server:4443/buildbot/slaves?filter='{"name":"abiref"}'
```

**Comment by ujibang** [comment]
Your curl command is not sending the curly brackets {} 

```
GET /buildbot/slaves?filter="name":"abiref" HTTP/1.1
```

**Comment by jmbeuken** [comment]
yes... 

but, you can see in the previous comment , I use  this command 

`curl -g -v -k -u a:a  https://restheart_server:4443/buildbot/slaves?filter={\"name\":\"abiref\"} `

and we can see in the output that the GET command is : 

`> GET /buildbot/slaves?filter={"name":"abiref"} HTTP/1.1`

why it doesn't work ? 

it seems that the JSON syntax  is correct...

**Comment by ujibang** [comment]
Which version of restheart are you using?

Try the latest one. In some previous releases we updated undertow with a version that requires the curly brackets to be encoded. We downgraded it to fix this issue. 

To check if this is the issue you can ask curl to encode the url like in the following example

```
curl -G --data-urlencode "filter={'from':'ujibang'}" https://beta.mrest.io/demo/messages
```

**Comment by jmbeuken** [comment]
restheart-3.4.0

ok ! it seems working : 

```
curl -k -u a:a -G --data-urlencode "filter={'name':'abiref'}" https://restheart_server:4443/buildbot/slaves

{"_embedded":[{"_id":{"$oid":"56f2a724ce87ed71f5d541f0"},"name":"abiref","brand":"HP DL360 G9","os":"CentOS 7.2","vendor":"intel","cpu":"2 x E5-2670 v3 @ 2.30GHz","core":48,"ram":32,"speed":"fast","max_builds":3,"builders":["abiref_gnu_5.3_openmpi","abiref_gnu_5.3_serial","abiref_gnu_5.3_debug","abiref_nag_6.2_openmpi","abiref_gnu_5.3_libxc"],"passwd":"xxxxxxx","reference":true,"active":true}],"_id":"slaves","_returned":1}
```
thank you...

now, I need to make GET from AngularJS ...

something like that : 

`var responsePromise=$http.get(URL_DB_PROXY+'/buildbot/slaves?filter={"name":"abiref"}');`

to be continued... ;-)

**Comment by ujibang** [comment]
Just use the following to encode the url

https://www.w3schools.com/jsref/jsref_encodeURI.asp

**Comment by jmbeuken** [comment]
Thanks !  everything working :-) 
Now, I can migrate from mongodb-rest to RESTHeart... : I need projection feature !

**Comment by ujibang** [comment]
by the way, I just pushed a change to set to true the undertow option ALLOW_UNESCAPED_CHARACTERS_IN_URL

it also avoids BAD REQUEST for requests with URL containing curly brackets
