### ISSUE TITLE
What is the negate operator for filter :  $not ? 

### ISSUE THREAD

**Issue by jmbeuken** [SoftInstigate/restheart#305]
I try to negate this expression  :  

`filter={"category": {"$regex":"(push|slow|merge)"} }`

i.e. keep "category" that do not contain "push or slow or merge"

I try something like that but with error : 

`filter={"$not":{ "$or":[{"category":"push"},{"category":"slow"},{"category":"merge"}] }}`

any idea ?

btw : what is the list of logical operators : $and and $or  only ?

I don't have hair on my head anymore. ;-)

thank you...

use restheart 3.4.1 & mongodb 2.6

**Comment by mkjsix** [comment]
This has not much to do with RESTHeart, it's about regular expressions and MongoDB's $regex operator. However, I think you should play with regular expressions negative lookahead, for example: https://www.regextester.com/94366

I cannot test, but something like this could be in the right direction (it depends on your input, I don't have a clue about it...):

`filter={"category": {"$regex":"^(?!push|slow|merge)([a-z0-9]+)$"} }`

I'd suggest to search for similar MongoDB questions on Stackoverflow.

**Comment by jmbeuken** [comment]
Thank you for your suggestions, it seems working :-) 
Concerning the logical operators, there are only $and and $or with RESTheart filter,  or I can use all operators found in MongoDB ?

**Comment by mkjsix** [comment]
In terms of queries you can use any MongoDB operator, plus aggregation pipelines and map reduce functions.

- https://restheart.org/learn/query-documents/
- https://restheart.org/learn/aggregations/

**Comment by jmbeuken** [comment]
ok, thanks

 but , can you explain why this filter is in error

`filter={"$not":{ "$or":[{"category":"push"},{"category":"slow"},{"category":"merge"}] }}`

while this works

`filter={ "$or":[{"category":"push"},{"category":"slow"},{"category":"merge"}] }`

thank you

**Comment by mkjsix** [comment]
what's the error?

**Comment by jmbeuken** [comment]
sorry , I updated my previous comment with the error...

**Comment by mkjsix** [comment]
Because that is the wrong syntax for the [$not operator](https://docs.mongodb.com/manual/reference/operator/query/not/):

```
$not
Syntax: { field: { $not: { <operator-expression> } } }
```

You should use the [$nor operator](https://docs.mongodb.com/manual/reference/operator/query/nor/) instead:

```
filter={ "$nor":[{"category":"push"},{"category":"slow"},{"category":"merge"}] }
```

**Comment by jmbeuken** [comment]
so simple  :-)
sorry for wasting your time,
thank you @mkjsix
