### ISSUE TITLE
Can not create index 

### ISSUE THREAD

**Issue by tatapm** [SoftInstigate/restheart#31]
Here is sample json:
{ "collectionId": 9999,
  "collectionStatus": {
          "id": 9999,
           "discoStatus": 4     
        },
   "strasse": "abc"
   }
1.Create index for collectionId field with request :/collection/_indexes/collectionId
==> Error:  "java.lang.NullPointerException", "  at org.restheart.handlers.indexes.PutIndexHandler.handleRequest(PutIndexHandler.java:62)"

2.How to index collectionStatus.discoStatus field?

Thanks

**Comment by ujibang** [comment]
You need to PUT /db/coll/_indexes/indexname

The following json


{ keys: {"collectionStatus.discoStatus": 1} }

**Comment by tatapm** [comment]
Yeah. It work as your solution b/c I missed json body for those requests.
Thanks
