### ISSUE TITLE
May I ask If I am able to get the response payload by using Put and Patch method

### ISSUE THREAD

**Issue by nazisangg** [SoftInstigate/restheart#310]
When I use Put and Patch method，It will return HTTP status code and an empty payload. Is there an way that I can get the updated doc as an payload? so that I don't need to use get method after put and patch.
## Steps to Reproduce

1.
2.
3.

**Comment by ujibang** [comment]
You can use the [WriteResultTransformer](https://github.com/SoftInstigate/restheart/blob/master/src/main/java/org/restheart/metadata/transformers/WriteResultTransformer.java)

[Transformers](https://restheart.org/learn/request-transformers/) allow to transform the request and the response for instance adding the new/updated document.

WriteResultTransformer uses `RequestContext.getDbOperationResult().getOldData()` and `RequestContext.getDbOperationResult().getNewData()` to get the old and updated versions of the document and add them to the response body in the `oldData` and `newData` sub-documents.
