### ISSUE TITLE
Question > How to use cursor.hint() through RESTHeart?

### ISSUE THREAD

**Issue by Musikolo** [SoftInstigate/restheart#316]
Hi,

I've got a question and I would appreciate some guidance on this regard. I've got a query that only performs well when using the [`cursor.hint()`](https://docs.mongodb.com/v3.4/reference/method/cursor.hint/) method. If I don't use it, MongoDB tends to use the wrong index, which, to the point I've been look into, it doesn't perform as good it should.

Although I have searched in the [documentation](https://restheart.org/learn/), I haven't found anything that allows me to do so.

How could I `hint` MongoDB to use a specific index through RESTHeart?

Thank you!

**Comment by ujibang** [comment]
Unfortunately `hint` is not available with restheart.

We will implement it in the next release. Would it work for you if we allow specifying it via a query parameter? For instance:

```
GET /db/coll?hint={"idx":1}
```

**Comment by Musikolo** [comment]
Yes, that should work perfectly. In particular, the index I need to use would be something like this: 
```
GET /db/coll?hint={"field1":1, "field2":-1}
```

However, in order to implement all the functionality of `hint`, I don't know if it would also be possible to support something like this:
```
GET /db/coll?hint="my_index_name"
```
or
```
GET /db/coll?hintname="my_index_name"
```

Thank you! ;-)

**Comment by mkjsix** [comment]
@ujibang set to be included in 3.6.0 (to be released end of 2018)

**Comment by ujibang** [comment]
@Musikolo just pushed c6399b2f3c2e46eeef6bdbe6d1f3b4f4eb4c4664 that includes support for `hint` query parameter.

I also added documentation about this at https://restheart.org/learn/query-documents/#hint and [two integration tests](https://github.com/SoftInstigate/restheart/commit/b8f795c8e548b5d6f2d411e598c5693be27babb8#diff-781bffd27e34e91e789c699696825317)

Note that I didn't find a way to specify the index by name with the java driver. Only specifying the indexed fields is supported.

I'm closing this, please review and reopen if you find any problem. 

You can try it on the[ latest snapshot](https://oss.sonatype.org/content/repositories/snapshots/org/restheart/restheart/3.6.0-SNAPSHOT/) or using docker (the image latest tag is automatically updated on each commit).

**Comment by Musikolo** [comment]
Awesome!

Thank you so much!

**Comment by mkjsix** [comment]
This is in [release 3.6.0](https://github.com/SoftInstigate/restheart/releases/tag/3.6.0).
