### ISSUE TITLE
Eliminate default authentication

### ISSUE THREAD

**Issue by fdrsuisse** [SoftInstigate/restheart#320]
Hi, in order to use the APIs the default authentication in the file
etc/security.yml  is admin/changeit , 
according to the link https://softinstigate.atlassian.net/wiki/spaces/RH/pages/13369378/Enable+and+Configure+Security
Is it possible to eliminate the default authentication ?
Best Regards,
Francesco

**Comment by ujibang** [comment]
if you want no authorization (all requests are executed) just comment out `idm` and `am` sections from configuration file

**Comment by fdrsuisse** [comment]
Hi Andrea, many thanks for your support. It works. You can close the issue.
Best Regards,
Francesco
