### ISSUE TITLE
Throwing HTTP 417 when key is duplicate in POST

### ISSUE THREAD

**Issue by johnnywiller** [SoftInstigate/restheart#330]
## Expected Behavior
RH should throw a better HTTP code when facing an duplicate key error. For example a 400 BAD REQUEST or 409 CONFLICT (better IMHO).

## Current Behavior
Currently it's returning HTTP 417. It's true that RH returns a good message that tells what happened, but even with this message, some misunderstood could happen. If the person is seeing only the codes, it could end up very confusing, because HTTP 417 is a non usual REST error. 

## Context
In my case I was using a HTTP lib that didn't show the response body. I took some good time to discover it was duplicate key.
Also, if the user logs all the errors code returned by the API, this is an unusual code compared to other API's.

## Environment
RH 3.7 
Mongo 4

## Steps to Reproduce
Create an unique index in MongoDB of any field and send two POST requests with same value in this field.
  
## Possible Implementation
Change  the returning code in method updateDocument of DAOUtils class

**Comment by mkjsix** [comment]
I tend to agree with you @johnnywiller 

Accordingly to https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/417

> The HTTP 417 Expectation Failed client error response code indicates that the expectation given in the request's Expect header could not be met.

It means the 417 error code is a very specific one, related to the presence of the `Expect` HTTP header:

> The Expect HTTP request header indicates expectations that need to be fulfilled by the server in order to properly handle the request.

Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect

Which doesn't seem to be our case.

In RESTHeart the `HttpStatus.SC_EXPECTATION_FAILED` (error 417) in DAOUtils.java class is raised when the `allowUpsert` flag is `true` and we receive a `1100` error code from MongoDB ("E11000 duplicate key error index").

I think replacing the 417 code with a HTTP 409 CONFLICT would be the right solution.

**Comment by mkjsix** [comment]
The commit is on master and will be available from v. 3.8.0, which could be released this week.

**Comment by mkjsix** [comment]
Hi @johnnywiller,
We have released RESTHeart [3.8.0](https://github.com/SoftInstigate/restheart/releases/tag/3.8.0) with this change.

**Comment by johnnywiller** [comment]
cool :-)
