### ISSUE TITLE
security.yml : add ldap authentication

### ISSUE THREAD

**Issue by grostarin** [SoftInstigate/restheart#341]
Our LDAP don't authorize anonymous authentication.
So i cannot user ldap to authenticate restheart users

## Expected Behavior
Admin is able to specify ldap username/password to connect to ldap server.

## Current Behavior
No ldap authentication is managed.

## Environment
Restheart 3.8.1
mongo 3.6

## Steps to Reproduce
/

## Possible Implementation

After

```
## Config for AD Identity Manager
#adim:
#    - domainControllers: ldap://eastdc.example.com
#      principalNameSuffixes: corp.example.com,example.com
```

Add lines

```
#      authentication: true # default = false
#      username: my_ldap_user_dn
#      password: my_ldap_user_password
```

**Comment by mkjsix** [comment]
Hi @grostarin 
We added a very rough support for [ActiveDirectory](https://restheart.org/learn/ldap-authentication/) a long time ago, by including an external contribution, but at present we neither support it nor any LDAP authentication in the free version of the product, as we consider that an enterprise-only feature which could be implemented and supported in the next major release of the [Enterprise Edition](https://restheart.org/license), whenever a paying customer actually asks for it.
