### ISSUE TITLE
security.yml : using mustache like restheart.yml

### ISSUE THREAD

**Issue by grostarin** [SoftInstigate/restheart#342]
Add support of mustache parameters in security.yml like in restheart.yml

## Expected Behavior
When restheart admin uses mustache parameter in security.yml, mustache is replaced by a value like it's done for restheart.yml (using environment variables for example)

## Current Behavior
We could not use mustache parameter

## Context
Our organisation prefers starting docker container with environment variable and without configuration file in file system.
Liked to #341 usage

## Environment
Restheart 3.8.1
mongo 3.6

## Steps to Reproduce
/

## Possible Implementation
Use same algorithm as used for restheart.yml

**Comment by ujibang** [comment]
@mkjsix starting from RESTHeart 4, security will be delegated to [uIAM](https://github.com/softInstigate/uiam) 

This request should be implemented in uIAM, supporting configuration files with mustache parameters.

**Comment by ujibang** [comment]
I have copied this issue to uIAM project https://github.com/SoftInstigate/uiam/issues/1

closing this one.
