### ISSUE TITLE
How to update a single document

### ISSUE THREAD

**Issue by rjacobs91** [SoftInstigate/restheart#35]
Hi guys,
So I can make get requests and manipulate data really easily but making patch/post updates is not working properly. For example, if I make a patch request to my document url.
with the following content-type - application/json body the doc will update:
{"filter1":"2"}
however, if i try to update the value again there is a 409 error. With a patch surely this you should be able to update any number of times

**Comment by rjacobs91** [comment]
This was because the etag changes after first update. DOCUMENTATION ON WEBSITE REALLY NEEDED

**Comment by mkjsix** [comment]
ETag's documentation is in progress right now: https://softinstigate.atlassian.net/wiki/display/RH/ETags
Any feedback would be greatly appreciated, thank you!
