### ISSUE TITLE
Type-Converting will append type as a filed in document.

### ISSUE THREAD

**Issue by StevenJSun** [SoftInstigate/restheart#350]
## Expected Behavior

1、When I GETting Documents， some data will return type-conserving JSON, like data[0]. Is there a way or configuration to make API retrun all documents just like data[1]?
[{'uid': {'$numberLong': '5887391606'}},  # data[0]
 {'uid': 2084824280},  # data[1]
 {'uid': {'$numberLong': '5668990174'}}  #  data[2]
]

## Steps to Reproduce

1.
2.
3.

**Comment by ujibang** [comment]
java int type maximum value is 2147483648; the `uid= 5887391606` is therefore parsed as a Long. Storing the long value in mongodb results in `{'$numberLong': '5887391606'}`

I'm not sure if this is a bug. I'll look at it.

References https://restheart.org/docs/representation-format/#bson-types and https://docs.mongodb.com/manual/reference/mongodb-extended-json/#numberlong

**Comment by StevenJSun** [comment]
I think it is not a problem, we want to get the repsonse json like  {'uid': 2084824280} but not the format: {'uid': {'$numberLong': '5887391606'}, of course, the 'uid' is long type. so it there any config for it?

**Comment by StevenJSun** [comment]
@ujibang @mkjsix does this problem solved ? we want to get the repsonse json like {'uid': 2084824280} but not the format: {'uid': {'$numberLong': '5887391606'}, of course, the 'uid' is long type. so it there any config for it?

**Comment by ujibang** [comment]
Hi @StevenJSun 

as explained this is an issue with the MongoDB java driver parsing logic.

We are working at it. The point is that RESTHeart is using the default JsonWriterSettings which is EXTENDED and produces that output for java long values.

We are planning to add a query parameter to the request to allow selecting the JsonWriterSettings as EXTENDED, RELAXED and SHELL (default EXTENDED).

The RELAXED mode will output what you are expecting.

**Comment by StevenJSun** [comment]
@ujibang Okay, and what about the release time for this issue fixed ?

**Comment by ujibang** [comment]
Hi @StevenJSun 

this is a "feature request" and we added it to the roadmap. 

I expect it to be included in next release of RESTHeart, probably in September. However we don't commit on a release date.

**Comment by mkjsix** [comment]
@StevenJSun a clarification on the above reply from @ujibang: this is going to be changed first in the [Commercial Edition](https://restheart.org/editions/) in September, then it will be moved in the open source edition, probably in October or November. We commit on specific dates only for Enterprise customers with an active commercial subscription. 

Of course, meanwhile anybody can open a PR and contribute a solution (with tests and a bit of documentation...) to the open source edition.
