### ISSUE TITLE
Reserved field _uptime was filtered out from the request?

### ISSUE THREAD

**Issue by StevenJSun** [SoftInstigate/restheart#352]
when we write data to mongodb, the write request returns the following response：
'_warnings': ['Reserved field _uptime was filtered out from the request']

Is there a way to config a whitelist to let "_uptime" pass?

**Comment by ujibang** [comment]
Hi @StevenJSun ,

unfortunately RESTHeart filters out all fields whose name starts with _

I think we can relax this constraint since actual reserved fields are few (e.g. __etag_ and __links_).

I will add this to our backlog.

**Comment by StevenJSun** [comment]
@ujibang thanks, we will use another solution to work around.
