### ISSUE TITLE
How to config MongoDB connection pool for RestHeart?

### ISSUE THREAD

**Issue by StevenJSun** [SoftInstigate/restheart#353]
When request restheart mongodb service ,it returns the following response:

{'exception': 'java.lang.RuntimeException', 'exception message': 'com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=10.60.233.249:24000, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]'}], 'http status code': 500, 'http status description': 'Internal Server Error', 'message': 'Error handling the request, see log for more information'}

## Expected Behavior

the request should returns right response, 200 httpcode.

## Environment

CentOS 7
RESTHeart: 4.0.0
MongoDB: 4.0.6

## Steps to Reproduce

1.
2.
3.

## Possible Implementation

I don't know how to config the mongodb connection pool for RestHeart, and  how RestHeart manage the mongodb connection pool, or Restheart use a new mongodb connection for every restheart request ?

**Comment by ujibang** [comment]
you configure the connection setting the [MongoURI](https://docs.mongodb.com/manual/reference/connection-string/) in the yml configuration file:

```
#### MongoDB

##  MongoDb Connection

# Set the MongoDb connection using a Mongo Client URI.
#
# The format of the URI is:
#    mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]
#
# Use The URI query parameter 'authSource' to specify the authetication database:
# mongodb://user:secret@127.0.0.1/?authSource=authdb
#
# More information at http://api.mongodb.org/java/current/com/mongodb/MongoClientURI.html

mongo-uri: {{{mongo-uri}}}
```

Note that the default configuration file `restheart-platform-core.yml` sets the `mongo-uri` through a parameter. In this case define the uri in the properties file or via env parameters. More info at [configuration doc page](https://restheart.org/docs/configuration/)

The MongoDb driver handles a connection pool. You can set the options to control the pool: maxPoolSize and minPoolSize as following

```
mongo-uri: mongodb://127.0.0.1/? maxPoolSize=200
```

**Comment by StevenJSun** [comment]
@ujibang I had add the maxPoolSize=200 in the MongoDB URL, but when  execute read or write data  requests by the relative restheart apis , the mongodb connection  will be used out and cannot connect mongodb,  our mongodb server's connnection pool is 2000。So I want to know how restheart to manage the mongodb connection pool ? Is there any config for Restheart or MongodB server ?
