### ISSUE TITLE
How to start two or more Restheart instances for different dbs in one machine ? 

### ISSUE THREAD

**Issue by StevenJSun** [SoftInstigate/restheart#354]
We want to start two or more restheart instances for different mongodb databases in one machine node, so how to config restheart?

## Steps to Reproduce

1.
2.
3.

**Comment by mkjsix** [comment]
You just need to crete as many configuration property files as you need and assign a different `http-port` number to each one. Start each RH instance by pointing to its own configuration.

https://restheart.org/docs/configuration/

**Comment by StevenJSun** [comment]
@mkjsix thanks, the solution works now.
