### ISSUE TITLE
How RestHeart manage the mongodb connection pool and improve the performance? 

### ISSUE THREAD

**Issue by StevenJSun** [SoftInstigate/restheart#356]
I have some questions for mongodb connection pool:

1、 I have added the maxPoolSize=200 parameter in the MongoDB URL, but when execute read or write requests by the restheart rest apis , the mongodb connection will be used out and cannot connect mongodb, our mongodb server's connnection pool is 2000。So I want to know how restheart to manage the mongodb connection pool ? Is there any config for Restheart or MongoDB server? 

2、 I use nginx to config load balancer for Restheart, and every Restheart Mongodb-URi 's maxPoolSize is 200 and minPoolSize is 150, If I config 20 Restheart instances, then the total connections is 4000, but our mongodb server's default connection pool is 2000, so the actual connection size for every restheart instance is 150 or 100 ? 

3、I found two config parameters: 
#suggested value: core*2
io-threads: 4
#suggested value: core*16
worker-threads: 16
how the two configs are used ? 
does every worker-thread have a request queue and if the current request hasn't completed ,then the following request will be added into the queue and then waits to be executed ? And If I request the queued request, what about the request's response? 
So is there any config to improve the performance？ 

## Environment

MongoDB 4.0.6
RestHeart 4.0.0

## Steps to Reproduce

1.
2.
3.

**Comment by ujibang** [comment]
**1 connection pool**

RESTHeart manages the connection pool via the MongoDB official java driver. It is the driver that handles the connection pool transparently. You can better understand how it works reading the MongoDB official documentation. 

There are some MongoURI query parameters to control the pool:

|param|description|
|-|-|
maxPoolSize | The maximum number of connections in the connection pool. The default value is 100.
minPoolSize | The minimum number of connections in the connection pool. The default value is 0.NOTEThe minPoolSize option is not supported by all drivers. For information on your driver, see the drivers documentation.
maxIdleTimeMS | The maximum number of milliseconds that a connection can remain idle in the pool before being removed and closed.This option is not supported by all drivers.

**connection size**

if you have 20 RESTHeart instances and MongoDB server max connection is 2000, that I would set 
maxPoolSize to 99 (assuming that there are no more MongoDB clients): 99*20=1980 (just to have 20 connections available for other clients)!

note that if you get `MongoSocketOpenException`, this might be due a pooled connection being closed by the server. It can be due to network issues. You can try to set the `maxIdleTimeMS` query parameters to fix that.

**3 threads**

io-threads and working-threads are key parameters for performance. just follow the suggested values rules for optimal settings.

you can read more in [undertow documentation](http://undertow.io/undertow-docs/undertow-docs-2.0.0/index.html)

**Comment by StevenJSun** [comment]
@ujibang this is the restheart startup logs, are there any config advice for performance promotion?

 Initializing MongoDB connection pool to [10.60.233.249:24000] with options MongoClientOptions{description='null', applicationName='null', compressors='[]', readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, fsync=null, journal=null, retryWrites=false, readConcern=com.mongodb.ReadConcern@0, codecRegistry=org.bson.codecs.configuration.ProvidersCodecRegistry@8a906b2, serverSelector=null, clusterListeners=[], commandListeners=[], minConnectionsPerHost=0, maxConnectionsPerHost=200, threadsAllowedToBlockForConnectionMultiplier=5, serverSelectionTimeout=30000, maxWaitTime=120000, maxConnectionIdleTime=0, maxConnectionLifeTime=0, connectTimeout=10000, socketTimeout=0, socketKeepAlive=true, sslEnabled=false, sslInvalidHostNamesAllowed=false, sslContext=null, alwaysUseMBeans=false, heartbeatFrequency=10000, minHeartbeatFrequency=500, heartbeatConnectTimeout=20000, heartbeatSocketTimeout=20000, localThreshold=15, requiredReplicaSetName='null', dbDecoderFactory=com.mongodb.DefaultDBDecoder$1@2da59753, dbEncoderFactory=com.mongodb.DefaultDBEncoder$1@5629510, socketFactory=null, cursorFinalizerEnabled=true, connectionPoolSettings=ConnectionPoolSettings{maxSize=200, minSize=0, maxWaitQueueSize=1000, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[]}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, keepAlive=true, receiveBufferSize=0, sendBufferSize=0}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=20000, readTimeoutMS=20000, keepAlive=true, receiveBufferSize=0, sendBufferSize=0}}

**Comment by StevenJSun** [comment]
@ujibang are there any config parameters for MongoDB Server to promote the process request speed ? We found that sometimes executing a write request in Our MongoDB Server will take about 20-40 seconds.

**Comment by ujibang** [comment]
20 seconds for a single write request is not normal at all unless monodb is under heavy load.

In our experience, when you have performance issues the bottleneck is always monodb since restheart is very lightweight. 

In this case you need to scale up mongodb using more powerful hardware or sharding.

In case you are just testing your installation and you have such poor performance with a single request you should check your network. 

However since you are seeing up a cluster with 20 restheart instances I guess you have a really high load.

Can you clarify the load conditions?

**Comment by StevenJSun** [comment]
@ujibang I don't know why when execute read requests every three times ,then get the follow error,

the mongodb URI is : mongodb://bddasopr:bddasopr2019@10.50.84.230:24000,10.50.84.231:24000/bddas?readPreference=secondary&maxStalenessSeconds=120&maxIdleTimeMS=60000&socketTimeoutMS=60000


17:36:02.448 [XNIO-1 task-1] INFO  o.r.handlers.RequestLoggerHandler - GET http://10.60.224.97:8888/bddas from /10.106.169.134:59601 => status=500 elapsed=9ms contentLength=109
 17:36:03.335 [XNIO-1 task-1] INFO  o.r.handlers.RequestLoggerHandler - GET http://10.60.224.97:8888/bddas from /10.106.169.134:59601 => status=200 elapsed=34ms contentLength=28
 17:36:04.163 [XNIO-1 task-1] INFO  o.r.handlers.RequestLoggerHandler - GET http://10.60.224.97:8888/bddas from /10.106.169.134:59601 => status=200 elapsed=8ms contentLength=28
 17:36:05.031 [XNIO-1 task-1] INFO  o.r.handlers.RequestLoggerHandler - GET http://10.60.224.97:8888/bddas from /10.106.169.134:59601 => status=200 elapsed=10ms contentLength=28
 17:36:08.474 [XNIO-1 task-1] ERROR org.restheart.handlers.ErrorHandler - Error handling the request
 com.mongodb.MongoSocketReadException: Exception receiving message
	at com.mongodb.internal.connection.InternalStreamConnection.translateReadException(InternalStreamConnection.java:559)
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
17:36:08.477 [XNIO-1 task-1] INFO  o.r.handlers.RequestLoggerHandler - GET http://10.60.224.97:8888/bddas from /10.106.169.134:59601 => status=500 elapsed=10ms contentLength=109
 17:36:11.034 [XNIO-1 task-1] INFO  o.r.handlers.RequestLoggerHandler - GET http://10.60.224.97:8888/bddas from /10.106.169.134:59601 => status=200 elapsed=42ms contentLength=28
 17:36:11.702 [XNIO-1 task-1] INFO  o.r.handlers.RequestLoggerHandler - GET http://10.60.224.97:8888/bddas from /10.106.169.134:59601 => status=200 elapsed=10ms contentLength=28
 17:36:12.372 [XNIO-1 task-1] INFO  o.r.handlers.RequestLoggerHandler - GET http://10.60.224.97:8888/bddas from /10.106.169.134:59601 => status=200 elapsed=9ms contentLength=28
 17:36:13.045 [XNIO-1 task-1] ERROR org.restheart.handlers.ErrorHandler - Error handling the request
 com.mongodb.MongoSocketReadException: Exception receiving message
	at com.mongodb.internal.connection.InternalStreamConnection.translateReadException(InternalStreamConnection.java:559)
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
17:36:13.047 [XNIO-1 task-1] INFO  o.r.handlers.RequestLoggerHandler - GET http://10.60.224.97:8888/bddas from /10.106.169.134:59601 => status=500 elapsed=8ms contentLength=109
 17:36:13.834 [XNIO-1 task-1] INFO  o.r.handlers.RequestLoggerHandler - GET http://10.60.224.97:8888/bddas from /10.106.169.134:59601 => status=200 elapsed=33ms contentLength=28
 17:36:17.734 [XNIO-1 task-1] INFO  o.r.handlers.RequestLoggerHandler - GET http://10.60.224.97:8888/bddas from /10.106.169.134:59601 => status=200 elapsed=10ms contentLength=28
 17:36:18.422 [XNIO-1 task-1] INFO  o.r.handlers.RequestLoggerHandler - GET http://10.60.224.97:8888/bddas from /10.106.169.134:59601 => status=200 elapsed=10ms contentLength=28
 17:36:19.100 [XNIO-1 task-1] ERROR org.restheart.handlers.ErrorHandler - Error handling the request
 com.mongodb.MongoSocketReadException: Exception receiving message
	at com.mongodb.internal.connection.InternalStreamConnection.translateReadException(InternalStreamConnection.java:559)
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
17:36:19.103 [XNIO-1 task-1] INFO  o.r.handlers.RequestLoggerHandler - GET http://10.60.224.97:8888/bddas from /10.106.169.134:59601 => status=500 elapsed=8ms contentLength=109

**Comment by ujibang** [comment]
please share you replica set configuration. I suspect you have a secondary member misconfigured.

**Comment by StevenJSun** [comment]
@ujibang our replica set config is as follows:
master:
systemLog:
   destination: file
   path: /qhdba/mongodb/mg24000/log/mg.log
   verbosity: 0
   component:
      accessControl: 
         verbosity: -1
      index:
         verbosity: -1
      network:
         verbosity: -1
      query:
         verbosity: -1      
      replication:
         verbosity: -1
      sharding:
         verbosity: -1
      storage:
         verbosity: -1
         journal: 
            verbosity: -1      
   logAppend: true 
   logRotate: rename
processManagement:
   fork: true
   pidFilePath: /qhdba/mongodb/mg24000/etc/mg.pid
net:
   bindIp: 127.0.0.1,10.50.84.230
   port: 24000
   maxIncomingConnections: 2000
###########################config WT start######################## 
storage:
   dbPath: /qhdba/mg24000/data
   directoryPerDB: true
   syncPeriodSecs: 60
   #indexBuildRetry: false
   journal:
      enabled: true
   engine: wiredTiger
   wiredTiger:
      engineConfig:
         cacheSizeGB: 4
         directoryForIndexes: true
         statisticsLogDelaySecs: 0
      collectionConfig:
         blockCompressor: zlib
      indexConfig:
         prefixCompression: true
###########################config WT end######################## 
operationProfiling:
   slowOpThresholdMs: 100
   mode: slowOp
setParameter:
   enableLocalhostAuthBypass: false
#security:
 #  clusterAuthMode: keyFile
 #  keyFile: /qhdba/mongodb/mg24000/etc/mg.key
 #  authorization: enabled
################replicaset start##############################
replication:
   replSetName: bddas
   oplogSizeMB: 4000
################replicaset end##############################
################audit start##############################
auditLog:
    destination: file
    format: JSON
    path: /qhdba/mongodb/mg24000/log/auditLog.json
################audit end################################

=================================================
slave:
systemLog:
   destination: file
   path: /qhdba/mongodb/mg24000/log/mg.log
   verbosity: 0
   component:
      accessControl: 
         verbosity: -1
      index:
         verbosity: -1
      network:
         verbosity: -1
      query:
         verbosity: -1      
      replication:
         verbosity: -1
      sharding:
         verbosity: -1
      storage:
         verbosity: -1
         journal: 
            verbosity: -1      
   logAppend: true 
   logRotate: rename
processManagement:
   fork: true
   pidFilePath: /qhdba/mongodb/mg24000/etc/mg.pid
net:
   bindIp: 127.0.0.1,10.50.84.231
   port: 24000
   maxIncomingConnections: 2000
###########################config WT start######################## 
storage:
   dbPath: /qhdba/mg24000/data
   directoryPerDB: true
   syncPeriodSecs: 60
   #indexBuildRetry: false
   journal:
      enabled: true
   engine: wiredTiger
   wiredTiger:
      engineConfig:
         cacheSizeGB: 4
         directoryForIndexes: true
         statisticsLogDelaySecs: 0
      collectionConfig:
         blockCompressor: zlib
      indexConfig:
         prefixCompression: true
###########################config WT end######################## 
operationProfiling:
   slowOpThresholdMs: 100
   mode: slowOp
setParameter:
   enableLocalhostAuthBypass: false
#security:
 #  clusterAuthMode: keyFile
 #  keyFile: /qhdba/mongodb/mg24000/etc/mg.key
 #  authorization: enabled
################replicaset start##############################
replication:
   replSetName: bddas
   oplogSizeMB: 4000
################replicaset end##############################
################audit start##############################
auditLog:
    destination: file
    format: JSON
    path: /qhdba/mongodb/mg24000/log/auditLog.json
################audit end################################

**Comment by ujibang** [comment]
see https://docs.mongodb.com/manual/reference/replica-configuration/ 

from the mongo shell retrieve the configuration as following:

> You can access the configuration of a replica set using the rs.conf() method or the replSetGetConfig command.

**Comment by StevenJSun** [comment]
@ujibang
our replica set config is as follows:

 {
	"_id" : "bddas",
	"version" : 3,
	"protocolVersion" : NumberLong(1),
	"writeConcernMajorityJournalDefault" : true,
	"members" : [
		{
			"_id" : 0,
			"host" : "10.50.84.230:24000",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {
				
			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		},
		{
			"_id" : 1,
			"host" : "10.50.84.231:24000",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {
				
			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		},
		{
			"_id" : 2,
			"host" : "10.50.84.232:24000",
			"arbiterOnly" : true,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 0,
			"tags" : {
				
			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		}
	],
	"settings" : {
		"chainingAllowed" : true,
		"heartbeatIntervalMillis" : 2000,
		"heartbeatTimeoutSecs" : 10,
		"electionTimeoutMillis" : 10000,
		"catchUpTimeoutMillis" : -1,
		"catchUpTakeoverDelayMillis" : 30000,
		"getLastErrorModes" : {
			
		},
		"getLastErrorDefaults" : {
			"w" : 1,
			"wtimeout" : 0
		},
		"replicaSetId" : ObjectId("5d43d9c351e35e8e6968a14d")
	}
}

**Comment by StevenJSun** [comment]
@ujibang ，the connection reset probelm is resolved now. the connection ruleo of the firewall between our rest service node and mongodb node is misconfigured.
