### ISSUE TITLE
Java 8 compatibility with restheart 4.0

### ISSUE THREAD

**Issue by christiangroth** [SoftInstigate/restheart#361]
We want to update from restheart 3.10.1 to 4.0.0 and our project is still on Java 8. We can't move to Java 11 yet due to dependencies with other projects, but also can't update to restheart 4.0 using Java 8 because it's compiled with Java 11 only.

`
home/groth/dev/src/caas/caas-rest-api/src/main/java/com/espirit/caas/restheart/metrics/MongoHealthCheck.java:6: error: cannot access MongoDBClientSingleton
import org.restheart.db.MongoDBClientSingleton;
                       ^
  bad class file: /home/groth/.gradle/caches/modules-2/files-2.1/org.restheart/restheart/4.0.0/97ae5e8ba6c455e5f770d7e722c7525c749a071a/restheart-4.0.0.jar(org/restheart/db/MongoDBClientSingleton.class)
    class file has wrong version 55.0, should be 52.0
`

Are there any plans to be Java 8 compatible in the future or is this dropped with v4.0?

**Comment by ujibang** [comment]
restheart 4.0 uses java 11 and we have no plan to support old java releases..
