### ISSUE TITLE
Create missing database and /or collection on document PUT

### ISSUE THREAD

**Issue by chwal** [SoftInstigate/restheart#362]
## Expected Behavior
PUT request with a valid JSON-Body on 
_https://domain.tld/database/collection/document_
should create the **database**, **collection** and the **document** itself if they dont exist.

## Current Behavior
Restheart responds with code 404 on given database.

## Context
This is affecting our restheart client software, where this logic needs to be implemented over and over again.

## Environment
RESTHeart version 3.10.1

## Steps to Reproduce
1. See Expected Behavior

**Comment by ujibang** [comment]
Won't implement. 

Although it would simplify some specific use cases it would make much harder dealing with security permissions.

Also I don't find it compliant with REST paradigm. A verb on a resource would have side effects on parent resources.

It is much easier handling this requirement client side.
