### ISSUE TITLE
error in reading config file under windows

### ISSUE THREAD

**Issue by AmmRage** [SoftInstigate/restheart#365]
encounter exception: 
Exception in thread "main" java.lang.IllegalArgumentException: Illegal character in opaque part at index 2

## Expected Behavior
load config file

## Current Behavior
throw exception

## Context
the exception thrown when start restheart at standalone jar file

## Environment
window 10 pro 64 bit
restheart 4.1.0
mongodb 4.0.3

## Steps to Reproduce
1. download restheart 4.1.0 and run with  as the simplest scenario specifying config and property file.

## Possible Implementation
check the platform,  if it's windows replace '\\'  to '/' in file path before new DefaultMustacheFactory().compile(configFile);

**Comment by mkjsix** [comment]
Hi @AmmRage 

Could please tell us how you are passing the configuration from the command line? The path is coming from there.

Besides I can't find a reference in the source code to the line you mentioned `DefaultMustacheFactory().compile(configFile);`

I only have `Mustache m = new DefaultMustacheFactory().compile(CONFIGURATION_FILE.toString());`, line 216 of Bootstrapper.java

A more complete Java stacktrace will help us identifying the issue.

**Comment by mkjsix** [comment]
Issue reproduced, we'll fix it in 4.1.2 which will be released next week.
