### ISSUE TITLE
Auth-Token not present in the Get method response header

### ISSUE THREAD

**Issue by shireefadel** [SoftInstigate/restheart#368]
The Get method is not exposing the Auth-Token while using CORS 

I have an angular 8 application, while creating a get request ..  the response not containing the 
Auth-Token ... but i's exists if I make the request using any testing tool

_by the way it was working with restheart 3_

**Comment by ujibang** [comment]
Cannot reproduce. Suspect a misconfiguration, checking with @shireefadel

**Comment by shireefadel** [comment]
can you please reproduce it with a simple angular 8 client

**Comment by ujibang** [comment]
it is more a question on how to get the response header with angular and not an issue with restheart, the `Auth-Token` is correctly returned
