### ISSUE TITLE
Adding DB users

### ISSUE THREAD

**Issue by bogdancioroianu** [SoftInstigate/restheart#37]
Hi, 
I am trying to add new MongoDB users using the REST interface but I couldn't make it work and I always receive a Forbidden message with the "reserved resource" description. I am using a high privilege Mongo user into the restheart.yml to connect to the DB.

Is there anyway to make this work/available?

Thanks,
Bogdan

**Comment by ujibang** [comment]
Hi Bodgan,

as a security restriction, system tables cannot be accessed from restheart: you cannot create db users from restheart, this is supposed to be done at configuration time.

restheart uses its own identity and access managers to allow users accessing dbs, collections and documents. have a look at http://restheart.org/docs/security.html for more information.

**Comment by bogdancioroianu** [comment]
Thanks
