### ISSUE TITLE
Arabic characters not working well with V4

### ISSUE THREAD

**Issue by shireefadel** [SoftInstigate/restheart#370]
I have some names written in Arabic, it was working good in version 3 but now it's returning as gibberish instead 
## Expected Behavior

Arabic characters to be displayed correctly 

## Current Behavior

Gibberish characters returned.
"�������� ��������������"

## Environment
RH 4 installed on ubuntu 16 server with mongo db 4, 
the front-end is angular
<img width="767" alt="gibbresh arabic 2" src="https://user-images.githubusercontent.com/13928689/70887698-9f640b00-1fef-11ea-9448-6c9940101c65.png">
<img width="759" alt="gibbresh arabic 1" src="https://user-images.githubusercontent.com/13928689/70887706-a559ec00-1fef-11ea-9f41-f37656615850.png">

**Comment by ujibang** [comment]
Add the option `file.encoding=UTF-8 ` to the java command that starts RESTHeart as  follows:

```
$ java -Dfile.encoding=UTF-8 -jar restheart-platform-core.jar etc/restheart-platform-core.yml -e etc/default.properties
```
  
let us know if this fixes your issue

**Comment by shireefadel** [comment]
Yes -Dfile.encoding=UTF-8 did solve the problem, thanks
