### ISSUE TITLE
All requests to getRoles plugin are Forbidden

### ISSUE THREAD

**Issue by shireefadel** [SoftInstigate/restheart#371]
Any request to the plugin getRoles is returning 403 Forbidden However the user name in the Authentication header is matching the user in the url 
## Expected Behavior

An authenticated request to /_logic/roles/{uid} to return 200 OK
An unauthenticated request to /_logic/roles/{uid} to return 401 Unauthorized

## Current Behavior

All requests to  /_logic/roles/{uid} are returning 403 Forbidden

## Environment
MongoDB 4, Ubuntu server 16 with RH 4

<img width="1306" alt="getroles" src="https://user-images.githubusercontent.com/13928689/70888189-c707a300-1ff0-11ea-95ee-68c65d961f1f.png">

**Comment by ujibang** [comment]
In RESTHeart v4 the URI of getRoles plugin is `/roles/{uid}`

check all differences in configuration between v3 and v4 in [upgrate to v4](https://restheart.org/docs/upgrade-to-v4/#default-configuration) doc page

**Comment by shireefadel** [comment]
Does it require any secuirty predicate configuration?

**Comment by shireefadel** [comment]
Yes, it works fine now , Thanks
