### ISSUE TITLE
Trial email missing download link

### ISSUE THREAD

**Issue by Wdestroier** [SoftInstigate/restheart#378]
Trial email missing download link

## Expected Behavior

Email should have the download link

## Current Behavior

The email tells that the download link is at https://restheart.org/docs/setup/ and https://restheart.org/docs/setup/ says that it is in the email

**Comment by ujibang** [comment]
the download link is https://download.restheart.com/restheart-platform-4.1.14.zip

In the email, it is in the top right corner of header. can you please confirm it is there?

**Comment by mkjsix** [comment]
Could you please tell us which email client are you using ? I’ve seen layout problems with Apple Mail.

**Comment by Wdestroier** [comment]
@ujibang thank you

**Comment by Wdestroier** [comment]
@mkjsix Windows Email
![prtsc](https://user-images.githubusercontent.com/14764307/74334011-d9475880-4d77-11ea-9de2-9d8907ae35b7.png)
