### ISSUE TITLE
Search document by date using collection filter

### ISSUE THREAD

**Issue by djaswal** [SoftInstigate/restheart#38]
Hey,
  I was wondering if its possible to search the document using date (iso string or epoch time) through uri?

example:
http://somedomain.com/somecollection?filter={'date':'1436911606420'}

Thanks,

**Comment by ujibang** [comment]
Sure you can!

The filter query parameter can be any mongodb query using any operator.

For instance you can do the following for a range date filter:

http://somedomain.com/somecollection?filter="{'$and':[{'date':{'$ge': START-DATE}},{'date':{ $le:END-DATE}}]}"

Note also that mongodb data format is bson, which includes a date type. In this case you do:

{'date':{'$date':value}}

See http://restheart.org/docs/resource-representation-format.html for more info.
