### ISSUE TITLE
Internal server error on request on db/collection when mongodb driver user lacks readWrite permission

### ISSUE THREAD

**Issue by ujibang** [SoftInstigate/restheart#383]
## Expected Behavior
A request on a db/collection when mongodb driver user lacks readWrite permission should lead to response status FORBIDDEN

## Current Behavior
The request lead to Internal Server Error:

```
HTTP/1.1 500 Internal Server Error

{
    "exception": "java.lang.RuntimeException",
    "exception message": "com.mongodb.MongoQueryException: Query failed with error code 13 and error message 'not authorized on roads to execute command { find: '_properties', filter: { _id: '_properties' }, limit: 1, singleBatch: true, $db: 'roads', $clusterTime: { clusterTime: Timestamp(1592294129, 8), signature: { hash: BinData(0, 2676F54E1AA468CEF9682DADCE437FA0D2C1F212), keyId: 6828929976947965955 } }, lsid: { id: UUID('b40a5cee-dd68-4cba-830f-317d523aa9f3') } }' on server gart-test-shard-00-02.t8cze.mongodb.net:27017",
    "http status code": 500,
    "http status description": "Internal Server Error",
    "message": "Error handling the request, see logs for more information"
}
```

## Environment
RESTHeart 5.1

## Steps to Reproduce

1. create a mongodb user 'test' without readWrite role on the collection  `restheart.test`
2. configure RESTHeart to connect to MongoDB using `test`
3. execute GET /test

## Possible Implementation
The problem is due to the exception being thrown on `CollectionPropsInjector` executing `dbsDAO.getCollectionProperties()` (or when user lack permissions on db `DbPropsInjector`  executing `dbsDAO.getDatabaseProperties()`)

These are interceptors so executed by restheart-core so that the MongoService's `ErrorHandler` (that handles error code 13) does not handle it.

**Comment by ujibang** [comment]
Fixed in 7f665d902161381728ffe6fd92555c3f38286d10

Now response looks like:

```json
{
    "http status code": 403,
    "http status description": "Forbidden",
    "message": "The MongoDB user does not have enough permissions to execute this operation"
}
```

**Comment by Har-IT-TechWide** [comment]
hi @ujibang I am Getting the above error "The MongoDB user does not have enough permissions to execute this operation" for my MongoDB. What is the solution for this. Do I need to add any user permission in restheart.yml?

**Comment by ujibang** [comment]
@Har-IT-TechWide 

this should be related to the MongoDB user used to connect RESTHeart to MongoDB that lacks required permissions.

For more information on how to provide the MongoDB user the correct permissions read https://restheart.org/docs/security/secure-connection-to-mongodb#restrict-permissions-of-mongodb-user
