### ISSUE TITLE
Interceptors: Differences/usage between the interceptors

### ISSUE THREAD

**Issue by StephenOTT** [SoftInstigate/restheart#389]
Hey
Is there usage docs around when the different interceptors would be used?  Specifically looking at JsonInterceptor vs  BsonInterceptor vs MongoInterceptor: Is there a description of what parsing occurs in each layer and when you would check?

Something like: JsonIntercetor: web request handling, BsonInterceptor: serialization handling, and MongoInterceptor: request db request handling ?

**Comment by ujibang** [comment]
The documentation about interceptors is available at https://restheart.org/docs/plugins/core-plugins/#interceptors

### First rule: 

> An interceptor can intercept requests handled by a Service when its request and response types are equal to the ones declared by the Service.

### Second rule:

The actual parsing logic is defined by Services. This way each request ends up to one single parsing operation to optimize performances. This is also required to allow interceptors to manipulate the request before the service takes in place.

See documentation at https://restheart.org/docs/plugins/core-plugins/#services

For instance [JsonService](https://github.com/SoftInstigate/restheart/blob/master/commons/src/main/java/org/restheart/plugins/JsonService.java) code is:

```java
public interface JsonService extends Service<JsonRequest, JsonResponse> {
    @Override
    default Consumer<HttpServerExchange> requestInitializer() {
        return e -> JsonRequest.init(e);
    }

    @Override
    default Consumer<HttpServerExchange> responseInitializer() {
        return e -> JsonResponse.init(e);
    }

    @Override
    default Function<HttpServerExchange, JsonRequest> request() {
        return e -> JsonRequest.of(e);
    }

    @Override
    default Function<HttpServerExchange, JsonResponse> response() {
        return e -> JsonResponse.of(e);
    }
}
``` 

As you see, it defines a request initialization function with `requestInitializer()`

It invokes `JsonRequest.init()` that uses `JsonParser` to parse the request content as a `JsonElement`

```java
public class JsonRequest extends ServiceRequest<JsonElement> {
    private JsonRequest(HttpServerExchange exchange) {
        super(exchange);
    }
    
    public static JsonRequest init(HttpServerExchange exchange) {
        var ret = new JsonRequest(exchange);
        
        try {
            ret.injectContent();
        } catch (Throwable ieo) {
            ret.setInError(true);
        }
        
        return ret;
    }
    
    public static JsonRequest of(HttpServerExchange exchange) {
        return of(exchange, JsonRequest.class);
    }
    
    public void injectContent() throws IOException {
        var json = JsonParser.parseString(ChannelReader
                .read(wrapped.getRequestChannel()));
        
        setContent(json);
    }
}
```

**Comment by StephenOTT** [comment]
So based on this then the order is something like the following?

httpReq -> JsonService -> JsonInterceptor -> MongoInterceptor
httpReq -> BsonService -> BsonInterceptor -> MongoInterceptor

**Comment by ujibang** [comment]
`MongoInterceptor` intercepts requests handled by the `MongoService` (and resolving the request, ie `resolve()` returns `true`).

`JsonInterceptor` intercepts requests by services implementing the `JsonService` interface (and resolving the request, ie `resolve()` returns `true`).

`BsonInterceptor` intercepts requests by services implementing the `BsonService` interface (and resolving the request, ie `resolve()` returns `true`).  Note that `BsonService` is just a Service with requests and response using `BsonValue` as content type. It is not used by `MongoService`(that uses `MongoRequest` and `MongoResponse`)

 the request can be intercepted on different stages, `REQUEST_BEFORE_AUTH`, `REQUEST_AFTER_AUTH`, `RESPONSE` and `RESPONSE_ASYNC` so you can snoop and modify:
- the **request** before or after that authentication and authorization occur
- the **response** generated by the handling service, synchronously and asynchronously with the response sending


```
httpReq -> JsonInterceptor (interceptPoint.REQUEST_BEFORE_AUTH) -> [Authentication & Authorization] -> JsonInterceptor (interceptPoint.REQUEST_AFTER_AUTH) -> JsonService -> JsonInterceptor (interceptPoint.RESPONSE) -> httpResp
```

```
httpReq -> MongoInterceptor (interceptPoint.REQUEST_BEFORE_AUTH) -> [Authentication & Authorization] -> MongoInterceptor (interceptPoint.REQUEST_AFTER_AUTH) -> MongoService -> execute Mongo command -> MongoInterceptor (interceptPoint.RESPONSE) -> httpResp
```

**Comment by ujibang** [comment]
closing, feel free to reopen if needed
