### ISSUE TITLE
docker image for GraalVM version

### ISSUE THREAD

**Issue by chaoqing** [SoftInstigate/restheart#399]
Hi, thanks a lot for this fantastic project. I am not a java developer, so know little on the java thing.
Thanks to the Docker image, I can easily start a service to serve mongodb.
But I did not find one docker image with GraalVM enabled, which I think will be better for guys like us just want using your work in cloud.

So I I would really appreciate if you guys could create a Dockerfile for GraalVM native version of restheart and push it to Dockerhub.

**Comment by mkjsix** [comment]
Hi @chaoqing 

Thank you for your kind words. A GraalVM docker image sounds like a good idea and it's already on our roadmap, but we don't have an ETA yet.

Byt the way, with the upcoming new version of RESTHeart it is possible to implement plugins also in JavaScript.

**Comment by ujibang** [comment]
We still didn't released a GraalVM image but we now have `restheart-native` (a binary image build with GraalVM, which allows JS plugins deployments):

```
$ docker pull softinstigate:restheart:6.0.0-native
```

Also docker-compose is available:

```
# Create dirs
$ mkdir restheart-native restheart-native/etc restheart-native/plugins  && cd restheart-native

# GRAB docker compose file
$ curl https://raw.githubusercontent.com/SoftInstigate/restheart/master/docker-compose-native.yml --output docker-compose.yml

# GRAB CONFIGURATION FILES
$ curl https://raw.githubusercontent.com/SoftInstigate/restheart/master/core/etc/acl.yml --output etc/acl.yml
$ curl https://raw.githubusercontent.com/SoftInstigate/restheart/master/core/etc/users.yml --output etc/users.yml
$ curl https://raw.githubusercontent.com/SoftInstigate/restheart/master/core/etc/restheart.yml --output etc/restheart.yml
$ curl https://raw.githubusercontent.com/SoftInstigate/restheart/master/core/etc/default.properties --output etc/default.properties

# launch stack

$ docker-compose up
```

**Comment by ujibang** [comment]
update:

we are releasing the following docker images:

### restheart running on OpenJDK

```
$ docker pull softinstigate/restheart:6.0.3
```

Note: allows deploying only Java plugins

### restheart-native (executable built as native image with GraalVM)

```
$ docker pull softinstigate/restheart:6.0.3-native
```

Notes:
- allows deploying only JavaScript plugins (Java plugins require to be built as native image)
- smaller memory footprint and faster startup

### RESTHeart running on GraalVM Java Rutime

```
$ docker pull softinstigate/restheart:6.0.3-graalvm
```

Notes: 
- allows deploying both Java and JavaScript plugins
- bigger docker image
