### ISSUE TITLE
$currentDate inside an array -- HTTP Post request

### ISSUE THREAD

**Issue by MetallicHack** [SoftInstigate/restheart#400]
Hi,

First of all, thanks for your project, this is really hellpfull !!
I have got an issue that I don't understand.

I want to create new document with http POST request if it doesn't exist in my collection.
Then, I will add new objects in the array (thanks to PATCH) which will contain the price and the $currentDate.
My documents all contain an array, with objects inside, which all contain the "updateDate".

If I put the "$currentDate" outside the array like this, it works :
`[{
    "Name":  "REFRIGIRATOR",
    "$currentDate": { "updateDate": true },
    "Array":  [
                  {
                      "StockExchangePrice":  233                  
                  }
              ]
}]`

However, if I do this : 

`[{
    "Name":  "REFRIGIRATOR",
    "Array":  [
                  {
                      "StockExchangePrice":  233,
                      "$currentDate": { "updateDate": true }				  
                  }
              ]
}]`

It doesn't work.
I receive an error 52 from MongoDB.

Any idea why it doesn't work ?

Thank you in advance !

**Comment by ujibang** [comment]
Hi @MetallicHack ,

this is not how update operator work. To update your document with `$currentDate` you need to use the [dot notation](https://docs.mongodb.com/manual/core/document/#document-dot-notation)

So basically your request should be:


to update all documents in the array:
```
PATCH /coll/docid

{
    "$currentDate": {
        "array.$[]. updateDate": true
    }
}
```

to update the second document in the array:
```
PATCH /coll/docid

{
    "$currentDate": {
        "array.1. updateDate": true
    }
}
```

**Comment by MetallicHack** [comment]
Thank you very much for your time and your answer !

Would it be possible, in 1 single PATCH request, to push a new document in the array and update the date inside this same document ?
Something like this (without producing a conflict...) :
`
"$push": { "array": {"productName" : "myproduct"} },
"$currentDate": {
        "array.1.updateDate": true
    }`

I would like to add a new document inside in the array with one PATCH request.
Through this, a document like this : 
`{"productName" : "myproduct", "updateDate":XXXXXXX }` 
would be added in the array.
