### ISSUE TITLE
Dynamic generation of OpenAPI3 documentation for Swagger UI

### ISSUE THREAD

**Issue by eliasgruenewald** [SoftInstigate/restheart#406]
## Expected Behavior
It would be great to dynamically create an OpenAPI3 specification in JSON or YAML format to have an API documentation that can be displayed in Swagger UI or some comparable tool.

## Current Behavior
Currently, we can only "guess" which endpoints are there.

## Context
This refers to all possible schemes.

## Environment
Latest restheart version.

## Steps to Reproduce
Not available.

## Possible Implementation
Open for discussion.

**Comment by mkjsix** [comment]
To be honest, this is an idea we are thinking about for years now, but we have never had the time to actually work on it.

**Comment by eliasgruenewald** [comment]
Interesting, thanks for the quick answer! Do you think, it's going to be put on the roadmap rather soonish or is it expected to be highly or too complex?

**Comment by mkjsix** [comment]
Hi,
It's a matter of available resources more than complexity: we are a small company and the product has grown huge, so we can implement new features only when there's a clear return on the investment. At present we are adding major new features only when we have an active  customer willing to sponsor the initiative.
In this specific moment we have other priorities, so even if the feature looks interesting we could only put it in the roadmap but without an ETA. Before summer we are going to release RESTHeart v6 with full support for a GraphQL API on top of MongoDB and that has been a major effort for us, but of course we would be happy to collaborate and merge PRs.
For example, the GraphQL API itself has been developed as part of a master thesis degree, which helped a lot.
