### ISSUE TITLE
DELETE operation reports ETag header as required instead of If-Match which is actually checked

### ISSUE THREAD

**Issue by gokrokvertskhov** [SoftInstigate/restheart#41]
DELETE operation on collection reports wrong required header (ETag, instead of If-Match)

Here (https://github.com/SoftInstigate/restheart/blob/develop/src/main/java/org/restheart/handlers/collection/DeleteCollectionHandler.java#L56) DELETE operation reports ETag header while getWriteEtag methods here (https://github.com/SoftInstigate/restheart/blob/develop/src/main/java/org/restheart/utils/RequestHelper.java#L53) checks for If-Match header existence.

**Comment by mkjsix** [comment]
Fixed by commit:

https://github.com/SoftInstigate/restheart/commit/e695013f134a0a47a302833858aac965f6d9ef97
