### ISSUE TITLE
Basic tutorial doesn't work on 6.0.3

### ISSUE THREAD

**Issue by IliaGe** [SoftInstigate/restheart#412]
Hey,
I have just deployed the restheart (6.0.3) and started the basic tutorial available at
https://restheart.org/docs/tutorial/

When I get to the "PUT a new document" or "PATCH a document" it returns 404.
I can only GET documents until this point. When I start using /inventory/newDoc it doesn't work and generated 404

## Steps to Reproduce

1.
2.
3.

**Comment by ujibang** [comment]
Yep, restheart 6 introduces the [write mode](https://restheart.org/docs/upgrade-to-v6/#write-mode-in-mongodb-rest-api)

by default PUT write mode is `update`. To have the request "PUT a new document" to create the document, we need to add `wm=upsert` or `wm=insert`

I fixed the tutorial page. Please try again
