### ISSUE TITLE
Password authentication problem

### ISSUE THREAD

**Issue by orkhanalizade** [SoftInstigate/restheart#42]
I'm trying to sign in from the browser 8080 port and it doesn't accept my username and password and asks again. I fill all correctly. What is the problem?

**Comment by ujibang** [comment]
Please provide more info, including your configuration files.

**Comment by orkhanalizade** [comment]
I did all absolutely how do you describe on your official page. After then
how I connected secure authentication it asks me to fill username and
password fields. I fill correctly but it asks me to sign in again and
again. In yml file I just corrected username and password lines

**Comment by ujibang** [comment]
Are you using the file based SimpleIdentityManager?

What is the role given to your user?

What are the permission given to this role?

What URI are you trying to access?

Paste the log messages (debug level) too.

**Comment by orkhanalizade** [comment]
okay! I did it! I had added it to the admin group in the same yml doc and
now it accepted my login and password, but it returns me:

{ "_embedded" : { } , "_links" : { "self" : { "href" : "/"} ,
"rh:paging" : { "href" : "/{?page}{&pagesize}" , "templated" : true} ,
"curies" : [ { "href" :
"http://www.restheart.org/docs/v0.10/#api-root-{rel}" , "templated" :
true , "name" : "rh"}]} , "_type" : "ROOT" , "_size" : 0 ,
"_total_pages" : 1 , "_returned" : 0}

is it correct? In my opinion something there is wrong


вт, 11 авг. 2015 г. в 19:04, Andrea Di Cesare <notifications@github.com>:

**Comment by orkhanalizade** [comment]
All works now! Thanks for your response!
