### ISSUE TITLE
gitreleases.dev deprecated

### ISSUE THREAD

**Issue by mweibel** [SoftInstigate/restheart#427]
hi!

I'm the author of [gitreleases.dev](https://gitreleases.dev) and saw that you use gitreleases.dev on your [setup page](https://restheart.org/docs/setup/). I can't find it in the code so this is just a heads-up:
gitreleases.dev will be shut down soon. GitHub has meanwhile added support for linking directly to assets:
https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases

Replace link:
`https://gitreleases.dev/gh/SoftInstigate/restheart/latest/<asset>`

With:
`https://github.com/SoftInstigate/restheart/releases/latest/download/<asset>`

Cheers
Michael

**Comment by ujibang** [comment]
Thank you @mweibel, much appreciated!

We updated the download links.
