### ISSUE TITLE
How to work in vue.js use Websocket without "Unauhorized Error:401"

### ISSUE THREAD

**Issue by jaeh8703** [SoftInstigate/restheart#428]
## Expected Behavior

I want to connect Websocket in vue.js and use like chat example
## Current Behavior

when I try connect, it happend "Unauhorized Error:401"
## Context

I just want watch my data in realtime

## Environment

macOS, v6, v5.0.6

<img width="1019" alt="스크린샷 2022-02-21 오전 10 29 33" src="https://user-images.githubusercontent.com/65217813/154874927-b34e3fee-c4d0-4842-bfa9-fe876d8fe375.png">
[security.txt](https://github.com/SoftInstigate/restheart/files/8105493/security.txt)
[restheart.txt](https://github.com/SoftInstigate/restheart/files/8105494/restheart.txt)

## Steps to Reproduce

1. this.socket = new WebSocket('ws://localhost:8080/db/');
       this.socket.onopen = () => {
         this.socket.send('test')
            this.socket.onmessage = ({data}) => {
                     console.log(data)
                 }
             }

**Comment by jaeh8703** [comment]
> Another option is to define a permission for the WebSocket endpoint that allows an unauthenticated client to connect.
> 
> You do this by creating an ACL document
> 
> ```httpspec
> POST /acl
> 
> {
>     "_id": "unauthenticatedCanConnectToMyWebSocket",
>     "predicate": "path-prefix('/messages/_streams/all')",
>     "roles": ["$unauthenticated"],
>     "priority": 0
>  }
> ```

I did try your solution, but I still have "Unauthorized Error:401" 
how do I fix this ?
<img width="581" alt="스크린샷 2022-02-23 오후 3 08 42" src="https://user-images.githubusercontent.com/65217813/155269433-f805eb7a-6849-4132-b10a-7526b1236565.png">
GET /acl
<img width="398" alt="스크린샷 2022-02-23 오후 3 06 23" src="https://user-images.githubusercontent.com/65217813/155269373-a57932c0-e3b3-4e89-958e-9e985d897817.png">
<img width="1378" alt="스크린샷 2022-02-23 오후 3 05 34" src="https://user-images.githubusercontent.com/65217813/155269393-53bcca52-55e2-41ef-820e-0d573fea79e6.png">

**Comment by ujibang** [comment]
I doubled checked:

the stream definition (took form https://restheart.org/docs/mongodb-websocket/examples/)

```
$ http -b -a admin:secret :8080/messages/_meta
{
    "_etag": {
        "$oid": "6215eea1dd912e789ae39811"
    },
    "_id": "_meta",
    "streams": [
        {
            "stages": [
                {
                    "_$match": {
                        "_$or": [
                            {
                                "operationType": "insert"
                            },
                            {
                                "operationType": "update"
                            }
                        ]
                    }
                }
            ],
            "uri": "all"
        },
        {
            "stages": [
                {
                    "_$match": {
                        "fullDocument::name": {
                            "_$var": "n"
                        }
                    }
                }
            ],
            "uri": "mine"
        }
    ]
}
```

The ACL permission

```
$ http -b -a admin:secret :8080/acl/unauthenticatedCanConnectToMyWebSocket
{
    "_etag": {
        "$oid": "6215fd0062aa2364cf2020fe"
    },
    "_id": "unauthenticatedCanConnectToMyWebSocket",
    "predicate": "path-prefix('/messages/_streams/all')",
    "priority": 0,
    "roles": [
        "$unauthenticated"
    ]
}
```

Connect to stream (using [websocat](https://github.com/vi/websocat))
```
$ websocat --text - autoreconnect:ws://127.0.0.1:8080/messages/_streams/all
```

Create a document in /messages

```
$ http -a admin:secret :8080/messages a:=1
HTTP/1.1 201 Created
```

The stream receives a change event:

```
$ websocat --text - autoreconnect:ws://127.0.0.1:8080/messages/_streams/all
{"fullDocument":{"_id":{"$oid":"6215fdcf62aa2364cf202106"},"a":1,"_etag":{"$oid":"6215fdcf62aa2364cf202105"}},"documentKey":{"_id":{"$oid":"6215fdcf62aa2364cf202106"}},"operationType":"insert"}
```

**Comment by ujibang** [comment]
I also noticed that in your code you are trying to send a message via the websocket.

The change streams API is read only, you get push notifications of change events in the collection.

To change documents in the collection and thus generating change events notified by the WebSocket API, you need to use the REST API, as in the example above.

**Comment by jaeh8703** [comment]
Thank you for answer!
I tried this but still have the problem.

It works fine untill the command "$ http -b -a admin:secret :8080/acl/unauthenticatedCanConnectToMyWebSocket".

but I still  have an Error 

"14:05:39.871 [XNIO-1 task-2] INFO  org.restheart.handlers.RequestLogger - GET http://127.0.0.1:8080/messages/_streams/all from /127.0.0.1:52396 => status=405 elapsed=2ms contentLength=106
 14:05:39.897 [XNIO-1 task-2] ERROR o.r.m.h.RequestDispatcherHandler - Can't find PipelinedHandler(CHANGE_STREAM, GET)”  

It happend when I request the Command "$ websocat --text - autoreconnect:ws://127.0.0.1:8080/messages/_streams/all”

how can I fix this ?

**Comment by mkjsix** [comment]
Beware that change streams work only if you are connected to a MongoDB Replica Set

**Comment by ujibang** [comment]
closing, feel free to reopen for additional help
