### ISSUE TITLE
How to pass the Ca cert of mongodb while running docker image

### ISSUE THREAD

**Issue by Rekha-Prakash** [SoftInstigate/restheart#429]
## Expected Behavior
Connecting to enterprise MongoDB with CA cert using docker image

## Current Behavior
Not finding an option to pass the CA crt to the docket image.

## Context
I am trying to connect to the enterprise mongodb which has cert. How can I pass the cert while running restheart docker image?

**Option 1:** Using env variable, where can I pass the cert, as the environment variable only has MONGO_URI. 

docker run --rm-p8080:8080 -e MONGO_URI='mongodb://mongoappuser:<PWD>@<XYC.com>:27117/?ssl=true&replicaSet=daas-mongodb&authSource=admin'-v/host/path/to/default.properties:/opt/restheart/etc/default.properties softinstigate/restheart

**Option 2** mounting property file to docker, Where can I pass the cert in restheart.yml or default.properties file ?

docker run -d -p 80:8080 --name restheart -v /git/restheart/etc:/opt/restheart/etc:ro softinstigate/restheart

**Comment by mkjsix** [comment]
Hi,

This is how I'd do it:

You have to create the keystore by importing the certificate used by mongod with the [keytool command](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/keytool.html) 

If you have a look at [Connect to MongoDB over TLS/SSL](https://restheart.org/docs/mongodb-rest/secure-connection-to-mongodb/#connect-to-mongodb-over-tlsssl) in our documentation, you see how to do it outside a container.

Then I would run the container overriding its default ENTRYPOINT

```
FROM eclipse-temurin:17-jre

LABEL maintainer="SoftInstigate <info@softinstigate.com>"

WORKDIR /opt/restheart
COPY target/restheart.jar .
COPY target/plugins/* plugins/

ENV RHO='/mongo-uri->"mongodb://host.docker.internal";/http-host->"0.0.0.0"'
ENTRYPOINT [ "java", "-Dfile.encoding=UTF-8", "-server", "-jar", "restheart.jar" ]
EXPOSE 8009 8080 4443
```

Which means:

` $ docker run --rm-p8080:8080 -e MONGO_URI="<...>" --entrypoint "java -Dfile.encoding=UTF-8 -server -Djavax.net.ssl.trustStore=rhTrustStore -Djavax.net.ssl.trustStorePassword=changeit -Djavax.security.auth.useSubjectCredsOnly=false -jar restheart.jar etc/restheart.yml -e etc/default.properties" -v "/host/path/to/rhTrustStore:/opt/restheart/rhTrustStore" softinstigate/restheart`

Also adding a -v to mount the file where the keystone is (named "rhTrustStore" in this example).

As mentioned, I have not tried this by myself yet.

**Comment by ujibang** [comment]
closing, feel free to reopen for additional help
