### ISSUE TITLE
Read Preference per request

### ISSUE THREAD

**Issue by WT2** [SoftInstigate/restheart#450]
Hello Guys

Is there a way to choose the Read Preference for a given request, via a parameter in the url?
If this parameter exists, it overrides the default one we put on the mongodb connection string.
If not, i think it will be a nive improvement. 

Thanks

**Comment by ujibang** [comment]
you can do it, see https://restheart.org/docs/upgrade-to-v7#allow-to-specify-readconcern-writeconcern-and-readpreference-at-request-level

**Comment by WT2** [comment]
yep great working well :) 
thanks guys
