### ISSUE TITLE
Refactor code to support the Mongodb Java driver v. 3.0

### ISSUE THREAD

**Issue by mkjsix** [SoftInstigate/restheart#46]
Version 3 of the Java driver for Mongodb is now stable and introduces many API and performance improvements. We need to plan a refactoring of the DAO layer and move RESTHeart core to the new API.

Ref:
http://blog.mongodb.org/post/58136652766/the-mongodb-java-driver-30
https://www.mongodb.com/blog/post/introducing-30-java-driver

**Comment by ujibang** [comment]
closing and moving task to jira https://softinstigate.atlassian.net/browse/RH-100
