### ISSUE TITLE
GraphQL API always returns 400 in case of well formatted responses that include errors

### ISSUE THREAD

**Issue by ujibang** [SoftInstigate/restheart#484]
**Describe the bug**

If a GraphQL query returns a well formatted GraphQL response with not empty `errors`, RESTHeart response status code is 400

According to [GraphQL Over HTTP specs](https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md)

> The server SHOULD NOT use a 4xx or 5xx status code for a response to a well-formed GraphQL-over-HTTP request.

Nevertheless, according to the de facto standard, RESTHeart should return 400 in case of validation errors (such as undefined query, undefined argument, undefined field or incorrect argument).

For instance, the Space X GraphQL API responds 400 for undefined query

```
echo '{"query": "query NotExists { company { foo } }"}' | http post https://main--spacex-l4uc6p.apollographos.net/graphql
HTTP/1.1 400 Bad Request
....

{
    "errors": [
        {
            "extensions": {
                "code": "INVALID_FIELD",
                "field": "foo",
                "type": "Info"
            },
            "message": "cannot query field 'foo' on type 'Info'"
        }
    ]
}
```

The test case  ["Should contains errors key" in field-to-aggregation.feature](https://github.com/SoftInstigate/restheart/blob/e2f60f8ec97c1ade16019deef65b7552d2f0ddad/core/src/test/java/karate/graphql/field-to-aggregation/field-to-aggregation.feature#L60) is tricky. It produces a `DataFetchingException` due to an invalid aggregation mapping and also return wrong data `"data":{"userByEmail":{"malformedStage":null}}`. Should be the status code 500 in this case???

**To Reproduce**

1. Execute the test case ["Should contains errors key" in field-to-aggregation.feature](https://github.com/SoftInstigate/restheart/blob/e2f60f8ec97c1ade16019deef65b7552d2f0ddad/core/src/test/java/karate/graphql/field-to-aggregation/field-to-aggregation.feature#L60)
2. The status code is 400

**Expected behavior**

When a correct GraphQL response can be generated, even if it contains errors, the status code should be 200

**Detailed documentations**

the response content type from the GraphQL API is now always `application/graphql-response+json`
the API response codes are:

- 404 graphql app not existing
- 405 wrong method (not POST or OPTIONS)
- 500 connection error with mongodb  <== this is the only case when 500 is returned
- 200 when valid GraphQL response even if contains some errors (partial data)
- 400 when the request is invalid (e.g. wrong json, wrong GraphQL query, not existent fields in selection, etc)
- 400 when the request is valid but the response only contains errors the prevented any data to be fetched (i.e. data: null)

For the last case the specification says:
>If the GraphQL response does not contain the {data} entry then the server MUST reply with a 4xx or 5xx status code as appropriate

**Comment by jodeleit-es** [comment]
I assume the first link has a wrong target. Did you want to link to this URL? --> https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#applicationjson
