### ISSUE TITLE
Help request for a solution based on restheart 6.1.4

### ISSUE THREAD

**Issue by repka3** [SoftInstigate/restheart#504]
Hi everybody,

I am managing a Softinstigate solution for a client based on RestHeart 6.1.4.

Recently, the solution has been subjected to real-world usage load, and the RestHeart container has experienced some unjustified shutdowns (in the Amazon Elastic Container Service).

I'll attach some screenshots that depict the situation:

![Screenshot 2024-04-10 104412](https://github.com/SoftInstigate/restheart/assets/694917/f4cedbff-c39f-4ff9-b264-cdb54f81cb82)

![Screenshot 2024-04-10 104313](https://github.com/SoftInstigate/restheart/assets/694917/cd326ab0-2c5d-4d71-b5cc-c567cfb42c9c)

The application logs don't show anything unusual—no errors, no warnings.

Could you help identify the problem? What other informations do you need?

From what I gather, this could be a bug with RestHeart itself (as evidenced by the unexplained spike in load and the consequent shutdown).

Could a version upgrade solve the issue? If so, which version is safe to upgrade from 6.1.4?

Thank you.

**Comment by mkjsix** [comment]
At first, we should look at RESTHeart's logs, as here we can only see the ECS lifecycle events, which provide little information. For example, have you set up the ECS service to log into CloudWatch? Please attach the logs here.

**Comment by mkjsix** [comment]
Ok, I missed the part when you wrote no errors in logs, but do you know if RESTHeart receives big payloads? It could be that some requests are creating CPU or memory issues in the container itself. In our previous experience, we had a similar behaviour when a customer was posting by mistake huge JSON documents inducing the container to run out of memory. Could you try adding some memory to the container and see what happens?

**Comment by repka3** [comment]
First of all, thanks for answering.

I can attach you the last 2 days of logs, but beside some error due to duplicate key (application error) and some warning due to a bug in the frontend, they show nothing relative to the moment when the problem present itself.

[log-events-viewer-result (2).csv](https://github.com/SoftInstigate/restheart/files/14931122/log-events-viewer-result.2.csv)

The amount of Json is the same at every request, it doesn do any mass post or anything like that.

The service is under a balance loader with max of 9 tasks of 4 gb each, and the scale policy is memory utilization. 

As far as I can tell the service didn;t even attempted to scale, just died.

So you are suggesting to increment the memory available for single task ?

Is there anything I can do to monitor better the situation as far as you can tell ?

Thanks again.

**Comment by mkjsix** [comment]
Usually, 4GB of RAM are more than enough for heavy loads, and the logs suggest there are no problems with RESTHeart itself.

From the ECS logs:

```
service oa-restheart-prod port 8080 is unhealthy in target-group oa-prod-t [2 due to
(reason Request timed out).
```

So the problem should be your [target group health check settings](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html).

I suggest looking at this article: [How do I troubleshoot health check failures for Amazon ECS tasks on Fargate?](https://repost.aws/knowledge-center/ecs-fargate-health-check-failures).

Below is a typical configuration that works for us:

![Screenshot 2024-04-16 alle 07 38 43](https://github.com/SoftInstigate/restheart/assets/365382/de42f977-402e-432b-9941-9317beefe841)

**Comment by repka3** [comment]
Hello,

I tried to increse che containers memory from 4G to 8G, checked all incoming JSON for given session (meeting, since che application is about casting votes basically), and checked the "life check" performed from aws, to no avail. Life check is setup like you said and it is actually killing the container when the app no longer works (i.e. the application is so slow the prior 60 seconds, it's practically unusable)

The only "anomaly" I found for this particular tenant, is the json response due to clients request constantly to get the status of the tenena (i.e. the /status in the setinterval in the frontend) . It has hundreds of entries and forech entry there are list of all partecipant (for instance attendees for given entry, positive votes, negative and so on.) So it's "quite big" in constrast to the standard usage, but I dont understand how can it kill the restheart.

The other thing I find strange is the health graph in AWS for the cluster. You see how the RAM is really high even when the application is no longer in use ? And keep in mind we are talking about 8G of ram. If we were in a C/C++ context, I would instinctively call this scenario "missing free after malloc (or delete/new)".
![Screenshot 2024-04-20 090514](https://github.com/SoftInstigate/restheart/assets/694917/c97002a6-f2e6-41cd-a3b1-7543d44c409b)


Any suggestion for the situation?

Thanks for your time.

**Comment by mkjsix** [comment]
Regarding the memory issue, this usually depends on the JVM Garbage Collector cycles. However, if the memory never gets released, there could be some other problem, but actually you are not getting any OutOfMemory Exception so far. In our experience we never had to use a RESTHeart container with more than 4 GB of RAM even for huge payloads. The issue here to me seems to be the very high CPU usage: you should to investigate what part of the solution is eating all the CPU, as it could be either some custom code or some external library.

Version 6.1.4 is pretty old anyway, my suggestion is to see what happens moving to 6.6.1. Version 7.x would be even better but introduces a different configuration model so it might require some rework to adapt to the present solution.
