### ISSUE TITLE
AGPL Licence Issue

### ISSUE THREAD

**Issue by Har-IT-TechWide** [SoftInstigate/restheart#509]
**Describe the bug**

We are getting AGPL lice issue and Our org is blocking this Docker Image

**Additional context**

What are the steps we need to take from unblock this docker image.

**Comment by mkjsix** [comment]
It seems your organization is preventing you to use docker images with AGPL license. There's nothing we can do on this side, you should ask people within your organization about your policies.

RESTHeart is distributed under a dual licensing mode: you can use it under the open-source [AGPL v3 license](https://github.com/SoftInstigate/restheart/blob/master/LICENSE.txt) or you can buy a [commercial license](https://github.com/SoftInstigate/restheart/blob/master/COMM-LICENSE.txt).

For more informations on the commercial license have a look at [restheart.com](https://restheart.com/).
