### ISSUE TITLE
Connect to Atlas Cluster

### ISSUE THREAD

**Issue by sgkamakama** [SoftInstigate/restheart#512]
I am getting connection error when using mongodb+srv://username:password@host/db.

I am wondering if Restheart support mongodb+srv

Thank you

**Comment by sgkamakama** [comment]
This is my script

***@***.***/catalyst?retryWrites=true&authenticationDatabase=admin&replicaSet=atlas-u1k7lv-shard-0&readPreference=secondary&readPreferenceTags=nodeType:ANALYTICS&srvServiceName=mongodb&readConcernLevel=local


Error

com.mongodb.MongoQueryException: Command failed with error 13 (Unauthorized): 'not authorized on catalyst to execute command { find: "_properties", readConcern: { level: "local" }, filter: { _id: "_properties" }, limit: 1, singleBatch: true, $db: "catalyst", $clusterTime: { clusterTime: Timestamp(1718703618, 1), signature: { hash: BinData(0, C5BD84F5C5AAC0E8F42A7EE50F44B48491472E47), keyId: 7365678082948071430 } }, lsid: { id: UUID("3d6d7b9c-68b9-456c-bac0-098865eadd92") }, $readPreference: { mode: "secondary", tags: [ { nodeType: "ANALYTICS" } ] } }' on server pl-0-eu-central-1.bozk8.mongodb.net:1027. The full response is {"ok": 0.0, "errmsg": "not authorized on catalyst to execute command { find: \"_properties\", readConcern: { level: \"local\" }, filter: { _id: \"_properties\" },

**Comment by sgkamakama** [comment]
This is my script it give

***@***.***/catalyst?retryWrites=true&authenticationDatabase=admin&replicaSet=atlas-u1k7lv-shard-0&readPreference=secondary&readPreferenceTags=nodeType:ANALYTICS&srvServiceName=mongodb&readConcernLevel=local


Error

com.mongodb.MongoQueryException: Command failed with error 13 (Unauthorized): 'not authorized on catalyst to execute command { find: "_properties", readConcern: { level: "local" }, filter: { _id: "_properties" }, limit: 1, singleBatch: true, $db: "catalyst", $clusterTime: { clusterTime: Timestamp(1718703618, 1), signature: { hash: BinData(0, C5BD84F5C5AAC0E8F42A7EE50F44B48491472E47), keyId: 7365678082948071430 } }, lsid: { id: UUID("3d6d7b9c-68b9-456c-bac0-098865eadd92") }, $readPreference: { mode: "secondary", tags: [ { nodeType: "ANALYTICS" } ] } }' on server pl-0-eu-central-1.bozk8.mongodb.net:1027. The full response is {"ok": 0.0, "errmsg": "not authorized on catalyst to execute command { find: \"_properties\", readConcern: { level: \"local\" }, filter: { _id: \"_properties\" },

**Comment by mkjsix** [comment]
The error message you're encountering, `not authorized on catalyst to execute command`, indicates that the user you are using to connect to the MongoDB Atlas cluster does not have the required permissions to execute the query on the catalyst database.
Check user permissions and if the user does not have the necessary permissions, you can update the user's roles to include read access to the catalyst database. Add a role such as read or readAnyDatabase to the user.

**Comment by sgkamakama** [comment]
Sorry for sending another email.

When connecting with the same URL using mongosh shell (shown below), Studio T3 and MongoDB Compas I am able to connect. I have also attached my custom yml. Your assistance will be much appreciated

Thank you

***@***.***

**Comment by sgkamakama** [comment]
Thanks a lot, I will check and test.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by mkjsix** [comment]
Closing this. Please re-open when you'll have additional information.
