### ISSUE TITLE
Pagesize

### ISSUE THREAD

**Issue by Qahraman** [SoftInstigate/restheart#52]
Hi,I changed pagesize 3000 in restheart.yml and started this ,but it wasn't changed.it returns "message": "illegal page parameter, pagesize must be >= 0 and <= 1000. Please help me

**Comment by mkjsix** [comment]
Actually the maximum pagesize you can set is 1000, it doesn't sound realistic to exchange bigger pages, it would create a huge JSON payload.

**Comment by Qahraman** [comment]
Thank you very much.You really help me.
