### ISSUE TITLE
Aggregate

### ISSUE THREAD

**Issue by Qahraman** [SoftInstigate/restheart#55]
How to use aggregate queries in restheart?

**Comment by ujibang** [comment]
currently aggregate queries are not supported.

note that this is in the roadmap and planned for next version

jira task 41: https://softinstigate.atlassian.net/browse/RH-41

as a workaround you can implement a custom application handler: documentation at https://softinstigate.atlassian.net/wiki/x/IoCw

**Comment by Qahraman** [comment]
Thanks

**Comment by ujibang** [comment]
@Qahraman we just released 1.1 with aggregation supporto

more info at http://www.softinstigate.com/blog/2015/12/08/what-is-new-in-RESTHeart-1.1.0/
