### ISSUE TITLE
insert document

### ISSUE THREAD

**Issue by Qahraman** [SoftInstigate/restheart#56]
I used to insert one document.but batch insert can't use.Please help me

**Comment by ujibang** [comment]
sorry, I don't understand you question.

if you mean that you inserted a document but you are not able to update it, you meet the ETag feature.

documentation at https://softinstigate.atlassian.net/wiki/x/hICM

in summary, to update (or delete) an existing document, you need to pass the ETag in If-Match request header

**Comment by Qahraman** [comment]
OK.Thank you very much
