### ISSUE TITLE
Return all documents in a collection

### ISSUE THREAD

**Issue by misinco** [SoftInstigate/restheart#57]
Instead of using page and pageSize, is there a way to just return all documents in a collection?  I looked around but was unable to find anything.

**Comment by ujibang** [comment]
You cannot get all documents of a collection in one shot. think about paging as the equivalent of db cursors....

The pagesize limit is 1000: bigger values result in too big hal+json response documents.

You have to iterate and GET all the available pages; if you specify the *count* query parameter you also get _size and _total_pages properties.
