### ISSUE TITLE
Bad request when get collection with parameter

### ISSUE THREAD

**Issue by vanhung89** [SoftInstigate/restheart#59]
Hi
I'm newbie. I use RequestParams to put parameter to filter collection. 
params.put("username", email);
params.put("username", email);
params has type is RequestParams 
When I use 
client.get("http://10.0.2.2:8080/android/user?filter=", params, new AsyncHttpResponseHandler() {
..........
} 
to query, It said Bad request. Can you tell me why? And how to fix it. Thanks

**Comment by ujibang** [comment]
try to log the URL parameter of the client.get() call. 

It should be:

```
http://10.0.2.2:8080/android/user?filter={'email':'xxx@yyy.com'}
```

**Comment by vanhung89** [comment]
Why we don't use RequestParams  to pass parameter? And when do we use RequestParams?

**Comment by mkjsix** [comment]
In this specific case "filter" is a single parameter because it's a MongoDB query and must be a single JSON payload:
https://docs.mongodb.org/manual/reference/method/db.collection.find/
