### ISSUE TITLE
Unable to connect using Plain Credentials (when using LDAP)

### ISSUE THREAD

**Issue by merrickkw** [SoftInstigate/restheart#61]
Please add support for Plain Credentials, which is used for LDAP.

Currently the code at org.restheart.db.MongoDBClientSingleton:

                        credentials.add(MongoCredential.createCredential((String) mongoUser, (String) mongoAuthDb, ((String) mongoPwd).toCharArray()));

The above need to be replaced with the following

                        credentials.add(MongoCredential.createPlainCredential((String) mongoUser, (String) mongoAuthDb, ((String) mongoPwd).toCharArray()));

mongoAuthDb will need to configured at the restheart.yml (mongo-credentials - auth-db) as $external

**Comment by mkjsix** [comment]
Hi, we can insert this into our backlog, but if you need anything soon the best way would be to open a pull request (code and tests).

**Comment by merrickkw** [comment]
I hope next version will use and support

com.mongodb.MongoClientURI

This should solve any kind of authentication mechanism

**Comment by ujibang** [comment]
this sounds like a great idea!

I'll check it and eventually we can turn the mongo configuration option to use mongo URIs!

this way, we can also pass options to configure, for instance, the Write concern.

I created the improvement in our jira https://softinstigate.atlassian.net/browse/RH-119

**Comment by ujibang** [comment]
FYI mongo-uri is now used in configuration file!

Find it in the latest commit cae8e757635fc2f7dafa25e09134d4d194fbc74b 

It will be officially released with RESTHeart 1.1

**Comment by ujibang** [comment]
@merrickkw release 1.1 is out with mongo uri support.
more info at http://www.softinstigate.com/blog/2015/12/09/what-is-new-in-RESTHHeart-1.1.0/

we also cited your suggestion, thanks

**Comment by merrickkw** [comment]
@ujibang Thanks for the updates!! will try to play around with it again...
