### ISSUE TITLE
get MongoDB ObjectId in JSON via Javascript

### ISSUE THREAD

**Issue by santoshh2015** [SoftInstigate/restheart#62]
Hello,

Recently I have started using RestHeart API with MongoDB.It is really cool. please suggest how to access object id from the below response using JQuery Ajax. Please find the below code snippet.

Thank you.

Request:

      jQuery.ajax({
         type: "GET",
         url:"http://localhost:8080/test/user?filter=",
         contentType: "application/json",
         dataType: "json",
         success: function (data, status, jqXHR) {
                  console.log(jqXHR.responseText);
         },

         error: function (jqXHR, status) {
         	alert("status:"+status);
         
         }
});
    

Here is the response:
```
{
  "_embedded": {
    "rh:doc": [
      {
        "_embedded": {},
        "_links": {
          "self": {
            "href": "/test/user/5626e2acd4c6d36cccf70b41"
          },
          "rh:coll": {
            "href": "/test/user"
          },
          "rh:document": {
            "href": "/test/user/{docid}{?id_type}",
            "templated": true
          },
          "curies": [
            {
              "href": "http://restheart.org/curies/1.0/{rel}.html",
              "templated": true,
              "name": "rh"
            }
          ]
        },
        "_type": "DOCUMENT",
        "_id": {
          "$oid": "5626e2acd4c6d36cccf70b41"
        },
        "Username": "test",
        "Password": "test",
        "_etag": {
          "$oid": "5626e2acd4c6d36cccf70b42"
        },
        "_lastupdated_on": "2015-10-21T00:56:12Z",
        "_created_on": "2015-10-21T00:56:12Z"
      }
    ]
  },
  
}
```

**Comment by ujibang** [comment]
You have to parse the response text to a json object, and access the documents in the _embedded['rh:doc'] array.

please try (I haven't tested it):

```
var responseJSON = jQuery.parseJSON(jqXHR.responseText);

responseJSON._embedded['rh:doc'].forEach(function(doc) {
    String id = doc._id['$oid'];
    console.log('document id: ' + id);
});
```

**Comment by santoshh2015** [comment]
It worked for me.Thank you Andrea Di Cesare.
