### ISSUE TITLE
Storing and retrieving files from GridFS using XmlhttpRequest

### ISSUE THREAD

**Issue by santoshh2015** [SoftInstigate/restheart#64]
Hello,

I am trying to capture the user information along with the image and saving into the db in a single document instead of having two dbs like usersdb & users.files. If possible can you guys share any example how to use GridFs to store/retrieve images from Mongodb using Javascript. 

Thank you in advance.

**Comment by ujibang** [comment]
Hi, 

files have properties: you might's them to store the user info.

In fact to create a file you need a multi part request: one part is the binary data, the other one, called 'properties' is any json.

Given that a file id is *file_id* the following requests allow to get the properties and the binary data respectively:

```
GET 127.0.0.1:8080/users.files/file_id

GET 127.0.0.1:8080/users.files/file_id/binary
```


More details in RESTHeart [GridFS](https://softinstigate.atlassian.net/wiki/x/RoCw) documentation.

However keep in mind that currently the file document is immutable. If you try to update it you'll get *501 Not Implemented* response code. Support for file update is planned for next release.

For some information have a look at this discussion https://github.com/SoftInstigate/restheart/issues/60 and to the related task in our roadmap https://softinstigate.atlassian.net/browse/RH-64.

**Comment by santoshh2015** [comment]
Andrea,

Thank you very much for sharing the information.It solved my problem.I was bit confused with db.files and GridFS. Will keep an eye for your next release.:)
