### ISSUE TITLE
eTag generation and modification.

### ISSUE THREAD

**Issue by hemraj-sharma** [SoftInstigate/restheart#69]
Hi,
I came across a problem related to etag. I am trying to get the etag information for a particular mongodb document updation using the url as follows:

:-> db_name/db_collection/mongodb_id

but sometimes it gives the etag and sometimes it does not.
 if the url "db_name/db_collection/mongodb_id" does not return the eTag, then I tried to get the same document with the url as bellow:
:-> db_name/db_collection?filter={"_id":{"$oid":"mongodb_id"}}
I find the _etag  in the response. This is outside the the embedded tag (containing the rh:doc ).
I used this etag to update this document value using PATCH api.
I put this etag in if-match header value and "content-type"-> "application/json" along with json data in the body.
In response I get the the error 409, a conflict response.
but in backend somehow it generates the etag for this particular document.
Now if I hit again with the url : 
:-> db_name/db_collection/mongodb_id
then I got a new etag value along with the document information.
Now if I again use the PATCH API to update using this new etag generated, I am able to update the mongo document.
But in the above process I have to hit mongodb 4 times, only to update a single document in the mongodb which is very expensive and not to be proceed with.

**Comment by ujibang** [comment]
The request

```
GET db_name/db_collection?filter={"_id":{"$oid":"mongodb_id"}}
```
is a request to a collection resource. It returns the collection properties and the documents as embedded resources (in _embedded['rh:doc'] array). 

**The _etag property outside the _embedded object is the tag of the collection (you use it to update the collection properties)**.

You need to find the *_etag* of the document you want to update. That will be an element of the *rh:doc* array. 

Of course you can do:

```
GET db_name/db_collection/mongodb_id
```

This is a request to a document resource, so you'll find the *_etag* directly between its properties.

Note that if you created the documents via a different client (e.g. the mongo shell) the _etag will not be there. In this case you don't need to specify the *If-Match* request header.

The *_etag* is updated every time the document is updated (via PUT or PATCH requests).

For more information I suggest you to a look at [Representation Format](https://softinstigate.atlassian.net/wiki/x/UICM) [URI format](https://softinstigate.atlassian.net/wiki/x/ToCM) and [ETag](https://softinstigate.atlassian.net/wiki/x/hICM) documentation sections.

**Comment by hemraj-sharma** [comment]
Thank you very much. I appreciate your concern.
Hemraj
