### ISSUE TITLE
support gridfs?

### ISSUE THREAD

**Issue by gaojice** [SoftInstigate/restheart#7]
support gridfs?

**Comment by gaojice** [comment]
thank u very much!
my use-case:
user can download file by: curl -O http://ip:port/db/fs/filename_or_id
just like what nginx-gridfs supplied.

**Comment by mkjsix** [comment]
Work in progress, we plan to release this feature in the final 0.9.8 release but we don't have a deadline yet, hopefully within a couple of weeks.

**Comment by mkjsix** [comment]
Update: we now have code to download files in our latest SNAPSHOT (develop branch). We are working also to add the possibility to POST files.

**Comment by ujibang** [comment]
0.10.0 adds support for GrifFs
