### ISSUE TITLE
system.indexes should not be used to determine whether a DB exists

### ISSUE THREAD

**Issue by fiddlerpianist** [SoftInstigate/restheart#75]
It seems that, in Mongo 3.2 with the default security model enabled, most client connections with reasonable privileges cannot see the system.indexes collection of a given database. Access to that collection also appears to be deprecated altogether (https://docs.mongodb.org/v3.0/reference/system-collections/).

This causes problems with the `doesDbExist(String dbName)` method on the `org.restheart.db.DbsDAO` class, as it returns false for databases which actually do exist. This in turn causes problems with the `GetRootHandler` and `GetDBHandler`.

**Comment by ujibang** [comment]
Thanks,

we need some more testing on 3.2

What do you mean exactly with "reasonable privileges"?
Is the *read* role enough?

**Comment by fiddlerpianist** [comment]
Correct. The read role is not enough, and neither is readWrite or even "create indexes."

**Comment by mkjsix** [comment]
FYI, we've just created a JIRA issue to track progress about MongoDB 3.2 compatibility and related tests.
https://softinstigate.atlassian.net/browse/RH-137

**Comment by ujibang** [comment]
fixed in 1.1.x branch

@fiddlerpianist can you please try it?

will be released in 1.1.3 soon

**Comment by fiddlerpianist** [comment]
Yes, that fixed it. Thanks!

**Comment by AEtherSurfer** [comment]
I am experiencing this in 3.0.7 as well.

**Comment by AEtherSurfer** [comment]
How long till 1.1.3-SNAPSHOT is deployed to mvn-repo?

**Comment by mkjsix** [comment]
@AEtherSurfer we have just put in place an automatic deployment of maven artifacts during the continuous integration process, so 1.1.3-SNAPSHOT jars are now deployed to mvn-repo and it will kept in synch for each successive git push. Please let us know if it works for you now.

**Comment by mkjsix** [comment]
@AEtherSurfer however, we suppose you have a different issue here, as MongoDB 3.0.7 does not have this behavior.

**Comment by fiddlerpianist** [comment]
For the record, this isn't a perfect fix, as it will not list databases that have been created but have no collections in them.

**Comment by ujibang** [comment]
Hello @fiddlerpianist,

Can you make an example on how to reproduce the problem?

**Comment by fiddlerpianist** [comment]
The original problem or the problem as to why this is not a perfect solution?

The reason it is not a perfect solution is that I can create a new database with no-defined user collections in it but it will not show up in RestHeart until a new collection is created.

1. Log into MongoDB with security enabled
2. Create a new database.
3. Verify that you cannot see any collections under the database (including system.indexes).
4. `/` will not list that newly-created database.
5. Create a new collection under that new database.
6. '/' will now list that database (and its collection if you drill down).

**Comment by ujibang** [comment]
How do you do step 2?
