### ISSUE TITLE
Best way to get multiple documents by different id's in single URI request

### ISSUE THREAD

**Issue by kalyangit** [SoftInstigate/restheart#77]
I want to get documents with two different ids in a single URI request.

**Comment by ujibang** [comment]
You need to GET the collection and use [filter](https://softinstigate.atlassian.net/wiki/x/XACk) to pass a mongodb query.

For instance the following request returns the 2 documents whose _id are the two specified ObjectIds (note the $oid keys)

```
GET /db/collection?filter={"_id": {"$in": [ {"$oid":"567429a27d31260d0f9f14f0" }, {"$oid": "566e86312d174c3087e54d12"}]}}
```
