### ISSUE TITLE
How to use $in on document ids in get

### ISSUE THREAD

**Issue by singhvikram704** [SoftInstigate/restheart#79]
I am trying to get set of object using $in on applying _id. But not getting any result.

http://localhost:8080/cart/products?page=1&pagesize=50&filter={"_id":{$in:["56728f50c80b6d044788cdcc","56728f50c80b6d044788cdcc"]}}

**Comment by ujibang** [comment]
the ids are ObjectId so you have to do

```
http://localhost:8080/cart/products?page=1&pagesize=50&filter={"_id":{"$in":[{"$oid": "56728f50c80b6d044788cdcc"},{"$oid": "56728f50c80b6d044788cdcc"}]}}
```

**Comment by singhvikram704** [comment]
working fine.. thanks :)
