### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by galgalesh** [SoftInstigate/restheart#80]
Hi

The docs at https://softinstigate.atlassian.net/wiki/display/RH/API+tutorial contain some errors. The httpie commands aren't always the correct ones. For example:

>Create a Collection

>    $ http PUT 127.0.0.1:8080/myfirstdb desc='this is my first db created with restheart'

**Comment by ujibang** [comment]
Hello @galgalesh 

I fixed it. You might want to give it a try :)

Thanks for reporting this.

**Comment by galgalesh** [comment]
Looks good now, Thanks!

**Comment by ujibang** [comment]
Thank you.

This is how a project becomes great!
