### ISSUE TITLE
Filtering date

### ISSUE THREAD

**Issue by machine16** [SoftInstigate/restheart#81]
So I have this on my db;
{
            	"DATE_T": {
                	"$date": 1444394707664
            	},
            	"Date_and_Time": "",
            	"ErrorType0": 0,
            	"ErrorType1": 0,
            	"ErrorType2": 0,
            	"ErrorType3": 1
}

and I want to filter by "DATE_T".

I am using:  
http -a a:a GET 127.0.0.1:8080/final/mydb?filter="{'DATE_T': {'$date':'1444394707664'}}"

and my result is ...
{
	"_collection-props-cached": false,
	"_created_on": "2015-12-22T15:56:41Z",
	"_etag": {
    	"$oid": "567972b921d89e1d020c4a68"
	},
	"_id": "mydb",
	"_links": {
    	"curies": [],
    	"self": {
        	"href": "/final/mydb?filter={'DATE_T': {' ':1444394707664}}"
    	}
	},
	"_returned": 0
}

could someone tell me what i am doing wrong?

**Comment by mkjsix** [comment]
Perhaps you defined "$date" as a number ("$date": 1444394707664) but you are querying it as a string ('$date':'1444394707664')? What happens if you remove the '' from the '1444394707664' in your filter?

**Comment by machine16** [comment]
the result is exactly the same...

**Comment by machine16** [comment]
I notice that in the response, at "href": "/final/mydb?filter={'DATE_T': {' ':1444394707664}}" ... the "$date" doesn't appear...

**Comment by machine16** [comment]
I already solved the problem.. I just removed the "" from the filter like this:

PREVIOUS: http -a a:a GET 127.0.0.1:8080/final/mydb?filter="{'DATE_T': {'$date':'1444394707664'}}"

NEW: http -a a:a GET 127.0.0.1:8080/final/mydb?filter={'DATE_T': {'$date':'1444394707664'}}

Thank you for your reply
;)
