### ISSUE TITLE
ETAG is not returned by the server

### ISSUE THREAD

**Issue by AntonioSpalluto** [SoftInstigate/restheart#82]
Hi All,

I would like to turn on the ETAG into the server response. As you can see in the following link it is not there, but the doc states it should be always there.
http://ag-messagebroker.westeurope.cloudapp.azure.com:8080/info/statistics/ag-virtualroulette-1/10?v0.0.1

Is this something missing into the configuration?

Many Thanks

**Comment by mkjsix** [comment]
Hi, yes, it must be there.
Which version of RESTHeart and MongoDB are you running?

**Comment by AntonioSpalluto** [comment]
Hi Maurizio,

RestHeart 1.0.3
MongoDB 3.0.7

Thanks

**Comment by mkjsix** [comment]
If the document was not created by RESTHeart then the ETAG is not there. You can try PATCHing the document using either curl or httpie without changing anything and RESTHeart should create the missing ETAG

**Comment by AntonioSpalluto** [comment]
Is there any way to enable the auto creation of the etag on mongodb
resources? I cannot see any valid reasons to not enable it.
On Wed, 23 Dec 2015 at 8:08 PM Maurizio Turatti <notifications@github.com>
wrote:

> If the document was not created by RESTHeart then the ETAG is not there.
> You can try PATCHing the document using either curl or httpie without
> changing anything and RESTHeart should create the missing ETAG
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SoftInstigate/restheart/issues/82#issuecomment-166972718>
> .
>
-- 

*Antonio Spalluto*
*Chief Technology Officer*

*Authentic Gaming*

http://www.authenticgaming.com

email: antonio.spalluto@authenticgaming.com
phone: 00 356 9912 7316
skype: antonio.authentic
linkedin: antoniospalluto

Disclaimer - The information contained in this message and any attachment
is intended for the recipient(s) designated only, is confidential and may
be privileged or otherwise protected from  disclosure. Therefore, the
contents of this message may not be re-transmitted, copied or revealed to a
third party without first obtaining the permission of the sender. If this
e-mail is received in error, please delete it immediately.

**Comment by ujibang** [comment]
The _etag is auto created by restheart.

This happens on any write operation (PUT, POST and PATCH)

Of course if data has not been created by restheart, you wont find it there unless your client adds { "_etag": new ObjectId() } to the insert.

To fix it you can PATCH your documenta and restheart will add it for you.

If you have many documents you can easily add the _etag from the mongo shell with a batch update.

Adding the _etag property on GET requests as well would violate the http protocol that mandates GET to be always a safe method (doesn't change the status of the resource).

**Comment by AntonioSpalluto** [comment]
Hi Andrea,

This sounds like the solution for me.

Thanks for your prompt reply.
On Thu, 24 Dec 2015 at 10:24 AM Andrea Di Cesare <notifications@github.com>
wrote:

> The _etag is auto created by restheart.
>
> This happens on any write operation (PUT, POST and PATCH)
>
> Of course if data has not been created by restheart, you wont find it
> there unless your client adds { "_etag": new ObjectId() } to the insert.
>
> To fix it you can PATCH your documenta and restheart will add it for you.
>
> If you have many documents you can easily add the _etag from the mongo
> shell with a batch update.
>
> Adding the _etag property on GET requests as well would violate the http
> protocol that mandates GET to be always a safe method (doesn't change the
> status of the resource).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SoftInstigate/restheart/issues/82#issuecomment-167076398>
> .
>
-- 

*Antonio Spalluto*
*Chief Technology Officer*

*Authentic Gaming*

http://www.authenticgaming.com

email: antonio.spalluto@authenticgaming.com
phone: 00 356 9912 7316
skype: antonio.authentic
linkedin: antoniospalluto

Disclaimer - The information contained in this message and any attachment
is intended for the recipient(s) designated only, is confidential and may
be privileged or otherwise protected from  disclosure. Therefore, the
contents of this message may not be re-transmitted, copied or revealed to a
third party without first obtaining the permission of the sender. If this
e-mail is received in error, please delete it immediately.

**Comment by AntonioSpalluto** [comment]
Hi All,

I have a problem with the return of the ETag response header parameter. I just upgraded the version to the 2.0.1 but now I am not getting any etag like it was supposed to be.
You can test it from this url: http://ag-messagebroker.westeurope.cloudapp.azure.com:8080/info/statistics/agcasino-virtualroulette1/25

Thanks

**Comment by ujibang** [comment]
Etag response header is only returned on write requests (PUT, POST and PATCH). 

On GET you can retrieve it from the response body (_etag property)

**Comment by AntonioSpalluto** [comment]
Hi Andrea,

This is quite strange, usually the ETag parameter is always returned into the response header in order to cache it at browser level. In this way it is useless for caching purposes.

What do you think about it?

Thanks

**Comment by ujibang** [comment]
Hi @AntonioSpalluto 

you are right, bug confirmed. will fix asap

**Comment by AntonioSpalluto** [comment]
Thanks.

Looking forward for the new release!

**Comment by ujibang** [comment]
hi, this is fixed now in 2.0.x branch

will release 2.0.2 next week

thanks for reporting

**Comment by mkjsix** [comment]
@AntonioSpalluto @ujibang Release 2.0.2 is available now.
https://github.com/SoftInstigate/restheart/releases/tag/2.0.2

**Comment by AntonioSpalluto** [comment]
Thanks a lot for the quick fix
