### ISSUE TITLE
How to add new data element to a document?

### ISSUE THREAD

**Issue by mohankv** [SoftInstigate/restheart#84]
How to add new data element to a document?

I need to add new array element to an existing document. I tired to use methods PUT and PATCH; they both replace the whole document with new data. 

And I also have a requirement to update the document partially. For instance, initially a document is created with basic profile data. Additional properties like work phone and mobile numbers need to be added without fetching the whole document.

**Comment by ujibang** [comment]
PATCH is for partial updates. With PATCH, only the passed properties gets updated. Note that you can use the dot notation.

Say that you have document /db/coll/doc as follows:

```
{
"num": 1,
"array": ["a","b","c"],
"obj": { "x": 1, "y": 2 }
}
```

You can update *num* and *obj.x* with:

```
PATCH /db/coll/doc  {"num": 2, "obj.x": 100 }
```

You can also update *array*:

```
PATCH /db/coll/doc  {"array.0": "updated", "array.3": "new element" }
```

Note that referring to the 4th element of the array actually adds an element:

```
{
"num": 2,
"array": ["updated","b","c", "new element"],
"obj": { "x": 100, "y": 2 }
}
```

**Comment by mohankv** [comment]
Thanks Andrea! That helps a lot.
one more question: How to push an element to an array without specifying index?

**Comment by ujibang** [comment]
Hi @mohankv 

currently you cannot push (or pop) an element to an array. You have to calculate the index from the existing document (that you need anyway to get the ETag).

However this is planned for new version. More info at https://softinstigate.atlassian.net/browse/RH-19
