### ISSUE TITLE
How to add custom _links

### ISSUE THREAD

**Issue by AntonioSpalluto** [SoftInstigate/restheart#85]
Is there any way to add some custom _links into a document?

Cheers

**Comment by ujibang** [comment]
Hi Antonio,

the only way to modify the _links is defining a relationship; this will add the referenced documents between the _links

https://softinstigate.atlassian.net/wiki/x/iYCM

What is your use case?

You can also modify the getRepresentation() method of the class [DocumentRepresentationFactory](https://github.com/SoftInstigate/restheart/blob/master/src/main/java/org/restheart/handlers/document/DocumentRepresentationFactory.java) adding links

```
Representation rep;
...
rep.addLink(new Link("example", "http://example.com"));
...
```

**Comment by AntonioSpalluto** [comment]
Hi Andrea,

I need to add some "templated" links, so I cannot use the relationship in
this case due I should specify an ObjectID.
I would prefer to avoid customization of the source code for maintenance
reasons... are you thinking to add it in some of the next releases?

Thanks for the prompt reply

On Mon, 4 Jan 2016 at 14:44 Andrea Di Cesare <notifications@github.com>
wrote:

> Hi Antonio,
>
> the only way to modify the _links is defining a relationship; this will
> add the referenced documents between the _links
>
> https://softinstigate.atlassian.net/wiki/x/iYCM
>
> What is your use case?
>
> You can also modify the getRepresentation() method of the class
> DocumentRepresentationFactory
> <https://github.com/SoftInstigate/restheart/blob/master/src/main/java/org/restheart/handlers/document/DocumentRepresentationFactory.java>
> adding links
>
> Representation rep;
> ...
> rep.addLink(new Link("example", "http://example.com"));
> ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SoftInstigate/restheart/issues/85#issuecomment-168679195>
> .
>
-- 

*Antonio Spalluto*
*Chief Technology Officer*

*Authentic Gaming*

http://www.authenticgaming.com

email: antonio.spalluto@authenticgaming.com
phone: 00 356 9912 7316
skype: antonio.authentic
linkedin: antoniospalluto

Disclaimer - The information contained in this message and any attachment
is intended for the recipient(s) designated only, is confidential and may
be privileged or otherwise protected from  disclosure. Therefore, the
contents of this message may not be re-transmitted, copied or revealed to a
third party without first obtaining the permission of the sender. If this
e-mail is received in error, please delete it immediately.

**Comment by ujibang** [comment]
Hi Antonio,

I'm sorry but we don't have anything for this in our roadmap. If you want us to add it to restheart then you'll need to buy a custom development package.

Please refer to http://restheart.org/support-packages.html
