### ISSUE TITLE
"reserved resource" message while using Aggregation at remote server

### ISSUE THREAD

**Issue by hemraj-sharma** [SoftInstigate/restheart#86]
Hi, 
       I am using aggregation query, supported from the RS-1.1.1. Its working fine on my local db and restheart. When I try to execute it on the remote-db and restheart, it is giving "reserved resource" message.I am having same configuration at both places. I have a great hope of any reply from your end.
Regards,
Hemraj

**Comment by hemraj-sharma** [comment]
the message I am getting is:
{
  "_embedded": {},
  "_links": {
    "self": {
      "href": "/db_name/products/_aggrs/aggr_name"
    }
  },
  "http status code": 403,
  "http status description": "Forbidden",
  "message": "reserved resource"
}

Do you know any way to get rid of this.
regards,
Hemraj

**Comment by ujibang** [comment]
Can you double check the version of the remote restheart?

**Comment by hemraj-sharma** [comment]
does db version also matters, at my machine it is 3.0.7, but at remote it is 2.6.11

**Comment by ujibang** [comment]
It should only matter the restheart version

Resources whose name start with _ are reserved (cannot be used).

For instance, you cannot create a document with id _aggrs (that URI is used to map aggregations).

**Comment by hemraj-sharma** [comment]
Thanks it works for me now
