### ISSUE TITLE
Connecting to Database that is using SSL

### ISSUE THREAD

**Issue by merrickkw** [SoftInstigate/restheart#88]
Hi I understand that RESTHeart allows you to host the web service with SSL.
However in order to connect to database server that is using SSL certificate file (PEM) provided by the client, I need to set the System.Properties before-hand

Please add an easy implementation of this by adding the following settings in your properties file (maybe at YAML restheart.yml); I believe this will ease lot of people that don't have background on SSL with JAVA.

javax.net.ssl.keyStore
javax.net.ssl.keyStorePassword
javax.net.ssl.keyType
javax.net.ssl.trustStore
javax.net.ssl.trustStorePassword
javax.net.ssl.trustStoreType

**Comment by ujibang** [comment]
Hi @merrickkw,

I have added this to our roadmap: https://softinstigate.atlassian.net/browse/RH-148

thanks for your suggestion.
