### ISSUE TITLE
How to enter Date object into db using restheart

### ISSUE THREAD

**Issue by hemraj-sharma** [SoftInstigate/restheart#89]
As in java , while entering value for updatedOn as new Date(), How can we do the same through restheart. I need date to be stored  as ISO object.As:
"updatedOn" : ISODate("2015-12-30T07:04:37.478Z"),

**Comment by ujibang** [comment]
you need to use $date passing the epoch time in milliseconds

example:
```
http -a a:a PUT 127.0.0.1:8080/test/coll/date date:='{"$date": 1452161503000}'
```

from mongo shell you can check that it is actually stored as an ISODate

```
> db.coll.find({_id: "date"})
{ "_id" : "date", "date" : ISODate("2016-01-07T10:11:43Z"), "_etag" : ObjectId("568e3a2b2d174c8c299fa95c") }
```

more info on the representation format at https://softinstigate.atlassian.net/wiki/x/UICM

**Comment by hemraj-sharma** [comment]
thanks this is working fine for me

**Comment by caarto** [comment]
@ujibang 
i setup httpie tools for REST test,  
i put this line in the cmd
```http -a a:a GET 192.168.138.36:20080/ivms/CLTX/20160221203711068739 clpp='{"$date": 1456105418163}'```
and got an erro below
```
usage: http [--json] [--form] [--pretty {all,colors,format,none}]
            [--style STYLE] [--print WHAT] [--verbose] [--headers] [--body]
            [--stream] [--output FILE] [--download] [--continue]
            [--session SESSION_NAME_OR_PATH | --session-read-only SESSION_NAME_OR_PATH]
            [--auth USER[:PASS]] [--auth-type {basic,digest}]
            [--proxy PROTOCOL:PROXY_URL] [--follow] [--verify VERIFY]
            [--cert CERT] [--cert-key CERT_KEY] [--timeout SECONDS]
            [--check-status] [--ignore-stdin] [--help] [--version]
            [--traceback] [--debug]
            [METHOD] URL [REQUEST_ITEM [REQUEST_ITEM ...]]
http: error: "clpp:='{$date:1456105418163}'": Expecting value: line 1 column 1 (char 0)
```

what do I miss when I use this tool.
