### ISSUE TITLE
Repackaging to org.restheart

### ISSUE THREAD

**Issue by msuchecki** [SoftInstigate/restheart#9]
Have you considered repackaging com.softinstigate.restheart to org.restheart? That would be nice gesture for the community.

**Comment by mkjsix** [comment]
Yes, we totally agree and we're going to start the related refactoring within today or tomorrow, we only want to finalize a couple of merges first.

**Comment by mkjsix** [comment]
Refactoring is done and available with latest 0.9.8-SNAPSHOT on develop branch (also tag RH-45).
It will be available on master for next 0.9.8 stable in few days.
