### ISSUE TITLE
Does restheart has "NO_REQUEST_TIMEOUT"?

### ISSUE THREAD

**Issue by chunlunglin** [SoftInstigate/restheart#91]
Hi sir,

We setup the restheart to behind the firewall, now we have a problem.
After running for a while, all connection seems remain in established state and never been released,
the client side is using "System.Net.WebClient" to establish the connection.
And finally, the total connections reach the limit and it cannot serve new request anymore.

Does restheart close the connection automatically if some timeout reached?

Thanks.

**Comment by ujibang** [comment]
setting NO_REQUEST_TIMEOUT is not currently possible.

However we will do it asap since we think this is a critical issue. I created an issue in our jira instance to track and document this: https://softinstigate.atlassian.net/browse/RH-150

it will be fixed in next release 1.1.4

**Comment by ujibang** [comment]
hello @chunlunglin 

we completed the task https://softinstigate.atlassian.net/browse/RH-150

now you can configure NO_REQUEST_TIMEOUT (and more). Have a look at the configuration file for in the connection-options section https://github.com/SoftInstigate/restheart/blob/master/etc/restheart-dev.yml

this will be available in next release 1.2 (you can of course build restheart to try)

**Comment by chunlunglin** [comment]
That's great! Thank you so much!
