### ISSUE TITLE
Notifications on finished binary file insert

### ISSUE THREAD

**Issue by chrwuill** [SoftInstigate/restheart#92]
Hi
I'm using RESTHeart for storing and retrieving binary files from MongoDB. While this is working great I'm now looking for a way to get notifications on finished binary file inserts: I need to be able to notify listeners on finished file uploads. Is there a way to retrieve the information, that a specific POST request (uploading a new file) has finished successfully? Any hints how I could do this?

(I looked at representation transformers and while this enables me to take action for a request on my .files collection - such as posting a new file - I don't see how I can wait for the finished upload at this point. Also I saw the issue about webhooks https://softinstigate.atlassian.net/browse/RH-73, but it's not available yet.)

**Comment by mkjsix** [comment]
Hi,
We think the correct way to implement this feature would actually be to use Webhooks. Issue RH-73 has been delayed by other requests and it has been tentatively postponed to version 1.3 (it could mean a couple of months from now), unfortunately we don't have enough bandwidth to accomodate all the new features at the moment. Things might change in case some of our paying customers would have a similar need, in that case we could allocate additional resources for the task.

**Comment by chrwuill** [comment]
Webhooks seem to be the best way indeed. All right thanks for your quick response and I'm looking forward for future releases.

**Comment by mkjsix** [comment]
As this is quite an interesting feature anyway, we'll try to push up its priority as much as we can.

**Comment by mkjsix** [comment]
https://softinstigate.atlassian.net/browse/RH-73
