### ISSUE TITLE
Does restheart support "Replica Set"?

### ISSUE THREAD

**Issue by chunlunglin** [SoftInstigate/restheart#93]
Hi Sir,

Does restheart support Replica Set? How to configure it?

Thanks.

**Comment by ujibang** [comment]
Yes it does.

Connection to replica set is configured via mongo-uri option.

Refer to https://docs.mongodb.org/manual/reference/connection-string/ for detailed info about the mongo-uri format.

This page includes the following example:

The following connects to a replica set with two members, one on db1.example.net and the other on db2.example.net:

mongodb://db1.example.net,db2.example.com
