### ISSUE TITLE
HAL user interface does not run

### ISSUE THREAD

**Issue by caporossi** [SoftInstigate/restheart#96]
RESTHeart 1.1.3
Mongodb 3.2

all installed in windows 8.1

json interface works correctly

HAL user interface does not appear, at http://127.0.0.1:8080/browser

Ciao

**Comment by mkjsix** [comment]
Hi,
Are you building it on your own? In this case you might have forgotten to include the HAL Browser submodule before: https://github.com/SoftInstigate/restheart#how-to-build-it

**Comment by caporossi** [comment]
Hi
the first attempt was made using the file found here
https://github.com/SoftInstigate/restheart/releases/download/1.1.3/restheart-1.1.3.zip

the second attempt
cloning the project and then executing
$ Git submodule update --init --recursive
$ Mvn clean package

the result is the same

 the REST interface works well but does not appear HAL user interface  at http://127.0.0.1:8080/browser

Ciao

**Comment by mkjsix** [comment]
I downloaded the same ZIP file and uncompressed it. It works for me (Mac OSX).

This is what I did:

```
$ cd restheart-1.1.3

$ java -server -jar restheart.jar 

15:59:52.379 [main] INFO  org.restheart.Bootstrapper - Starting RESTHeart
15:59:52.385 [main] INFO  org.restheart.Bootstrapper - version 1.1.3
15:59:52.393 [main] INFO  org.restheart.Bootstrapper - Logging to /var/folders/pk/56szmnfn5zlfxh2x6tkd5wqw0000gn/T/restheart.log with level INFO
15:59:52.394 [main] INFO  org.restheart.Bootstrapper - Logging to console with level INFO
15:59:52.757 [main] INFO  org.restheart.Bootstrapper - MongoDB connection pool initialized
15:59:52.757 [main] INFO  org.restheart.Bootstrapper - MongoDB version 3.0.7
15:59:52.757 [main] WARN  org.restheart.Bootstrapper - ***** No identity manager specified. authentication disabled.
15:59:52.757 [main] WARN  org.restheart.Bootstrapper - ***** No access manager specified. users can do anything.
15:59:52.758 [main] INFO  org.restheart.Bootstrapper - Token based authentication enabled with token TTL 15 minutes
15:59:53.063 [main] INFO  org.restheart.Bootstrapper - HTTPS listener bound at 0.0.0.0:4443
15:59:53.064 [main] INFO  org.restheart.Bootstrapper - HTTP listener bound at 0.0.0.0:8080
15:59:53.066 [main] INFO  org.restheart.Bootstrapper - Local cache for db and collection properties enabled
15:59:53.131 [main] INFO  org.restheart.Bootstrapper - URL / bound to MongoDB resource *
15:59:53.278 [main] INFO  org.restheart.Bootstrapper - Embedded static resources browser extracted in /var/folders/pk/56szmnfn5zlfxh2x6tkd5wqw0000gn/T/restheart-721672425989387685
15:59:53.312 [main] INFO  org.restheart.Bootstrapper - URL /browser bound to static resources browser. access manager: false
15:59:53.602 [main] INFO  org.restheart.Bootstrapper - Pid file /var/folders/pk/56szmnfn5zlfxh2x6tkd5wqw0000gn/T/restheart-0.pid
15:59:53.603 [main] INFO  org.restheart.Bootstrapper - RESTHeart started
```

Do you see the same **Embedded static resources browser extracted in** log entry?
Could you copy here the startup logs as well?
Which Browser are you using, by the way?

**Comment by mkjsix** [comment]
Additionally, could you please confirm you can see our public instance here: http://dbapi.io/browser/#/db/coll

**Comment by caporossi** [comment]
sorry for the delay

It is not a browser problem
 here you can see the screenshot of http://dbapi.io/browser/#/db/coll
![hal_1](https://cloud.githubusercontent.com/assets/292378/12399769/3e194a1a-be1c-11e5-9045-204f915a20b2.PNG)


attached you can find the log file

[restheart.zip](https://github.com/SoftInstigate/restheart/files/94851/restheart.zip)


and other screenshots that can help you figure out where the problem is.
![hal_2](https://cloud.githubusercontent.com/assets/292378/12399847/b13e751a-be1c-11e5-9eb4-d67e19f52b21.PNG)
![hal_3](https://cloud.githubusercontent.com/assets/292378/12399850/b5879fca-be1c-11e5-8afa-2853f026bd19.PNG)
![hal_4](https://cloud.githubusercontent.com/assets/292378/12399857/bb680ace-be1c-11e5-9fd4-570ab4b2e4b6.PNG)
![hal_5](https://cloud.githubusercontent.com/assets/292378/12399861/bef95bca-be1c-11e5-9f41-c6cc53ccc4b1.PNG)




I found in C: \ Users \ gcaporossi \ AppData \ Local \ Temp \ restheart-1138963426701355955 a folder containing Hal browser but for some reason does not work.

how do you see the rest interface works fine.

thank you

**Comment by mkjsix** [comment]
I downloaded your restheart.zip file but it's only 22 bytes and looks empty. Could you please copy and paste here the initial few lines of the restheart's log? From "Starting RESTHeart" to "RESTHeart started".

It looks like a Windows specific issue, but that's weird and we're trying to reproduce it locally.

**Comment by ujibang** [comment]
Hi @caporossi 

question: what does restheart return requesting http://127.0.0.1:8080/browser? Is it NOT FOUND, OK with empty response or other?

**Comment by caporossi** [comment]
Hi @mkjsix 
below you can find the log file

10:08:16.844 [main] [34mINFO [0;39m org.restheart.Bootstrapper - Starting [31;1mRESTHeart[m
10:08:16.848 [main] [34mINFO [0;39m org.restheart.Bootstrapper - version 1.2.0-SNAPSHOT
10:08:16.850 [main] [34mINFO [0;39m org.restheart.Bootstrapper - Logging to C:\Users\GCAPOR~1\AppData\Local\Temp\\restheart.log with level INFO
10:08:16.850 [main] [34mINFO [0;39m org.restheart.Bootstrapper - Logging to console with level INFO
10:08:17.063 [main] [34mINFO [0;39m org.restheart.Bootstrapper - MongoDB connection pool initialized
10:08:17.064 [main] [34mINFO [0;39m org.restheart.Bootstrapper - MongoDB version 3.2.1
10:08:17.064 [main] [31mWARN [0;39m org.restheart.Bootstrapper - ***** No identity manager specified. authentication disabled.
10:08:17.065 [main] [31mWARN [0;39m org.restheart.Bootstrapper - ***** No access manager specified. users can do anything.
10:08:17.065 [main] [34mINFO [0;39m org.restheart.Bootstrapper - Token based authentication enabled with token TTL 15 minutes
10:08:17.187 [main] [34mINFO [0;39m org.restheart.Bootstrapper - HTTPS listener bound at 0.0.0.0:4443
10:08:17.187 [main] [34mINFO [0;39m org.restheart.Bootstrapper - HTTP listener bound at 0.0.0.0:8080
10:08:17.188 [main] [34mINFO [0;39m org.restheart.Bootstrapper - Local cache for db and collection properties enabled with TTL 1000 msecs
10:08:17.189 [main] [34mINFO [0;39m org.restheart.Bootstrapper - Local cache for schema stores not enabled
10:08:17.258 [main] [34mINFO [0;39m org.restheart.Bootstrapper - URL / bound to MongoDB resource *
10:08:17.335 [main] [34mINFO [0;39m org.restheart.Bootstrapper - Embedded static resources browser extracted in C:\Users\GCAPOR~1\AppData\Local\Temp\restheart-6993791002747932008
10:08:17.346 [main] [34mINFO [0;39m org.restheart.Bootstrapper - URL /browser bound to static resources browser. access manager: false
10:08:17.424 [main] [34mINFO [0;39m org.restheart.Bootstrapper - [32;1mRESTHeart started[m



Hi @ujibang at  http://127.0.0.1:8080/browser i have an empty resonse
if I try a path that does not exist for example http://127.0.0.1:8080/brooooowser the response is
{ "_links" : { "self" : { "href" : "/brooooowser"}} , "http status code" : 404 , "http status description" : "Not Found" , "message" : "Db 'brooooowser' does not exist"}


ciao

**Comment by mkjsix** [comment]
My only hypothesis so far is that some of the extracted files have a too long filesystem path

> In the Windows API the maximum length for a path is MAX_PATH, which is defined as 260 characters

Could you please try extracting restheart.zip directly under C:\ and verify is something changes? I'd like to test if it's really a path issue or not.

Additionally, I also suggest opening the Chrome's Javascript console and have a look at any error message when loading the HAL Browser

**Comment by caporossi** [comment]
Sorry for the delay
but these days are really busy!!!

I copied RestHeart in c: / but the result does not change.

in Chrome's Javascript console when I call the url  http://127.0.0.1:8080/browser  I have this result
<b>Request headers</b>
GET /browser HTTP/1.1
Host: 127.0.0.1:8080
Connection: keep-alive
Cache-Control: max-age=0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: it,en;q=0.8,en-US;q=0.6

<b>Response headers</b>
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 0
Date: Tue, 19 Jan 2016 20:56:45 GMT

as you can see, the response is 404 but the content-lenght is 0 and the page is blank

I call the url  http://127.0.0.1:8080/browserother  I have this result
<b>Request headers</b>
GET /browserother HTTP/1.1
Host: 127.0.0.1:8080
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: it,en;q=0.8,en-US;q=0.6

<b>Response headers</b>
HTTP/1.1 404 Not Found
Content-Encoding: gzip
X-Powered-By: restheart.org
Access-Control-Expose-Headers: Location, ETag, Auth-Token, Auth-Token-Valid-Until, Auth-Token-Location, X-Powered-By
Date: Tue, 19 Jan 2016 21:06:46 GMT
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Content-Type: application/hal+json
Content-Length: 139
Request Headers
view parsed


as you can see, the response is 404 but the content-lenght is 139 and the page show
{ "_links" : { "self" : { "href" : "/browserother"}} , "http status code" : 404 , "http status description" : "Not Found" , "message" : "Db 'browserother' does not exist"}

it seems that the web server of RestHeart can not map the virtual directory "/ browser" on the temporary folder generated in C: \ Users \ gcaporossi \ AppData \ Local \ Temp \ restheart-4020986507088336037

Ciao

**Comment by ujibang** [comment]
I noticed in the log the message

```
Embedded static resources browser extracted in C:\Users\GCAPOR~1\AppData\Local\Temp\restheart-6993791002747932008
```

but I guess the files are actually in:

```
 C: \Users\gcaporossi\AppData\ Local\Temp\restheart-6993791002747932008 
```

so **GCAPOR~1** should be **gcaporossi**

@caporossi my suggestion is setting the environment variable **%TEMP%** property and try again.

**Comment by caporossi** [comment]
hi
I first changed the environment variable % TEMP% in c:/Windows/temp but not work, I think a problem of acess.

I finally created a directory in  c:/Temp and set the environment variable%TEMP% in c:/Temp

in this folder all users have read and write and now everything is working correctly.

thank you

Gianluca
