### ISSUE TITLE
/browser url has gone?

### ISSUE THREAD

**Issue by caarto** [SoftInstigate/restheart#97]
hi there:
we update the rh version to 1.1.3,and we found the rh's /browser url gone.

envirment:mongodb 3.2.1,rh:1.1.3(rh configuration file unchange),other software unchange

is there any  change i missed

**Comment by caarto** [comment]
and we found that rh lost the mongodb's connection

thanks

**Comment by caarto** [comment]
oh, we found that the configuration file has change on v1.1.0.
we will modify the file first

**Comment by caarto** [comment]
now we change the mongo uri,we get the connection back,
and we open the log,we find the /browser url has restore in the program.
here is the log
<code>
18:50:32.200 [WrapperSimpleAppMain] [34mINFO [0;39m org.restheart.Bootstrapper - URL / bound to MongoDB resource *
18:50:32.362 [WrapperSimpleAppMain] [34mINFO [0;39m org.restheart.Bootstrapper - Embedded static resources browser extracted in C:\Windows\TEMP\restheart-2299394304607780896
18:50:32.370 [WrapperSimpleAppMain] [34mINFO [0;39m org.restheart.Bootstrapper - URL /browser bound to static resources browser. access manager: false
18:50:32.373 [WrapperSimpleAppMain] [34mINFO [0;39m org.restheart.Bootstrapper - URL /_logic/ping bound to application logic handler org.restheart.handlers.applicationlogic.PingHandler. access manager: false
18:50:32.374 [WrapperSimpleAppMain] [34mINFO [0;39m org.restheart.Bootstrapper - URL /_logic/roles bound to application logic handler org.restheart.handlers.applicationlogic.GetRoleHandler. access manager: false
18:50:32.375 [WrapperSimpleAppMain] [34mINFO [0;39m org.restheart.Bootstrapper - URL /_logic/ic bound to application logic handler org.restheart.handlers.applicationlogic.CacheInvalidator. access manager: true
</code>
and we change check the location the rh release the temp file in "C:\Windows\TEMP\restheart-2299394304607780896".
and there is a browser.html.
when we request /browser in chrome, we receive browser.html 404 in console.

**Comment by caarto** [comment]
we change the rh v 1.1.0,we got the /browser back,and the edition over the v1.1.0 ,we can not got the browser url

**Comment by mkjsix** [comment]
Please check if this issue is of any help: https://github.com/SoftInstigate/restheart/issues/96

**Comment by ujibang** [comment]
Hi @caarto,

are you using the jar from the release .tar.gz/.zip or you got it from the maven repo?

we realized that the jar in the maven repository does not include the browser.

we are updating the publication process to fix it....

**Comment by mkjsix** [comment]
Meanwhile we've released v 1.1.4 https://github.com/SoftInstigate/restheart/releases/tag/1.1.4

**Comment by caarto** [comment]
thanks for your response.
we change a short dir for the tmp file and it works.
in the windows,the tmp file dir must set UPPERCASE D:/ or C:/
